### ISSUE TITLE
Error after saving favicon.png: spawn convert ENOENT at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)

### ISSUE THREAD

**Issue by danielboven** [openzim/mwoffliner#1031]
Hi,
I have been trying out _mwoffliner_ on my laptop for some time and I quite like it. Now I have followed the same installation procedure for installing it on my desktop (I use NVM on both) but I keep getting this error in the terminal, after it's saving `favicon.png`:

```
[log] [2020-02-10T21:25:38.059Z] Saving favicon.png...
{"name":"mwoffliner","hostname":"ubuntu-workstation","pid":11893,"level":60,"err":{"message":"","name":"Error","stack":"Error: spawn convert ENOENT\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)\n    at onErrorNT (internal/child_process.js:415:16)\n    at process._tickCallback (internal/process/next_tick.js:63:19)","code":"ENOENT","errno":"ENOENT","syscall":"spawn convert","path":"convert","spawnargs":["/tmp/mwoffliner-1581369933454/favicon.png","-thumbnail","48","/tmp/mwoffliner-1581369933454/favicon.png"],"levelPath":"fatal/service-runner/unhandled"},"msg":"spawn convert ENOENT","time":"2020-02-10T21:25:38.870Z","v":0}
{"name":"mwoffliner","hostname":"ubuntu-workstation","pid":11893,"level":60,"errno":"ENOENT","code":"ENOENT","syscall":"spawn convert","path":"convert","spawnargs":["/tmp/mwoffliner-1581369933454/favicon.png","-thumbnail","48","/tmp/mwoffliner-1581369933454/favicon.png"],"levelPath":"fatal/service-runner/unhandled","msg":"spawn convert ENOENT","time":"2020-02-10T21:25:38.870Z","v":0}
[log] [2020-02-10T21:25:38.970Z] Exiting with code [1]
```

I use Node v10.18.1 and tried running mwoffliner as a global package (command), but also as described in [CONTRIBUTING.md](https://github.com/openzim/mwoffliner/blob/master/CONTRIBUTING.md) (with `npm start --`). Both of these methods work great on my laptop btw.

This is a full npm debug log that is generated when using `npm start` (as described in [CONTRIBUTING.md](https://github.com/openzim/mwoffliner/blob/master/CONTRIBUTING.md)):

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/daan/.nvm/versions/node/v10.18.1/bin/node',
1 verbose cli   '/home/daan/.nvm/versions/node/v10.18.1/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--mwUrl=https://algorithmist.com/',
1 verbose cli   '--adminEmail=yimep39028@reptech.org',
1 verbose cli   '--outputDirectory=/home/daan/Documents/projects/mediawiki/zim/scraping/10-02-2020',
1 verbose cli   '--redis=redis://127.0.0.1:6379' ]
2 info using npm@6.13.4
3 info using node@v10.18.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle mwoffliner@1.9.14~prestart: mwoffliner@1.9.14
6 info lifecycle mwoffliner@1.9.14~start: mwoffliner@1.9.14
7 verbose lifecycle mwoffliner@1.9.14~start: unsafe-perm in lifecycle true
8 verbose lifecycle mwoffliner@1.9.14~start: PATH: /home/daan/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/daan/Documents/projects/mediawiki/zim/mwoffliner/node_modules/.bin:/home/daan/.nvm/versions/node/v10.18.1/bin:/opt/lampp/bin/:/opt/node-v12.6.0-linux-x64/bin:/home/daan/.npm-global/bin:/home/daan/.local/bin:/home/daan/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle mwoffliner@1.9.14~start: CWD: /home/daan/Documents/projects/mediawiki/zim/mwoffliner
10 silly lifecycle mwoffliner@1.9.14~start: Args: [ '-c',
10 silly lifecycle   'ts-node ./src/cli.ts "--mwUrl=https://algorithmist.com/" "--adminEmail=yimep39028@reptech.org" "--outputDirectory=/home/daan/Documents/projects/mediawiki/zim/scraping/10-02-2020" "--redis=redis://127.0.0.1:6379"' ]
11 silly lifecycle mwoffliner@1.9.14~start: Returned: code: 1  signal: null
12 info lifecycle mwoffliner@1.9.14~start: Failed to exec start script
13 verbose stack Error: mwoffliner@1.9.14 start: `ts-node ./src/cli.ts "--mwUrl=https://algorithmist.com/" "--adminEmail=yimep39028@reptech.org" "--outputDirectory=/home/daan/Documents/projects/mediawiki/zim/scraping/10-02-2020" "--redis=redis://127.0.0.1:6379"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/daan/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/daan/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid mwoffliner@1.9.14
15 verbose cwd /home/daan/Documents/projects/mediawiki/zim/mwoffliner
16 verbose Linux 5.0.0-38-generic
17 verbose argv "/home/daan/.nvm/versions/node/v10.18.1/bin/node" "/home/daan/.nvm/versions/node/v10.18.1/bin/npm" "start" "--" "--mwUrl=https://algorithmist.com/" "--adminEmail=yimep39028@reptech.org" "--outputDirectory=/home/daan/Documents/projects/mediawiki/zim/scraping/10-02-2020" "--redis=redis://127.0.0.1:6379"
18 verbose node v10.18.1
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error mwoffliner@1.9.14 start: `ts-node ./src/cli.ts "--mwUrl=https://algorithmist.com/" "--adminEmail=yimep39028@reptech.org" "--outputDirectory=/home/daan/Documents/projects/mediawiki/zim/scraping/10-02-2020" "--redis=redis://127.0.0.1:6379"`
22 error Exit status 1
23 error Failed at the mwoffliner@1.9.14 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

How can I solve this error?

**Comment by kelson42** [comment]
@danielboven Might be that imagemagick (`convert`) is not installed?

**Comment by danielboven** [comment]
@kelson42 thank you for your comment! Running `apt-get install imagemagick` solved the problem. Is imagemagick listed as a dependency somewhere by the way? I can imagine that might be helpful for others as well

**Comment by kelson42** [comment]
@danielboven It should be tested properly at the start of `mwoffliner`, this looks like a regression to me. See https://github.com/openzim/mwoffliner/issues/491

**Comment by danielboven** [comment]
Ah that's clear, thank you @kelson42 for the information.
