### ISSUE TITLE
New unhandled promise scenario

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1060]
```
[log] [2020-03-21T00:00:15.045Z] Worker [19] Processing batch of [12] files
[log] [2020-03-21T00:00:15.114Z] Worker [6] Processing batch of [10] files
[log] [2020-03-21T00:00:15.179Z] Worker [0] Processing batch of [11] files
[log] [2020-03-21T00:00:15.210Z] Progress downloading files [28310/33459] [84.6%]
[log] [2020-03-21T00:00:15.249Z] Worker [22] Processing batch of [10] files
[log] [2020-03-21T00:00:15.303Z] Worker [5] Processing batch of [10] files
[log] [2020-03-21T00:00:15.315Z] Progress downloading files [28340/33459] [84.7%]
[log] [2020-03-21T00:00:15.380Z] Worker [9] Processing batch of [10] files
[log] [2020-03-21T00:00:15.440Z] Worker [7] Processing batch of [11] files
[log] [2020-03-21T00:00:15.472Z] Worker [10] Processing batch of [10] files
[log] [2020-03-21T00:00:15.502Z] Worker [20] Processing batch of [10] files
[log] [2020-03-21T00:00:15.509Z] Progress downloading files [28380/33459] [84.8%]
[log] [2020-03-21T00:00:15.528Z] Worker [2] Processing batch of [10] files
[log] [2020-03-21T00:00:15.541Z] Progress downloading files [28410/33459] [84.9%]
[log] [2020-03-21T00:00:15.565Z] Worker [13] Processing batch of [10] files
[log] [2020-03-21T00:00:15.598Z] Worker [17] Processing batch of [11] files
[log] [2020-03-21T00:00:15.649Z] Worker [8] Processing batch of [10] files
[log] [2020-03-21T00:00:15.700Z] Worker [16] Processing batch of [10] files
[log] [2020-03-21T00:00:15.768Z] Worker [14] Processing batch of [10] files
[log] [2020-03-21T00:00:15.799Z] Worker [11] Processing batch of [10] files
[log] [2020-03-21T00:00:15.842Z] Worker [15] Processing batch of [11] files
[log] [2020-03-21T00:00:15.904Z] Worker [18] Processing batch of [13] files
[log] [2020-03-21T00:00:16.042Z] Worker [1] Processing batch of [10] files
[log] [2020-03-21T00:00:16.133Z] Worker [4] Processing batch of [10] files
(node:1) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:202:11)
    at IncomingMessage.emit (events.js:203:15)
    at IncomingMessage.EventEmitter.emit (domain.js:448:20)
    at endReadableNT (_stream_readable.js:1143:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 30)
```

This process got stuck a few minutes afterward as well.

**Comment by kelson42** [comment]
@bakshiutkarsha Does this scenario can as well explain which the process somehow just get stuck?
