### ISSUE TITLE
ArchWiki embeded wiki links broken/not found

### ISSUE THREAD

**Issue by iTzHard** [openzim/mwoffliner#1127]
ZIM file obtained from Kiwix, applies to both fulltext index and fulltext index + pictures.

Examples: 
Main page --> Arch Linux --> Systemd [Broken]
Main page --> Frequently asked questions --> Arch Linux [Broken]

Applies to all pages that link to other pages (apart from the main page)

**Comment by kelson42** [comment]
I think the problem has been working... but now the whole wiki with the latest version of mwoffliner is not scrapable, I always get the same error (see https://farm.openzim.org/pipeline/5ecd1e0aa15fcb47c20934d9/debug):
```
[warn] [2020-05-26T14:11:39.182Z] Failed to get article [Mastodon_(Español)] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[warn] [2020-05-26T14:11:40.633Z] Failed to get article [Extra_keyboard_keys] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[warn] [2020-05-26T14:11:41.180Z] Failed to get article [Multihead] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by kelson42** [comment]
@bakshiutkarsha @midik Do you know what is going on here?

**Comment by kelson42** [comment]
@midik It seems a new run on a other server has been this time successfull https://farm.openzim.org/pipeline/5ecbfa66117427072994bec7.. so this is a sporadic bug and probably a symptom of something else.

**Comment by midik** [comment]
@kelson42 great, anyways, it's worth to add these null checks.

**Comment by kelson42** [comment]
@iTzHard We published a few days ago a new ZIM. The problem you reported seems fixed, see http://library.kiwix.org/archlinux_en_all_maxi_2020-05/. Therefore, I will close this ticket.

**Comment by kelson42** [comment]
@midik The new problem we have see is now reported in an other ticket, see https://github.com/openzim/mwoffliner/issues/1139
