### ISSUE TITLE
Latest MWoffliner has a new sporadic error pattern when using local Parsoid

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1139]
We did not had the problem before... but many wikis without Parsoid API are often failing with the following error:
```
[warn] [2020-05-26T14:11:39.182Z] Failed to get article [Mastodon_(Español)] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[warn] [2020-05-26T14:11:40.633Z] Failed to get article [Extra_keyboard_keys] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
[warn] [2020-05-26T14:11:41.180Z] Failed to get article [Multihead] using remote Parsoid, trying with local one TypeError: Cannot read property 'displaytitle' of undefined
    at renderMCSArticle (/tmp/mwoffliner/lib/util/articleRenderers.js:101:39)
    at /tmp/mwoffliner/lib/util/articleRenderers.js:54:26
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/mwoffliner/lib/util/articleRenderers.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

See for example:
* https://farm.openzim.org/pipeline/5ecd1e0aa15fcb47c20934d9/debug
* https://farm.openzim.org/pipeline/5ecf490218b11fb99e8bfa07/debug

It seems we have a problem in retrieving some kind of JSON.

**Comment by kelson42** [comment]
This problem does not occur anymore because of a better software architecture (we don't fallback during rendering).
