### ISSUE TITLE
Tests do not pass on Nodejs v14

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1188]
See CI

**Comment by kelson42** [comment]
I can reproduce the problem locally:
```
$ more /home/kelson/.npm/_logs/2020-06-24T19_43_43_148Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test:unit' ]
2 info using npm@6.14.5
3 info using node@v14.4.0
4 verbose run-script [ 'pretest:unit', 'test:unit', 'posttest:unit' ]
5 info lifecycle mwoffliner@1.10.8~pretest:unit: mwoffliner@1.10.8
6 info lifecycle mwoffliner@1.10.8~test:unit: mwoffliner@1.10.8
7 verbose lifecycle mwoffliner@1.10.8~test:unit: unsafe-perm in lifecycle true
8 verbose lifecycle mwoffliner@1.10.8~test:unit: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kelson/code/mwoffliner/node_modules/.bin:/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/kelson/code/mwoffliner/node_module
s/.bin:/home/kelson/.npm-global/bin:/home/kelson/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle mwoffliner@1.10.8~test:unit: CWD: /home/kelson/code/mwoffliner
10 silly lifecycle mwoffliner@1.10.8~test:unit: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'tape -r tsconfig-paths/register -r ts-node/register test/unit/*.test.ts | tap-spec'
10 silly lifecycle ]
11 silly lifecycle mwoffliner@1.10.8~test:unit: Returned: code: 1  signal: null
12 info lifecycle mwoffliner@1.10.8~test:unit: Failed to exec test:unit script
13 verbose stack Error: mwoffliner@1.10.8 test:unit: `tape -r tsconfig-paths/register -r ts-node/register test/unit/*.test.ts | tap-spec`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid mwoffliner@1.10.8
15 verbose cwd /home/kelson/code/mwoffliner
16 verbose Linux 5.4.0-37-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test:unit"
18 verbose node v14.4.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error mwoffliner@1.10.8 test:unit: `tape -r tsconfig-paths/register -r ts-node/register test/unit/*.test.ts | tap-spec`
22 error Exit status 1
23 error Failed at the mwoffliner@1.10.8 test:unit script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kelson42** [comment]
This seems to be only a porblem with the test. Normal MWoffliner seem to work fine.

**Comment by midik** [comment]
@kelson42 
> do not pass **at all**

Do you mean that's volatile error? Here are a few recent successful runs on v14:

- https://travis-ci.com/github/openzim/mwoffliner/jobs/353323961
- https://travis-ci.com/github/openzim/mwoffliner/jobs/353273210
- https://travis-ci.com/github/openzim/mwoffliner/jobs/353142574

**Comment by kelson42** [comment]
@midik I at the feeling they don't pass at all now, but you are right, under certain condition it seems to work... but most of the time it fails.

**Comment by kelson42** [comment]
Looks better since latest release of 14.5.0
