### ISSUE TITLE
ERR wrong number of arguments for 'hmget' command

### ISSUE THREAD

**Issue by steph-nb** [openzim/mwoffliner#1387]
Hi,

when running this command:
mwoffliner --verbose --keepEmptyParagraphs --outputDirectory ./downloads/ --articleList=https://de.wikipedia.org/wiki/Bodensee --mwUrl="https://de.wikipedia.org" --adminEmail=test@test.com

I get ERR wrong number of arguments for 'hmget' command

Many thanks in advance and BR,
Stephan

PS: Here some more log

%3C%2Fdiv%3E%3C%2Fdiv%3E%7C%3Cp%3EDie%20jahreszeitlich%20%3Ci%3Eh%C3%B6chsten%20Wasserst%C3%A4nde%3C%2Fi%3E%20entstehen%20meist%20im%20Fr%C3%BChjahr%2FSommer%20nach%20der%20Schneeschmelze%20%C3%BCber%203.000%26%23160%3Bm%20in%20den%20Alpen.%20Zus%C3%A4tzliche%20starke%20Regenf%C3%A4lle%20im%20Sommer%20im%20Einzugsgebiet%20des%20Alpenrheins%20(Schweiz)%2C%20der%20Bregenzer%20Ach%20(Bregenzer%20Wald)%20und%20von%20Schussen%20und%20Argen%20(Oberschwaben)%20k%C3%B6nnen%20den%20Wasserzufluss%20noch%20erh%C3%B6hen%20und%20zu%20Hochwasser%20f%C3%BChren.%3Csup%20id%3D%22cite_ref-Aurelia_Scherrer_2014_38-0%22%20class%3D%22reference%22%3E%3Ca%20href%3D%22%23cite_note-Aurelia_Scherrer_2014-38%22%3E%26%2391%3B38%26%2393%3B%3C%2Fa%3E%3C%2Fsup%3E&colimit=max]
[log] [2021-01-25T14:55:45.715Z] Got error from MW Query undefined
Failed to run mwoffliner after [3s]: {
        "stack": "ReplyError: ERR wrong number of arguments for 'hmget' command\n    at parseError (/usr/local/lib/node_modules/mwoffliner/node_modules/redis-parser/lib/parser.js:179:12)\n    at parseType (/usr/local/lib/node_modules/mwoffliner/node_modules/redis-parser/lib/parser.js:302:14)",
        "message": "ERR wrong number of arguments for 'hmget' command",
        "command": "HMGET",
        "args": [
                "1611586544729-detail"
        ],
        "code": "ERR"
}

**********

ERR wrong number of arguments for 'hmget' command

**********

[log] [2021-01-25T14:55:45.719Z] Exiting with code [2]
[log] [2021-01-25T14:55:45.719Z] Deleting temporary directory [/tmp/mwoffliner-1611586544732]

**Comment by kelson42** [comment]
At least, articleList is not an article list.

**Comment by steph-nb** [comment]
How would an articleList then look like?
Is the usage as indicated on this page not correct?
https://www.gitmemory.com/issue/openzim/mwoffliner/657/479797656

**Comment by steph-nb** [comment]
OK, got it, this one works:
mwoffliner --verbose --keepEmptyParagraphs --outputDirectory ./downloads/ --articleList=./articleList.txt --mwUrl="https://de.wikipedia.org" --adminEmail=test@test.com

Therefore I close the issue.
Thx a lot!

**Comment by tim-moody** [comment]
I am encountering this problem as well (from the end of the log):

```
[info] [2025-05-14T06:59:04.000Z] Getting JSON from [https://en.wikipedia.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages%7Ccoordinates&rdlimit=max&rdnamespace=0&redirects=true&formatversion=2&titles=ARO-APOC3&colimit=max]
[warn] [2025-05-14T06:59:04.071Z] Ignoring articles without revisions: ARO-APOC3
[error] [2025-05-14T06:59:04.072Z] Failed to run mwoffliner after [2s]: {
        "message": "ERR wrong number of arguments for 'hmget' command"
}
[error] [2025-05-14T06:59:04.072Z]

**********

ERR wrong number of arguments for 'hmget' command

**********


[log] [2025-05-14T06:59:04.073Z] Exiting with code [2]
```

The run command is:

 ```
 mwoffliner \
  --adminEmail="info@iiab.me" \
  --articleList="/lists/debug.tsv" \
  --customMainPage="Main" \
  --customZimTitle="Debug" \
  --customZimDescription="list from enwp." \
  --customZimFavicon="https://en.wikipedia.org/static/images/project-logos/enwiki.png" \
  --filenamePrefix="debug" \
  --mwUrl="https://en.wikipedia.org/" \
  --format="novid:maxi" --format="" \
  --osTmpDir="/dev/shm" \
  --outputDirectory="/output" \
  --forceRender="RestApi" \
  --requestTimeout="300" \
  --speed="1" \
  --webp \
  --verbose
```

The articleList is:

`ARO-APOC3
`

The response for the query

`https://en.wikipedia.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions&rdlimit=max&rdnamespace=0%7C3000%7C3002&redirects=true&formatversion=2&titles=ARO-APOC3
`
is

`{"batchcomplete":true,"warnings":{"redirects":{"warnings":"Unrecognized values for parameter \"rdnamespace\": 3000, 3002"}},"query":{"pages":[{"ns":0,"title":"ARO-APOC3","missing":true}]},"limits":{"redirects":500}}
`

I have seen this error from other pages on both enwp and mdwiki where the page does not exist, but the wiki returns a message to add it rather than an error.

**Comment by tim-moody** [comment]
To be clear, this issue crashes mwoffliner.

The problem can arise if a title is removed or renamed after the article list, like medicine.tsv, has been generated.

**Comment by benoit74** [comment]
This is already fixed in `main` in fact, see https://farm.openzim.org/pipeline/a4fef35f-c280-4adc-9b9f-b05604dbd1c1/debug which failed only because too many articles failed to download, not because of this error. I will comment on other issue regarding this failure.

Note that we plan to release this as 1.15.0 "soon".

**Comment by benoit74** [comment]
Error occurred again with 1.15.0 on one specific recipe: https://farm.openzim.org/recipes/wikipedia_pt_football

Occurred twice in a row, so it is easy to reproduce / debug / fix, and not a random failure:
- https://farm.openzim.org/pipeline/4410d825-7bf5-4746-ba3b-8e28481cfc06
- https://farm.openzim.org/pipeline/9a76d4b5-547c-4d43-9188-264f3cd3838d
