### ISSUE TITLE
mwoffliner does no start anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#140]
After refactor:

```
$ ./bin/mwoffliner.script.js --mwUrl=https://en.wikipedia.org/ --format=novid --verbose --adminEmail=kelson@kiwix.org --withZimFullTextIndex
module.js:491
    throw err;
    ^

Error: Cannot find module 'mwoffliner.lib'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/mwoffliner/lib/mwoffliner.vars.js:31:23)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)

```

Kind of not clear why this does not appeared as I have tested the branch...

I have achieved to fixed it... but then appears an other bug...

**Comment by kelson42** [comment]
@darkenvy @subbuss ideas?

**Comment by kelson42** [comment]
@darkenvy This is related to the "refactor" branch. @subbuss has removed the problematic commit and put it back (and rebased!?) the "refactor" branch. Would be great if you could fix it and make a new PR. Meanwhile I close this ticket as the problem has been "fixed" on git master.
