### ISSUE TITLE
Unexpected token < in JSON at position 0 on LDAP login

### ISSUE THREAD

**Issue by erbap** [openzim/mwoffliner#1403]
Hi,

Our local mediawiki's are migrating to 1.35.0 (5280de9) with ldaps integration
LDAPProvider: 1.0.5 (a5cd785)
LDAPAuthentication2: 1.0.2 (771b91e)
LDAPAuthorization: 1.1.0 (e037664)

When I run:
```
mwoffliner --mwUrl=https://<my url>/ --adminEmail=<my e-mail> --mwWikiPath=/ --mwApiPath=/api.php --mwModulePath=/load.php --redis=redis://127.0.0.1:6379 --verbose --mwUsername=<my user> --mwPassword='<my secret>' --mwDomain=<my domain>
```

I get the error:
```
[log] [2021-02-25T08:44:49.500Z] closing sanitize redis DB
[log] [2021-02-25T08:44:49.502Z] Starting mwoffliner v1.11.3...
[info] [2021-02-25T08:44:49.504Z] Using custom flavour: no
[info] [2021-02-25T08:44:49.511Z] Downloading [https://<my url>/api.php?&lgdomain=<my domain>action=query&meta=tokens&type=login&format=json]
Failed to run mwoffliner after [1s]: {
	"stack": "SyntaxError: Unexpected token < in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at MediaWiki.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/MediaWiki.js:79:39)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/MediaWiki.js:24:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "Unexpected token < in JSON at position 0"
}
```
I see that there is nothing between "<my domain>" and "action" in the line
```
[info] [2021-02-25T08:44:49.511Z] Downloading [https://<my url>/api.php?&lgdomain=<my domain>action=query&meta=tokens&type=login&format=json]
```
Should there not be an "&" also?

**Comment by erbap** [comment]
I forget to mention the most important:
mwoffliner --version
1.11.3

cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"

**Comment by kelson42** [comment]
@MananJethwani Do we have forgotten a question mark in the login URL?

**Comment by MananJethwani** [comment]
@kelson42 it's the `&` we have forgotten to place after `lgdomain`, `?` is always added in apiUrl.

**Comment by kelson42** [comment]
Yes a &, not a ?
