### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by erbap** [openzim/mwoffliner#1414]
I try to dump a local/public mediawiki 1.35 on a RHEL 8 server with mwoffliner 1.11.3 but get an error:

```mwoffliner --mwUrl=http://wiki.domain.tdl/ --adminEmail=<my email> --mwWikiPath=/ --mwApiPath=/api.php --mwModulePath=/load.php --mwRestApiPath=/rest.php/v1 --outputDirectory=/tmp/survey --verbose
[log] [2021-03-24T09:18:10.334Z] closing sanitize redis DB
[log] [2021-03-24T09:18:10.336Z] Starting mwoffliner v1.11.3...
[info] [2021-03-24T09:18:10.338Z] Using custom flavour: no
[log] [2021-03-24T09:18:10.340Z] Getting text direction...
[log] [2021-03-24T09:18:10.341Z] Getting site info...
[log] [2021-03-24T09:18:10.341Z] Getting sub-title...
[info] [2021-03-24T09:18:10.342Z] Downloading [http://wiki-surveyppp.app.jandenul.com/]
[info] [2021-03-24T09:18:10.342Z] Getting JSON from [http://wiki-surveyppp.app.jandenul.com/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2021-03-24T09:18:10.343Z] Downloading [http://wiki-surveyppp.app.jandenul.com/]
[log] [2021-03-24T09:18:10.997Z] Text direction is [ltr]
[info] [2021-03-24T09:18:11.573Z] Getting JSON from [http://wiki-surveyppp.app.jandenul.com/api.php?action=query&format=json&prop=redirects%7Crevisions%7Ccoordinates&rdlimit=max&rdnamespace=]
[info] [2021-03-24T09:18:11.729Z] Coordinates not available on this wiki
[log] [2021-03-24T09:18:11.729Z] Base Url:  http://localhost:6927/wiki-surveyppp.app.jandenul.com/v1/page/mobile-sections/
[log] [2021-03-24T09:18:11.729Z] Base Url for Main Page:  http://localhost:8000/wiki-surveyppp.app.jandenul.com/v3/page/pagebundle/
[log] [2021-03-24T09:18:11.730Z] Starting Parsoid & MCS
{
  "name": "mwoffliner",
  "hostname": "vm-mwsvdsppp01.jandenul.com",
  "pid": 37454,
  "level": 50,
  "levelPath": "error/metrics",
  "msg": "No such metrics client: 'undefined'",
  "time": "2021-03-24T09:18:11.759Z",
  "v": 0
}
{
  "name": "parsoid",
  "hostname": "vm-mwsvdsppp01.jandenul.com",
  "pid": 37454,
  "level": 30,
  "levelPath": "info",
  "msg": "loading ...",
  "time": "2021-03-24T09:18:12.500Z",
  "v": 0
}
{
  "name": "mwoffliner",
  "hostname": "vm-mwsvdsppp01.jandenul.com",
  "pid": 37454,
  "level": 60,
  "err": {
    "message": "",
    "name": "TypeError",
    "stack": "TypeError: Cannot read property 'replace' of undefined
    at normalizeName (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/service-runner/lib/statsd.js:22:20)
    at makeStatsD (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/service-runner/lib/statsd.js:70:57)
    at Function.getMetrics (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/service-runner/service-runner.js:60:53)
    at new ParsoidConfig (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/lib/config/ParsoidConfig.js:169:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/lib/api/ParsoidService.js:51:22)
    at Generator.next (<anonymous>)
    at tryCatchNext (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:783:28)
    at continuer (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:800:24)
    at callback (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:812:43)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:814:9
    at tryCatch2 (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:48:12)
    at PrFunPromise.Promise (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise.js:458:15)
    at new PrFunPromise (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:100:21)
    at Object.init (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/prfun/lib/index.js:797:21)
    at Object.apiServiceWorker (/usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/lib/index.js:55:24)
    at _requireModule.then (/usr/local/lib/node_modules/mwoffliner/node_modules/service-runner/lib/worker.js:195:47)
    at tryCatcher (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/mwoffliner/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)",
    "levelPath": "fatal/service-runner/worker"
  },
  "msg": "Cannot read property 'replace' of undefined",
  "time": "2021-03-24T09:18:12.544Z",
  "v": 0
}
```

**Comment by erbap** [comment]
--mwRestApiPath=/rest.php/v1/page solves this error

**Comment by CaptainBoggle** [comment]
I have the same error, however the fix did not work for me.

**Comment by c01dc0ffee** [comment]
I'm getting the same problem and output but the wiki I'm targeting doesn't seem to support REST API, only action API. I can set mwRestApiPath to "" but then mwoffliner fails with `Unable to find appropriate API end-point to retrieve article HTML`.
