### ISSUE TITLE
Cannot read property 'modules' of undefined

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1456]
Impossible to scrape a wikipedia_sv_all https://farm.openzim.org/pipeline/b8574557279057e525a50806/debug

**Comment by kelson42** [comment]
@MananJethwani This is clearly a regression

**Comment by kelson42** [comment]
@MananJethwani This is now by far the most impacting bug for Wikipedia scrapes... and because this seems to be a regression, it should be easy to fix. Could you please have a look?

**Comment by kelson42** [comment]
The problem happen when for some reason the HTTP request to get modules does not report any results.

See for example this json retrieval on an article which does not exist:
```
[info] [2021-08-29T10:53:11.432Z] Getting JSON from [https://de.wikipedia.org/w/api.php?action=parse&format=json&prop=modules%7Cjsconfigvars%7Cheadhtml&page=Vend%C3%B4me42]
[error] [2021-08-29T10:53:11.649Z] Error downloading article Vendôme
Failed to run mwoffliner after [6s]: {
	"stack": "TypeError: Cannot read property 'modules' of undefined\n    at /home/kelson/code/mwoffliner/src/util/saveArticles.ts:298:13\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/kelson/code/mwoffliner/src/util/saveArticles.ts:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)",
	"message": "Cannot read property 'modules' of undefined"
}


**********

Cannot read property 'modules' of undefined

**********
```

This can happen I guess for many reasons and I see at least one legitimate one and this is for example when an article is deleted beetween the moment when we retrieve the list of article and the moment where we really scrape the article. This is exacly what happened here https://farm.openzim.org/pipeline/b50bcbe7370494d52074a216/debug where the article "The_Paleo_Paranoids" has been deleted in the middle of the scraping process, see https://de.wikipedia.org/w/index.php?title=The_Paleo_Paranoids&action=edit&redlink=1
