### ISSUE TITLE
Newly unable to scrape fi.wikipedia.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1481]
https://farm.openzim.org/pipeline/c7a1c35a05e5e6422aaa1c06/debug

```
[error] [2021-06-10T07:01:07.110Z] Error downloading article Säteily­paine
Failed to run mwoffliner after [3585s]: {
	"message": "Maximum number of redirects exceeded",
	"name": "Error [ERR_FR_TOO_MANY_REDIRECTS]",
	"stack": "Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded\n    at RedirectableRequest._processResponse (/tmp/mwoffliner/node_modules/follow-redirects/index.js:317:26)\n    at ClientRequest.RedirectableRequest._onNativeResponse (/tmp/mwoffliner/node_modules/follow-redirects/index.js:56:10)\n    at Object.onceWrapper (events.js:422:26)\n    at ClientRequest.emit (events.js:315:20)\n    at ClientRequest.EventEmitter.emit (domain.js:486:12)\n    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)\n    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)\n    at HTTPParser.execute (<anonymous>)\n    at TLSSocket.socketOnData (_http_client.js:509:22)\n    at TLSSocket.emit (events.js:315:20)\n    at TLSSocket.EventEmitter.emit (domain.js:486:12)\n    at addChunk (_stream_readable.js:309:12)\n    at readableAddChunk (_stream_readable.js:284:9)\n    at TLSSocket.Readable.push (_stream_readable.js:223:10)\n    at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23)",
	"config": {
		"url": "https://fi.wikipedia.org/api/rest_v1/page/mobile-sections/S%C3%A4teily%C2%ADpaine",
		"method": "get",
		"headers": {
			"Accept": "application/json",
			"cache-control": "public, max-stale=86400",
			"accept-encoding": "gzip, deflate",
			"user-agent": "MWOffliner/HEAD (contact@kiwix.org)",
			"cookie": ""
		},
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 60000,
		"responseType": "json",
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	},
	"code": "ERR_FR_TOO_MANY_REDIRECTS"
}


**********

Maximum number of redirects exceeded

**********
```

**Comment by kelson42** [comment]
The problem seems to be upstream:
```
$ curl -sI "https://fi.wikipedia.org/wiki/S%C3%A4teily%C2%ADpaine" | grep HTTP
HTTP/2 200 
$ curl -sI "https://fi.wikipedia.org/api/rest_v1/page/mobile-sections/S%C3%A4teily%C2%ADpaine" | grep -i location
location: S%C3%A4teilypaine
$ curl -sI "https://fi.wikipedia.org/api/rest_v1/page/mobile-sections/S%C3%A4teilypaine" | grep -i location
location: S%C3%A4teily%C2%ADpaine
```

**Comment by kelson42** [comment]
Upstream ticket https://phabricator.wikimedia.org/T284734

**Comment by kelson42** [comment]
For an unknown reason, the problem does not occur any more.

**Comment by arlolra** [comment]
The fix is probably in,
https://github.com/wikimedia/mediawiki-title/pull/51
