### ISSUE TITLE
Newly unable to scrape br.wikisource.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1482]
https://farm.openzim.org/pipeline/de888efaee938ff06b0f1c06

```
[error] [2021-06-10T11:15:31.395Z] Error downloading article Pajenn:Troude_ha_Milin_-_Imitation_Jezuz-Krist,_1862.djvu/386
Failed to run mwoffliner after [777s]: {
	"message": "Request failed with status code 500",
	"name": "Error",
	"stack": "Error: Request failed with status code 500\n    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:17:12)\n    at Unzip.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:260:11)\n    at Unzip.emit (events.js:315:20)\n    at Unzip.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
	"config": {
		"url": "https://br.wikisource.org/api/rest_v1/page/html/Pajenn%3ATroude_ha_Milin_-_Imitation_Jezuz-Krist%2C_1862.djvu%2F386",
		"method": "get",
		"headers": {
			"Accept": "application/json",
			"cache-control": "public, max-stale=86400",
			"accept-encoding": "gzip, deflate",
			"user-agent": "MWOffliner/HEAD (contact@kiwix.org)",
			"cookie": ""
		},
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 60000,
		"responseType": "json",
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	}
}


**********

Request failed with status code 500

**********

```

**Comment by kelson42** [comment]
Upstream bug at https://phabricator.wikimedia.org/T284738

**Comment by kelson42** [comment]
Bug has been fixed upstream

**Comment by kelson42** [comment]
Tracked now at https://phabricator.wikimedia.org/T284693
