### ISSUE TITLE
Mwoffliner fails when article selection includes special characters.

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#1486]
Steps to reproduce: ran recipe [wikipedia_en_for_schools](https://farm.openzim.org/recipes/wikipedia_en_for_schools) using http://tmp.kiwix.org/w4school/W4schools.csv on the zimfarm

The recipe had run in the past without any issue but on a much smaller range of articles (20 vs. 2000). I only changed the csv file, nothing else in the parameters.

Ran the recipe three times, and it failed three times on different entries with `status code 400` - all of them however have in common that they include special characters, usually not stored in the .csv as special characters but as their code equivalent, e.g. Américo -> Am%25C3%25A9rico

See:
https://s3.us-west-1.wasabisys.com/org-kiwix-zimfarm-logs/627159702dac6ccadcbc1d06_mwoffliner.log failed on Eberhard_Jäckel 
In this first case the error log gave something wholy incorrect (Eberhard_J%25C3%25A4ckel), so I regenerated the csv and ran these two:
https://s3.us-west-1.wasabisys.com/org-kiwix-zimfarm-logs/80c159ba716f92fabacd1d06_mwoffliner.log failed on Tírechán
https://s3.us-west-1.wasabisys.com/org-kiwix-zimfarm-logs/6bb159702dac6cca71fd1d06_mwoffliner.log failed on Américo Castro

```
[log] [2021-06-22T13:01:32.143Z] Getting articles
[error] [2021-06-22T13:01:32.447Z] Error downloading article Am%C3%A9rico_Castro
Failed to run mwoffliner after [11s]: {
	"message": "Request failed with status code 400",
	"name": "Error",
	"stack": "Error: Request failed with status code 400\n    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
	"config": {
		"url": "https://en.wikipedia.org/api/rest_v1/page/mobile-sections/Am%25C3%25A9rico_Castro",
		"method": "get",
		"headers": {
			"Accept": "application/json",
			"cache-control": "public, max-stale=86400",
			"accept-encoding": "gzip, deflate",
			"user-agent": "MWOffliner/HEAD (contact@kiwix.org)",
			"cookie": ""
		},
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 60000,
		"responseType": "json",
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
```

**Comment by kelson42** [comment]
Quite sur this is an encodign problem in your article list.

**Comment by kelson42** [comment]
* no url encoding
* no local anchors (#)
* in utf8


If this is respected, it will work.
