### ISSUE TITLE
mwoffliner (docker) errors out when trying to archive a mediawiki instance

### ISSUE THREAD

**Issue by daduke** [openzim/mwoffliner#1580]
Hi,

I found this very interesting project as we need to archive two MW instances. I tried running it on on Ubuntu, Debian and Fedora, but it fails on all three with 2 different errors:

Ubuntu 20.04 LTS + Fedora 35:
```
[log] [2022-01-07T12:22:56.400Z] Starting Parsoid & MCS
{"name":"mwoffliner","hostname":"fedora","pid":31113,"level":50,"levelPath":"error/metrics","msg":"No such metrics client: 'undefined'","time":"2022-01-07T12:22:56.505Z","v":0}
{"name":"mwoffliner","hostname":"fedora","pid":31113,"level":60,"err":{"message":"","name":"Error","stack":"Error: Cannot find module 'is-arguments'\nRequire stack:\n- /usr/local/lib/node_modules/mwoffliner/node_modules/parsoid/node_modules/babybird/lib/promise-extra.js [..]
```

Debian bullseye:
```
[log] [2022-01-07T12:24:51.629Z] Starting Parsoid & MCS
{"name":"mwoffliner","hostname":"bullseye","pid":8228,"level":50,"levelPath":"error/metrics","msg":"No such metrics client: 'undefined'","time":"2022-01-07T12:24:51.666Z","v":0}
{"name":"parsoid","hostname":"bullseye","pid":8228,"level":30,"levelPath":"info","msg":"loading ...","time":"2022-01-07T12:24:52.470Z","v":0}
{"name":"mwoffliner","hostname":"bullseye","pid":8228,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'replace') [..]
```

I tried npm installing is-arguments, but the problem remains. I'm not sufficiently proficient in the node universe to debug this further.. any ideas?

thanks,
-Christian

**Comment by kelson42** [comment]
@daduke This is indeed an installation problem. Maybe you could give a try to the Docker image? https://hub.docker.com/r/openzim/mwoffliner

**Comment by daduke** [comment]
thanks for the fast response. I followed the instructions in docker/Readme, and `docker run -ti openzim/mwoffliner mwoffliner --help` works, but no matter what redis settings I try (or not, since it's supposed to work automagically), I always get
```
Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
```
event though redis is being started in the background..

**Comment by kelson42** [comment]
@daduke I will have a look but we use it on daily base... strange

**Comment by daduke** [comment]
lo and behold!! the 9345th attempt is now doing something! Let me see how far I get before you waste your time. Thanks!

it runs for ~1 min then stops with `cannot read property 'modules' of undefined`
one step further

**Comment by daduke** [comment]
each run errors out with the above error message at a different article. Sometimes it runs for 2 mins, sometimes for 10s.. 
```
[error] [2022-01-07T13:41:33.953Z] Error downloading article Quantis
Failed to run mwoffliner after [6s]: {
        "stack": "TypeError: Cannot read property 'modules' of undefined\n    at /tmp/mwoffliner/lib/util/saveArticles.js:294:26\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/util/saveArticles.js:24:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "message": "Cannot read property 'modules' of undefined"
```

**Comment by kelson42** [comment]
@daduke OK, this is a totally different problem then. Difficult to say what happen here, you can try to slow down the scraping with `--speed=0.1` and use `--verbose`, maybe you will get more information.

**Comment by daduke** [comment]
I do, but I can't really make sense of it:
```
{"name":"mwoffliner","hostname":"eb6c842236d7","pid":13,"level":40,"logType":"warn/api/main","wiki":"wiki$0","title":"Test/VisGraph","oldId":"7577","reqId":null,"userAgent":"service-mobileapp-node","msg":"Template Fetch Unrecognized parameter: 'rvslots'","longMsg":"Template Fetch\nUnrecognized parameter: 'rvslots'","levelPath":"warn/api/main","time":"2022-01-07T14:10:07.309Z","v":0}
{"name":"mwoffliner","hostname":"eb6c842236d7","pid":13,"level":50,"logType":"error","wiki":"wiki$0","title":"Test/VisGraph","oldId":7577,"reqId":null,"userAgent":"service-mobileapp-node","msg":"Failed to parse the JSON response for Extension Parse","stack":"ParserError: Failed to parse the JSON response for Extension Parse\n    at PHPParseRequest.ApiRequest._handleBody (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:479:12)\n    at PHPParseRequest.ApiRequest._requestCB (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:420:8)\n    at Request._callback (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:332:35)\n    at Request.self.callback (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:486:12)\n    at Request.<anonymous> (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:1157:10)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:486:12)\n    at IncomingMessage.<anonymous> (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","httpStatus":500,"longMsg":"Failed to parse the JSON response for Extension Parse","levelPath":"error","time":"2022-01-07T14:10:07.351Z","v":0}
{"name":"mwoffliner","hostname":"eb6c842236d7","pid":13,"level":50,"logType":"error/extension","wiki":"wiki$0","title":"Test/VisGraph","oldId":7577,"reqId":null,"userAgent":"service-mobileapp-node","msg":"Error Failed to parse the JSON response for Extension Parse  parsing extension token:  {\"type\":\"SelfclosingTagTk\",\"name\":\"extension\",\"attribs\":[{\"k\":\"typeof\",\"v\":\"mw:Extension\"},{\"k\":\"name\",\"v\":\"vistrail\"},{\"k\":\"about\",\"v\":\"#mwt1\"},{\"k\":\"source\",\"v\":\"<vistrail host=\\\"alps.ethz.ch\\\" db=\\\"tutorials\\\" port=\\\"3306\\\" vtid=\\\"15\\\" version=\\\"9\\\" buildalways=\\\"True\\\" showworkflow=\\\"True\\\" />\"},{\"k\":\"options\",\"v\":[{\"k\":\"host\",\"v\":\"alps.ethz.ch\",\"srcOffsets\":[26,30,32,44],\"vsrc\":\"alps.ethz.ch\"},{\"k\":\"db\",\"v\":\"tutorials\",\"srcOffsets\":[46,48,50,59],\"vsrc\":\"tutorials\"},{\"k\":\"port\",\"v\":\"3306\",\"srcOffsets\":[61,65,67,71],\"vsrc\":\"3306\"},{\"k\":\"vtid\",\"v\":\"15\",\"srcOffsets\":[73,77,79,81],\"vsrc\":\"15\"},{\"k\":\"version\",\"v\":\"9\",\"srcOffsets\":[83,90,92,93],\"vsrc\":\"9\"},{\"k\":\"buildalways\",\"v\":\"True\",\"srcOffsets\":[95,106,108,112],\"vsrc\":\"True\"},{\"k\":\"showworkflow\",\"v\":\"True\",\"srcOffsets\":[114,126,128,132],\"vsrc\":\"True\"}]}],\"dataAttribs\":{\"tsr\":[16,136],\"stx\":\"html\",\"selfClose\":true,\"src\":\"<vistrail host=\\\"alps.ethz.ch\\\" db=\\\"tutorials\\\" port=\\\"3306\\\" vtid=\\\"15\\\" version=\\\"9\\\" buildalways=\\\"True\\\" showworkflow=\\\"True\\\" />\",\"extTagOffsets\":[16,136,120,0]}}","stack":"ParserError: Failed to parse the JSON response for Extension Parse\n    at PHPParseRequest.ApiRequest._handleBody (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:479:12)\n    at PHPParseRequest.ApiRequest._requestCB (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:420:8)\n    at Request._callback (/tmp/mwoffliner/node_modules/parsoid/lib/mw/ApiRequest.js:332:35)\n    at Request.self.callback (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:486:12)\n    at Request.<anonymous> (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:1157:10)\n    at Request.emit (events.js:315:20)\n    at Request.EventEmitter.emit (domain.js:486:12)\n    at IncomingMessage.<anonymous> (/tmp/mwoffliner/node_modules/parsoid/node_modules/request/request.js:1079:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","httpStatus":500,"longMsg":"Error\nFailed to parse the JSON response for Extension Parse\n parsing extension token: \n{\"type\":\"SelfclosingTagTk\",\"name\":\"extension\",\"attribs\":[{\"k\":\"typeof\",\"v\":\"mw:Extension\"},{\"k\":\"name\",\"v\":\"vistrail\"},{\"k\":\"about\",\"v\":\"#mwt1\"},{\"k\":\"source\",\"v\":\"<vistrail host=\\\"alps.ethz.ch\\\" db=\\\"tutorials\\\" port=\\\"3306\\\" vtid=\\\"15\\\" version=\\\"9\\\" buildalways=\\\"True\\\" showworkflow=\\\"True\\\" />\"},{\"k\":\"options\",\"v\":[{\"k\":\"host\",\"v\":\"alps.ethz.ch\",\"srcOffsets\":[26,30,32,44],\"vsrc\":\"alps.ethz.ch\"},{\"k\":\"db\",\"v\":\"tutorials\",\"srcOffsets\":[46,48,50,59],\"vsrc\":\"tutorials\"},{\"k\":\"port\",\"v\":\"3306\",\"srcOffsets\":[61,65,67,71],\"vsrc\":\"3306\"},{\"k\":\"vtid\",\"v\":\"15\",\"srcOffsets\":[73,77,79,81],\"vsrc\":\"15\"},{\"k\":\"version\",\"v\":\"9\",\"srcOffsets\":[83,90,92,93],\"vsrc\":\"9\"},{\"k\":\"buildalways\",\"v\":\"True\",\"srcOffsets\":[95,106,108,112],\"vsrc\":\"True\"},{\"k\":\"showworkflow\",\"v\":\"True\",\"srcOffsets\":[114,126,128,132],\"vsrc\":\"True\"}]}],\"dataAttribs\":{\"tsr\":[16,136],\"stx\":\"html\",\"selfClose\":true,\"src\":\"<vistrail host=\\\"alps.ethz.ch\\\" db=\\\"tutorials\\\" port=\\\"3306\\\" vtid=\\\"15\\\" version=\\\"9\\\" buildalways=\\\"True\\\" showworkflow=\\\"True\\\" />\",\"extTagOffsets\":[16,136,120,0]}}","levelPath":"error/extension","time":"2022-01-07T14:10:07.354Z","v":0}
```

the command line I used was:
```
docker run -ti openzim/mwoffliner mwoffliner --mwUrl="http://alps.comp-phys.org/mediawiki/" --mwWikiPath="/" --mwApiPath="api.php"  --mwModulePath="load.php" --speed=0.1 --verbose
```
alps is a wiki that we run for one of our research groups and would like to retire..
thanks for all the help!

**Comment by daduke** [comment]
the error might actually come from mediawiki itself, closing for now. Thanks for the support.
