### ISSUE TITLE
Unable to find appropriate API end-point to retrieve article HTML

### ISSUE THREAD

**Issue by go2tom42** [openzim/mwoffliner#1584]
I have mediawiki latest version (also tried 1.35.5) spun up via [docker](https://github.com/go2tom42/mediawiki/blob/main/Dockerfile), It's accessible from the web.  The site functions correctly

When I try run (bare metal homelab running Ubuntu Server 20.04.3 LTS)
`docker run -ti -v /home/tom42/here:/output:rw ghcr.io/openzim/mwoffliner:latest mwoffliner --mwUrl="http://mwiki.example.pw" --mwWikiPath="/" --mwApiPath="api.php" --mwRestApiPath="rest.php/v1/page" --adminEmail=tom42@gmail.com --verbose --outputDirectory="/output"`

or

`docker run -ti -v /home/tom42/here:/output:rw ghcr.io/openzim/mwoffliner:latest mwoffliner --mwUrl="http://mwiki.example.pw" --mwWikiPath="/" --mwApiPath="api.php" --adminEmail=tom42martin@gmail.com --verbose --outputDirectory="/output"`

adding this makes no difference
`--mwModulePath="load.php"`

The results is this

```
tom42@workhorse2:~$ docker run -ti -v /home/tom42/here:/output:rw ghcr.io/openzim/mwoffliner:latest mwoffliner --mwUrl="http://mwiki.example.pw" --mwWikiPath="/" --mwApiPath="api.php" --mwRestApiPath="rest.php/v1/page" --adminEmail=tom42martin@gmail.com --verbose --outputDirectory="/output"
Unable to find image 'ghcr.io/openzim/mwoffliner:latest' locally
latest: Pulling from openzim/mwoffliner
Digest: sha256:c497f581003026d7904ebbf2bd55e836bcfbd29e218c03f9a3ed6df8765b7844
Status: Downloaded newer image for ghcr.io/openzim/mwoffliner:latest
starting redis-server in the background…
[log] [2022-01-16T07:09:04.182Z] closing sanitize redis DB
[log] [2022-01-16T07:09:04.184Z] Starting mwoffliner v1.11.10...
[info] [2022-01-16T07:09:04.188Z] Using custom flavour: no
[log] [2022-01-16T07:09:04.190Z] Getting text direction...
[log] [2022-01-16T07:09:04.191Z] Getting site info...
[log] [2022-01-16T07:09:04.191Z] Getting sub-title...
[info] [2022-01-16T07:09:04.191Z] Downloading [http://mwiki.example.pw/]
[info] [2022-01-16T07:09:04.192Z] Getting JSON from [http://mwiki.example.pw/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2022-01-16T07:09:04.192Z] Downloading [http://mwiki.example.pw/]
[log] [2022-01-16T07:09:04.395Z] Text direction is [ltr]
[info] [2022-01-16T07:09:04.773Z] Getting JSON from [http://mwiki.example.pw/api.php?action=query&format=json&prop=redirects%7Crevisions%7Ccoordinates&rdlimit=max&rdnamespace=]
[log] [2022-01-16T07:09:04.819Z] Base Url:  undefined
[log] [2022-01-16T07:09:04.820Z] Base Url for Main Page:  undefined
Failed to run mwoffliner after [1s]: {
        "stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.<anonymous> (/tmp/mwoffliner/lib/Downloader.js:240:23)\n    at Generator.next (<anonymous>)\n    at /tmp/mwoffliner/lib/Downloader.js:27:71\n    at new Promise (<anonymous>)\n    at __awaiter (/tmp/mwoffliner/lib/Downloader.js:23:12)\n    at Downloader.setBaseUrls (/tmp/mwoffliner/lib/Downloader.js:227:16)\n    at Object.<anonymous> (/tmp/mwoffliner/lib/mwoffliner.lib.js:165:26)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/mwoffliner.lib.js:26:58)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "message": "Unable to find appropriate API end-point to retrieve article HTML"
}


**********

Unable to find appropriate API end-point to retrieve article HTML

**********
```

Could it have something to do with that fact mediawiki removed mwoffliner's default REST API location with version [1.35.5, and is "Available for Wikimedia projects only"](https://www.mediawiki.org/wiki/API:REST_API) now

Old way (still current with Wikimedia projects)  
https://en.wikipedia.org/api/rest_v1/page/html/Earth

New way  
https://en.wikipedia.org/w/rest.php/v1/page/Earth/html

---EDIT
Tried with the "official" [openzim Mediawiki docker file](https://hub.docker.com/r/openzim/mediawiki), same result

**Comment by go2tom42** [comment]
If anyone else has this issue adding the following to the command line
`--optimisationCacheUrl=""`
