### ISSUE TITLE
install doesn't work

### ISSUE THREAD

**Issue by gerolfscherr** [openzim/mwoffliner#1592]
npm -i -g mwoffliner yields:

npm ERR! An unknown git error occurred
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/wikimedia/mobileapps.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

when I try to run 
 git --no-replace-objects ls-remote https://git@github.com/wikimedia/mobileapps.git
(with https:// instead of ssh:// ) the command works, but I don't know in in which file I could change the url scheme (grep didn't yield any promising results)

- I don't know why it should be neccessary to have my github key installed on the machine where I try to run mwoffliner, but I even tried to add a github ssh key, so the command "git --no-replace-objects ls-remote ssh://git@github.com/wikimedia/mobileapps.git" works, but the install still doesn't.

**Comment by kelson42** [comment]
I can not really help here unfortunately. I can not reproduce the problen, for me I get the same error but for an other package of Wikimedia.

This dependences are not maintained anymore since years and we will have to remove them from the dependence tree.

What works for me is cloning the repo of mwoffliner, installing packages locally and running `./node_modules/.bin/ts-node ./src/cli.ts`

**Comment by gerolfscherr** [comment]
I 'solved' it by using the docker version, now I am stuck at:

sudo docker run openzim/mwoffliner mwoffliner --mwUrl=REDACTED  --mwApiPath=/api.php --mwWikiPath=/ --mwModulePath=/load.php   --adminEmail=REDACTED

[...]
[log] [2022-02-13T05:02:05.404Z] Deleting temporary directory [/tmp/mwoffliner-1644724863368]
Failed to run mwoffliner after [3663s]: {
	"stack": "Error: unable to hack startup module\n    at hackStartUpModule (/tmp/mwoffliner/lib/util/dump.js:124:23)\n    at Object.<anonymous> (/tmp/mwoffliner/lib/util/dump.js:141:20)\n    at Generator.next (<anonymous>)\n    at fulfilled (/tmp/mwoffliner/lib/util/dump.js:24:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
	"message": "unable to hack startup module"
}


**********

unable to hack startup module

**********

**Comment by kelson42** [comment]
Seems then be https://github.com/openzim/mwoffliner/issues/1409. What is you Mediawiki version?

**Comment by gerolfscherr** [comment]
Version is 1.28 - I know this is outdated. The project we used this wiki for is finished and I wanted to archive the contents in a static format for future reference.

**Comment by Jaifroid** [comment]
@gerolfscherr That is the same error that we encountered in https://github.com/openzim/mwoffliner/issues/1590#issuecomment-1038022813 and below. Solve by generating keypair and putting public key on GitHub. But we're getting other permissions errors.

**Comment by kelson42** [comment]
MWoffliner does not rely anymore on ssh://[git@github.com](mailto:git@github.com)/wikimedia/mobileapps.git. Pretty sure this bug has been fixed a while ago already.
