### ISSUE TITLE
Wikibooks "Request failed with status code 504"

### ISSUE THREAD

**Issue by orange-tin** [openzim/mwoffliner#1617]
Looks like I'm not the only one having this issue.
The downloads have been failing at your farm too for over 6 months: https://farm.openzim.org/recipes/wikibooks_en

I need the latest version of Wikibooks and since Kiwix didn't have it, I ran mwoffliner (docker) on my own.

All was going well, articles were downloading, a few errors (articles were deleted between the time of getting the article chunk and downloading) but it was proceeding just fine. Until...

```
[log] [2022-06-04T22:10:09.817Z] Progress downloading articles [15980/94268] [17.0%]
T:4126; A:16000; RA:1; CA:15998; UA:1; FA:0; IA:15979; C:189; CC:189; UC:0; WC:0
[log] [2022-06-04T22:10:34.180Z] Progress downloading articles [16080/94268] [17.1%]
[error] [2022-06-04T22:19:46.993Z] Error downloading article Mirad_Grammar/print_version_of_dictionary
[log] [2022-06-04T22:19:47.001Z] Exiting with code [2]
[log] [2022-06-04T22:19:47.001Z] Deleting temporary directory [/tmp/mwoffliner-1654376419071]
Failed to run mwoffliner after [4769s]: {
	"message": "Request failed with status code 504",
	"name": "Error",
	"stack": "Error: Request failed with status code 504\n    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
	"config": {
		"url": "https://en.wikibooks.org/api/rest_v1/page/html/Mirad_Grammar%2Fprint_version_of_dictionary",
		"method": "get",
		"headers": {
			"Accept": "application/json",
			"cache-control": "public, max-stale=86400",
			"accept-encoding": "gzip, deflate",
			"user-agent": "MWOffliner/HEAD (admin@quantmail.net)",
			"cookie": ""
		},
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 120000,
		"responseType": "json",
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	}
}


**********

Request failed with status code 504

**********
```

My download did go further than https://farm.openzim.org/pipeline/5bd502a53aedc86d5719d726/debug , although the openzim pipeline log does not show that it hit an error while downloading an article...

I can confirm that the file in the error log: https://en.wikibooks.org/api/rest_v1/page/html/Mirad_Grammar%2Fprint_version_of_dictionary either does not exist or is not loading:
```
curl --connect-timeout 120 -I https://en.wikibooks.org/api/rest_v1/page/html/Mirad_Grammar%2Fprint_version_of_dictionary
HTTP/2 504 
content-length: 24
...
```

I have gone through a few older issues in this repo but none had a fix and https://farm.openzim.org/recipes/wikibooks_en hasn't successfully completed a run either.

**Comment by orange-tin** [comment]
Ok, so turns out https://en.wikibooks.org/wiki/Mirad_Grammar/print_version_of_dictionary is a dictionary and the page is VERY long.

This seems to be related to https://phabricator.wikimedia.org/T275505

**Comment by orange-tin** [comment]
Ran it again, got the same error but a different url: `https://en.wikibooks.org/api/rest_v1/page/html/CLEP_College_Algebra%2FPrintable_version`

```
[log] [2022-06-04T23:53:01.424Z] Progress downloading articles [12300/94230] [13.1%]
[error] [2022-06-05T00:01:58.192Z] Error downloading article CLEP_College_Algebra/Printable_version
Failed to run mwoffliner after [3771s]: {
	"message": "Request failed with status code 504",
	"name": "Error",
	"stack": "Error: Request failed with status code 504\n    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:486:12)\n    at endReadableNT (_stream_readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)",
	"config": {
		"url": "https://en.wikibooks.org/api/rest_v1/page/html/CLEP_College_Algebra%2FPrintable_version",
		"method": "get",
		"headers": {
			"Accept": "application/json",
			"cache-control": "public, max-stale=86400",
			"accept-encoding": "gzip, deflate",
			"user-agent": "MWOffliner/HEAD (EMAIL REDACTED)",
			"cookie": ""
		},
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 120000,
		"responseType": "json",
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1
	}
}


**********

Request failed with status code 504

**********
```

**Comment by orange-tin** [comment]
Once again, [this](https://en.wikibooks.org/wiki/CLEP_College_Algebra/Printable_version) is a pretty big page (about 5 MB HTML page). Seems like it is a problem with the page being too big.

**Comment by orange-tin** [comment]
Another update.
After increasing the requestTimeout from 120 to 600, it proceeded smoothly and gave me a different error:

```
[log] [2022-06-05T01:43:33.180Z] Progress downloading articles [20030/94230] [21.3%]
[log] [2022-06-05T01:43:53.894Z] Progress downloading articles [20120/94230] [21.4%]
[log] [2022-06-05T01:44:28.773Z] Progress downloading articles [20220/94230] [21.5%]
[log] [2022-06-05T01:44:50.623Z] Progress downloading articles [20310/94230] [21.6%]
/usr/local/sbin/mwoffliner: line 2:    12 Killed                  /usr/local/bin/mwoffliner --redis=$REDIS "$@"
```

Any idea what this error is?

**Comment by kelson42** [comment]
@orange-tin Thx for your report and you made a large part of the investigation. I will try to increase the `requestTimeout` like you in the Zimfarm and see if it works better.

**Comment by benoit74** [comment]
Looks like these pages are too big and failing forever ... we could better handle these failing pages with https://github.com/openzim/mwoffliner/issues/1942

**Comment by kelson42** [comment]
@benoit74 IMHO we can close this issue because you have implemented a solution to workaround and be more flexible around this kind of server-side errors?

**Comment by benoit74** [comment]
We still have a problem of "Too many articles failed to download, aborting" ... but this will be tracked / followed / solved globally at https://github.com/openzim/mwoffliner/issues/2336, no need for individual issue on each book for now.
