### ISSUE TITLE
"Webp compression working for cmyk color-space images" test not passing locally

### ISSUE THREAD

**Issue by JameelKaisar** [openzim/mwoffliner#1684]
### Command
```
npm run tape -- test/unit/downloader.test.ts
```

### Result
```
1..34
# tests 34
# pass  33
# fail  1
```

### Logs
```
not ok 8 Webp compression working for cmyk color-space images
  ---
    operator: equal
    expected: 'image/webp'
    actual:   'image/jpeg'
    at: <anonymous> (/workspaces/mwoffliner/test/unit/downloader.test.ts:62:8)
    stack: |-
      Error: Webp compression working for cmyk color-space images
          at Test.assert [as _assert] (/workspaces/mwoffliner/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/workspaces/mwoffliner/node_modules/tape/lib/test.js:80:32)
          at Test.equal (/workspaces/mwoffliner/node_modules/tape/lib/test.js:389:10)
          at Test.bound (/workspaces/mwoffliner/node_modules/tape/lib/test.js:80:32)
          at /workspaces/mwoffliner/test/unit/downloader.test.ts:62:8
          at Generator.next (<anonymous>)
          at fulfilled (/workspaces/mwoffliner/test/unit/downloader.test.ts:5:58)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
  ...
```

**Comment by JameelKaisar** [comment]
The tests were not passing due to the following error:
`Error: JPEG support not compiled. Please install the libjpeg development package before building.`

I was able to resolve this by installing `libglu1` and recompiling node packages.

```
sudo apt install libglu1
rm -rf node_modules/
npm ci
npm run tape -- test/unit/downloader.test.ts
```
