### ISSUE TITLE
Error? by running tests

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1732]
Running the test gives a strange error... but the overall test is OK.
```
 RUNS  test/e2e/en10.e2e.test.ts
T:19; A:564; RA:484; CA:70; UA:10; FA:0; IA:10; C:2; CC:2; UC:0; WC:0
T:20; Waiting for workers
T:20; ResolveRedirectIndexes
Resolve redirect
T:20; Set article indexes
set index
T:20; Resolve mimetype
T:20; create title index
T:20; 566 title index created
T:20; 4 clusters created
T:20; write zimfile :
T:20;  write mimetype list
T:20;  write directory entries
T:20;  write url prt list
T:20;  write title index
T:20;  write cluster offset list
T:20;  write header
T:20;  write checksum
 FAIL  test/e2e/en10.e2e.test.ts (134.365 s)
  en10
    ✕ Simple articleList (120586 ms)

  ● en10 › Simple articleList

    thrown: "Exceeded timeout of 120000 ms for a test.
    Use jest.setTimeout(newTimeout) to increase the timeout value, if this is a long-running test."

      25 |   };
      26 |
    > 27 |   test('Simple articleList', async () => {
         |   ^
      28 |     await execa(`redis-cli flushall`, { shell: true });
      29 |
      30 |     const outFiles = await mwoffliner.execute(parameters);

      at test/e2e/en10.e2e.test.ts:27:3
      at test/e2e/en10.e2e.test.ts:10:1
```

What is going on?

**Comment by uriesk** [comment]
e2e tests aren't finishing in the 120s.
You can set the timeout higher for a specific test like this
https://github.com/uriesk/mwoffliner/blob/nodeupdate/test/e2e/en10.e2e.test.ts#L86

**Comment by kelson42** [comment]
@uriesk Thank you for the explanation, but then I wonder why the overall test ends with exit code `0` and not `1`!
