### ISSUE TITLE
CI newly fails on my local system

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1741]
I have no `$S3_URL` configured, so not S3 cache problem, but since today I get the following error by running `npm test`

```
 PASS  test/unit/redis.test.ts
  Redis
    ✓ Redis Tests (19 ms)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.



ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/util.test.ts.


 FAIL  test/unit/util.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)

 FAIL  test/unit/urlRewriting.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)


ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From test/unit/styles.test.ts.


 FAIL  test/unit/styles.test.ts
  ● Test suite failed to run

    ReferenceError: Export '__signal_exit_emitter__' is not defined in module

      at node_modules/jest-runtime/build/index.js:1494:16
          at Array.forEach (<anonymous>)
```

So 3 tests don't run anymore and this has nothing to do with S3.

**Comment by kelson42** [comment]
@uriesk @pavel-karatsiuba Do you have the same behaviour?

**Comment by uriesk** [comment]
I do. Sometimes.
But i didn't pay much attention to it, because it looks like pavel is addressing such issues in #1737
https://github.com/openzim/mwoffliner/pull/1737/commits

**Comment by pavel-karatsiuba** [comment]
@kelson42 I am doing a lot of tests per day and saw such errors. This can be because you changed the branch but did not run `npm i`. In some cases, You need also to remove the node_modules folder and then run `npm i`.
