### ISSUE TITLE
Handling elevated Docker privileges across workers

### ISSUE THREAD

**Issue by kevinmcmurtrie** [openzim/mwoffliner#1764]
Docker can grant elevated privileges with options '--cap-add' or '--privileged', but a zimfarm worker may prohibit these for security reasons.  Scraper tasks crash when their request is denied.

Right now there is only informal knowledge about which scrapers do or don't need elevated privileges.  For example, `pixelmemory` refuses it and `zimit` is known to need it, so `pixelmemory` is configured to not request `zimit` tasks.  This isn't always the case so there are occasional failures.  A test run may attempt to launch a monitoring container with elevated privileges.

A better method of handling this is requested.

Sample:
https://farm.openzim.org/pipeline/2a8fe41cd2968ef0b645ad36/debug
ghcr.io/openzim/sotoki:2.0.2 (sotoki)
Resources	 3 5 GB 20 GB [monitored]
```
[2023-02-01 12:02:25,707: INFO] starting zimfarm task-worker for 2a8fe41cd2968ef0b645ad36.
[2023-02-01 12:02:25,707: INFO] configuration:
	username=pixelmemory
	webapi_uris=['https://api.farm.openzim.org/v1']
	workdir=/data
	task_id=2a8fe41cd2968ef0b645ad36
[2023-02-01 12:02:25,707: INFO] testing workdir at /data…
[2023-02-01 12:02:25,707: INFO] 	workdir is available and writable
[2023-02-01 12:02:25,707: INFO] testing private key at /etc/ssh/keys/zimfarm…
[2023-02-01 12:02:25,797: INFO] 	private key is available and readable (...)
[2023-02-01 12:02:25,798: INFO] testing authentication with https://api.farm.openzim.org/v1…
[2023-02-01 12:02:26,827: INFO] 	authentication successful
[2023-02-01 12:02:26,828: INFO] testing docker API on /var/run/docker.sock…
[2023-02-01 12:02:26,853: INFO] 	docker API access successful
[2023-02-01 12:02:26,862: INFO] Host hardware resources:
	CPU : 18 (total) ;  15 (avail)
	RAM : 64 GiB (total) ;  57 GiB (avail)
	Disk: 3 TiB (configured) ; 11.92 TiB (avail) ; 50 GiB (reserved) ; 2.95 TiB (remain)
[2023-02-01 12:02:26,862: INFO] registering exit signals
[2023-02-01 12:02:26,862: INFO] Fetching task details for 2a8fe41cd2968ef0b645ad36
[2023-02-01 12:02:27,378: INFO] Updating task-status=started
[2023-02-01 12:02:27,954: INFO] Setting-up workdir
[2023-02-01 12:02:27,958: INFO] Starting DNS cache
[2023-02-01 12:02:29,240: DEBUG] DNS Cache started using IPs: ['172.17.0.7']
[2023-02-01 12:02:29,240: INFO] Starting scraper. Expects files at: /Yosemite/zimfarm/data/2a8fe41cd2968ef0b645ad36 
[2023-02-01 12:02:29,242: DEBUG] Pulling image ghcr.io/openzim/sotoki:2.0.2
[2023-02-01 12:02:55,482: INFO] Updating task-status=scraper_started
[2023-02-01 12:02:56,097: INFO] Starting resource monitor
[2023-02-01 12:03:15,312: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 1): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:03:25,322: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 2): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:03:45,344: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 3): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:04:15,376: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 4): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:04:55,417: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 5): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:05:45,465: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 6): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:06:45,527: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 7): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:07:55,598: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 8): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:09:15,678: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 9): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:10:45,769: DEBUG] Docker API Error for <bound method ContainerCollection.run of <docker.models.containers.ContainerCollection object at 0x7f026770e160>> (attempt 10): 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:12:25,869: ERROR] Unhandled exception: 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:12:25,869: ERROR] 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/task-worker", line 60, in main
    sys.exit(worker.run())
  File "/usr/src/app/task/worker.py", line 646, in run
    self.start_monitor()
  File "/usr/src/app/task/worker.py", line 300, in start_monitor
    self.monitor = start_monitor(
  File "/usr/src/app/common/docker.py", line 330, in start_monitor
    return run_container(
  File "/usr/src/app/common/docker.py", line 92, in run_container
    return retried_docker_call(docker_client.containers.run, *args, **kwargs)
  File "/usr/src/app/common/docker.py", line 61, in retried_docker_call
    raise exc
  File "/usr/src/app/common/docker.py", line 50, in retried_docker_call
    return docker_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 847, in run
    container = self.create(image=image, command=command,
  File "/usr/local/lib/python3.8/site-packages/docker/models/containers.py", line 906, in create
    resp = self.client.api.create_container(**create_kwargs)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/containers/create?name=monitor_2a8fe: Internal Server Error ("plugin no-trivial-root failed with error: AuthZPlugin.AuthZReq: --cap-add not allowed")
[2023-02-01 12:12:25,871: ERROR] exiting.
[2023-02-01 12:12:25,871: INFO] Trying to upload exception details
[2023-02-01 12:12:25,871: INFO] Updating task-status=failed
```

**Comment by kevinmcmurtrie** [comment]
Wrong place.  Moved to https://github.com/openzim/zimfarm/issues/741
