### ISSUE TITLE
Wiktionary EN does not scrape anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1789]
Latest run has following error:

[error] [2023-02-09T18:00:28.113Z] Error parsing article constructores
Failed to run mwoffliner after [6929s]: {
	"stack": "TypeError: nodeArray.push is not a function\n    at rewriteUrls (file:///tmp/mwoffliner/lib/util/rewriteUrls.js:181:27)\n    at rewriteUrlsOfDoc (file:///tmp/mwoffliner/lib/util/rewriteUrls.js:229:23)\n    at processArticleHtml (file:///tmp/mwoffliner/lib/util/saveArticles.js:374:25)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async saveArticle (file:///tmp/mwoffliner/lib/util/saveArticles.js:158:61)",
	"message": "nodeArray.push is not a function"
}

**********

See https://farm.openzim.org/pipeline/88b49c8e90efcd0af4915e36/debug

**Comment by kelson42** [comment]
Here an other scrape failing for the same reason https://farm.openzim.org/pipeline/075cd3bd12423d09c6960f36/debug
