### ISSUE TITLE
Simplify Axios Error in the log

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#1792]
When we have an Axios error, the log is too verbose, we get something like:
```
[error] [2023-02-03T03:13:40.230Z] Error downloading article World_History/The_Rise_of_Dictatorship_and_Totalitarianism/Quick_Quiz
Failed to run mwoffliner after [1441s]: {
	"message": "Request failed with status code 403",
	"name": "AxiosError",
	"stack": "AxiosError: Request failed with status code 403\n    at settle (file:///tmp/mwoffliner/node_modules/axios/lib/core/settle.js:19:12)\n    at IncomingMessage.handleStreamEnd (file:///tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:512:11)\n    at IncomingMessage.emit (node:events:539:35)\n    at IncomingMessage.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1344:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
	"config": {
		"transitional": {
			"silentJSONParsing": true,
			"forcedJSONParsing": true,
			"clarifyTimeoutError": false
		},
		"adapter": [
			"xhr",
			"http"
		],
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 10000000,
		"xsrfCookieName": "XSRF-TOKEN",
```

and then come hundreds of line. This is not useful and brings problem, see https://github.com/openzim/zimfarm/issues/751.

We should not have all this details (at least not what in the `config` part of the json... but actually I want a simple error with the HTTP error code and only the most important information.

**Comment by FledgeXu** [comment]
Hi, I want to do this issue as my good first issue. Could you assign it to me?

**Comment by FledgeXu** [comment]
Hi, I want to do this issue as my good first issue. Could you assign it to me?
