### ISSUE TITLE
Failed to configure development environment on Apple Silicon mac.

### ISSUE THREAD

**Issue by FledgeXu** [openzim/mwoffliner#1793]
# Description
I'm working on the #1792 and trying to config development on my Apple Silicon Mac. When I finished `npm ci` and run `npm run start`, mwoffliner crashed.
# Enverioment
Chip: `Apple M2 Max`
OS: `macOS 13.2.1 (22D68)`
# Reproduce
Run: `npm run start`
# Log
```
Error: dlopen(/Users/fledge/Developer/mwoffliner/node_modules/@openzim/libzim/build/Release/zim_binding.node, 0x0001): symbol not found in flat namespace '__ZN3zim6writer7Article15getNextCategoryEv'
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1310:18)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Function.Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.bindings [as default] (/Users/fledge/Developer/mwoffliner/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/fledge/Developer/mwoffliner/node_modules/@openzim/libzim/dist/zim.js:8:28)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Object.require.extensions.<computed> [as .js] (/Users/fledge/Developer/mwoffliner/node_modules/ts-node/src/index.ts:1608:43) {
  code: 'ERR_DLOPEN_FAILED'
}
```

**Comment by FledgeXu** [comment]
Because libzim not yet supported the `macos-arm64`, so you have compiler it from scratch and replace the one under `node_modules/@openzim/libzim/download`.
We better add the Apple Silicon support for `libzim` and `node-libzim`.

**Comment by kelson42** [comment]
@FledgeXu You have to compile the libzim first. Otherwise duplicate of https://github.com/kiwix/kiwix-build/issues/570
