### ISSUE TITLE
Error: Unable to find appropriate API end-point to retrieve article HTML

### ISSUE THREAD

**Issue by SuzanneSoy** [openzim/mwoffliner#1836]
I installed mediawiki 1.39.3 on localhost following the steps at https://www.mediawiki.org/wiki/Manual:Running_MediaWiki_on_Debian_or_Ubuntu, but mwoffliner gives the following error:

```
(node:192851) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[log] [2023-05-07T00:09:08.202Z] Starting mwoffliner v1.12.1...
[log] [2023-05-07T00:09:08.207Z] Getting text direction...
[log] [2023-05-07T00:09:08.207Z] Getting site info...
[log] [2023-05-07T00:09:08.207Z] Getting sub-title...
[log] [2023-05-07T00:09:08.213Z] closing sanitize redis DB
[log] [2023-05-07T00:09:08.340Z] Text direction is [ltr]
[log] [2023-05-07T00:09:08.536Z] Base Url:  undefined
[log] [2023-05-07T00:09:08.536Z] Base Url for Main Page:  undefined
Failed to run mwoffliner after [0s]: {
	"stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///home/me/mwoffliner/node_modules/mwoffliner/lib/Downloader.js:163:19)\n    at Module.execute (file:///home/me/mwoffliner/node_modules/mwoffliner/lib/mwoffliner.lib.js:125:22)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
	"message": "Unable to find appropriate API end-point to retrieve article HTML"
}


**********

Unable to find appropriate API end-point to retrieve article HTML

**********
```

I have tried the following commands and many variations, with no success.

```
../node_modules/.bin/mwoffliner --mwUrl=http://localhost/
```

```
../node_modules/.bin/mwoffliner --mwUrl=http://localhost/ --customMainPage=Accueil --mwWikiPath=/mediawiki/index.php/ --mwApiPath=/mediawiki/api.php/ --mwRestApiPath=/mediawiki/rest.php/ --mwModulePath=/mediawiki/load.php/ --adminEmail=me@domain.com
```

**Comment by SuzanneSoy** [comment]
Managed to make it work with this command-line:

```
../node_modules/.bin/mwoffliner --mwUrl=http://localhost/ --customMainPage=My_Main_Page --mwWikiPath='/mediawiki/index.php?' --mwApiPath='/mediawiki/api.php' --mwRestApiPath='/mediawiki/rest.php' --mwModulePath='/mediawiki/load.php' --adminEmail=me@domain.com
```

**Comment by Jaifroid** [comment]
Glad you could solve it!

**Comment by kelson42** [comment]
@SuzanneSoy Do you want us to generate and publish a ZIM fike of your wiki?

**Comment by SuzanneSoy** [comment]
No thanks, I'm archiving an old private wiki into a set of static HTML pages. Turns out wikizimmer.js is a better tool for this, but having the ZIM backup was useful :)
