### ISSUE TITLE
404 when trying to archive stardewvalleywiki.com

### ISSUE THREAD

**Issue by IronCraftMan** [openzim/mwoffliner#1837]
I've been trying to archive stardewvalleywiki.com and I come upon this error:

```
[log] [2023-05-10T16:18:02.911Z] Not able to download content for https://stardewvalleywiki.com/Stardew_Valley/wiki/ due to AxiosError: Request failed with status code 404
[error] [2023-05-10T16:18:02.914Z] FATAL - Failed to get MediaWiki Metadata
```

If i don't include "/Stardew_Valley/" in the URL I get mostly the same error:

```
[error] [2023-05-10T16:25:24.961Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [1s]: {
	"message": "Request failed with status code 404",
...
```

The full log with command:

```
docker run --volume="$(pwd)/out":/out -ti ghcr.io/openzim/mwoffliner mwoffliner --mwUrl="https://stardewvalleywiki.com/Stardew_Valley" --customZimTitle="Stardew Valley Wiki" --adminEmail="admin@kiwix.org" --customMainPage="Stardew_Valley" --articleList="https://stardewvalleywiki.com/Special:AllPages"
starting redis-server in the background…
[log] [2023-05-10T16:18:02.727Z] Starting mwoffliner v1.12.1...
[log] [2023-05-10T16:18:02.743Z] Getting text direction...
[log] [2023-05-10T16:18:02.745Z] Getting site info...
[log] [2023-05-10T16:18:02.747Z] Getting sub-title...
[log] [2023-05-10T16:18:02.787Z] closing sanitize redis DB
[log] [2023-05-10T16:18:02.911Z] Not able to download content for https://stardewvalleywiki.com/Stardew_Valley/wiki/ due to AxiosError: Request failed with status code 404
[error] [2023-05-10T16:18:02.914Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [0s]: {
	"message": "Request failed with status code 404",
	"name": "AxiosError",
	"stack": "AxiosError: Request failed with status code 404\n    at settle (file:///tmp/mwoffliner/node_modules/axios/lib/core/settle.js:19:12)\n    at BrotliDecompress.handleStreamEnd (file:///tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:548:11)\n    at BrotliDecompress.emit (node:events:539:35)\n    at BrotliDecompress.emit (node:domain:475:12)\n    at endReadableNT (node:internal/streams/readable:1344:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)",
	"config": {
		"transitional": {
			"silentJSONParsing": true,
			"forcedJSONParsing": true,
			"clarifyTimeoutError": false
		},
		"adapter": [
			"xhr",
			"http"
		],
		"transformRequest": [
			null
		],
		"transformResponse": [
			null
		],
		"timeout": 120000,
		"xsrfCookieName": "XSRF-TOKEN",
		"xsrfHeaderName": "X-XSRF-TOKEN",
		"maxContentLength": -1,
		"maxBodyLength": -1,
		"env": {},
		"headers": {
			"Accept": "application/json, text/plain, */*",
			"cache-control": "public, max-stale=86400",
			"user-agent": "MWOffliner/HEAD (admin@kiwix.org)",
			"cookie": "",
			"Accept-Encoding": "gzip, compress, deflate, br"
		},
		"httpAgent": {
			"_events": {},
			"_eventsCount": 2,
			"defaultPort": 80,
			"protocol": "http:",
			"options": {
				"keepAlive": true,
				"noDelay": true,
				"path": null
			},
			"requests": {},
			"sockets": {},
			"freeSockets": {},
			"keepAliveMsecs": 1000,
			"keepAlive": true,
			"maxSockets": null,
			"maxFreeSockets": 256,
			"scheduling": "lifo",
			"maxTotalSockets": null,
			"totalSocketCount": 0
		},
		"httpsAgent": {
			"_events": {},
			"_eventsCount": 2,
			"defaultPort": 443,
			"protocol": "https:",
			"options": {
				"keepAlive": true,
				"noDelay": true,
				"path": null
			},
			"requests": {},
			"sockets": {},
			"freeSockets": {
				"stardewvalleywiki.com:443:::::::::::::::::::::": [
					{
						"_tlsOptions": {
							"pipe": false,
							"secureContext": {
								"context": {}
							},
							"isServer": false,
							"requestCert": true,
							"rejectUnauthorized": true
						},
						"_secureEstablished": true,
						"_securePending": false,
						"_newSessionPending": false,
						"_controlReleased": true,
						"secureConnecting": false,
						"_SNICallback": null,
						"servername": "stardewvalleywiki.com",
						"alpnProtocol": false,
						"authorized": true,
						"authorizationError": null,
						"encrypted": true,
						"_events": {
							"close": [
								null,
								null,
								null
							],
							"timeout": [
								null,
								null
							]
						},
						"_eventsCount": 9,
						"connecting": false,
						"_hadError": false,
						"_parent": null,
						"_host": "stardewvalleywiki.com",
						"_readableState": {
							"objectMode": false,
							"highWaterMark": 16384,
							"buffer": {
								"head": null,
								"tail": null,
								"length": 0
							},
							"length": 0,
							"pipes": [],
							"flowing": true,
							"ended": false,
							"endEmitted": false,
							"reading": true,
							"constructed": true,
							"sync": false,
							"needReadable": true,
							"emittedReadable": false,
							"readableListening": false,
							"resumeScheduled": false,
							"errorEmitted": false,
							"emitClose": false,
							"autoDestroy": true,
							"destroyed": false,
							"errored": null,
							"closed": false,
							"closeEmitted": false,
							"defaultEncoding": "utf8",
							"awaitDrainWriters": null,
							"multiAwaitDrain": false,
							"readingMore": false,
							"dataEmitted": true,
							"decoder": null,
							"encoding": null
						},
						"_writableState": {
							"objectMode": false,
							"highWaterMark": 16384,
							"finalCalled": false,
							"needDrain": false,
							"ending": false,
							"ended": false,
							"finished": false,
							"destroyed": false,
							"decodeStrings": false,
							"defaultEncoding": "utf8",
							"length": 0,
							"writing": false,
							"corked": 0,
							"sync": false,
							"bufferProcessing": false,
							"writecb": null,
							"writelen": 0,
							"afterWriteTickInfo": null,
							"buffered": [],
							"bufferedIndex": 0,
							"allBuffers": true,
							"allNoop": true,
							"pendingcb": 0,
							"constructed": true,
							"prefinished": false,
							"errorEmitted": false,
							"emitClose": false,
							"autoDestroy": true,
							"errored": null,
							"closed": false,
							"closeEmitted": false
						},
						"allowHalfOpen": false,
						"_sockname": null,
						"_pendingData": null,
						"_pendingEncoding": "",
						"_server": null,
						"ssl": {
							"_parent": {
								"reading": true,
								"onconnection": null
							},
							"_secureContext": {
								"context": {}
							},
							"reading": true
						},
						"_requestCert": true,
						"_rejectUnauthorized": true,
						"parser": null,
						"_httpMessage": null,
						"timeout": 0
					},
					{
						"_tlsOptions": {
							"pipe": false,
							"secureContext": {
								"context": {}
							},
							"isServer": false,
							"requestCert": true,
							"rejectUnauthorized": true
						},
						"_secureEstablished": true,
						"_securePending": false,
						"_newSessionPending": false,
						"_controlReleased": true,
						"secureConnecting": false,
						"_SNICallback": null,
						"servername": "stardewvalleywiki.com",
						"alpnProtocol": false,
						"authorized": true,
						"authorizationError": null,
						"encrypted": true,
						"_events": {
							"close": [
								null,
								null,
								null
							],
							"timeout": [
								null,
								null
							]
						},
						"_eventsCount": 9,
						"connecting": false,
						"_hadError": false,
						"_parent": null,
						"_host": "stardewvalleywiki.com",
						"_readableState": {
							"objectMode": false,
							"highWaterMark": 16384,
							"buffer": {
								"head": null,
								"tail": null,
								"length": 0
							},
							"length": 0,
							"pipes": [],
							"flowing": true,
							"ended": false,
							"endEmitted": false,
							"reading": true,
							"constructed": true,
							"sync": false,
							"needReadable": true,
							"emittedReadable": false,
							"readableListening": false,
							"resumeScheduled": false,
							"errorEmitted": false,
							"emitClose": false,
							"autoDestroy": true,
							"destroyed": false,
							"errored": null,
							"closed": false,
							"closeEmitted": false,
							"defaultEncoding": "utf8",
							"awaitDrainWriters": null,
							"multiAwaitDrain": false,
							"readingMore": false,
							"dataEmitted": true,
							"decoder": null,
							"encoding": null
						},
						"_writableState": {
							"objectMode": false,
							"highWaterMark": 16384,
							"finalCalled": false,
							"needDrain": false,
							"ending": false,
							"ended": false,
							"finished": false,
							"destroyed": false,
							"decodeStrings": false,
							"defaultEncoding": "utf8",
							"length": 0,
							"writing": false,
							"corked": 0,
							"sync": false,
							"bufferProcessing": false,
							"writecb": null,
							"writelen": 0,
							"afterWriteTickInfo": null,
							"buffered": [],
							"bufferedIndex": 0,
							"allBuffers": true,
							"allNoop": true,
							"pendingcb": 0,
							"constructed": true,
							"prefinished": false,
							"errorEmitted": false,
							"emitClose": false,
							"autoDestroy": true,
							"errored": null,
							"closed": false,
							"closeEmitted": false
						},
						"allowHalfOpen": false,
						"_sockname": null,
						"_pendingData": null,
						"_pendingEncoding": "",
						"_server": null,
						"ssl": {
							"_parent": {
								"reading": true,
								"onconnection": null
							},
							"_secureContext": {
								"context": {}
							},
							"reading": true
						},
						"_requestCert": true,
						"_rejectUnauthorized": true,
						"parser": null,
						"_httpMessage": null,
						"timeout": 0
					}
				]
			},
			"keepAliveMsecs": 1000,
			"keepAlive": true,
			"maxSockets": null,
			"maxFreeSockets": 256,
			"scheduling": "lifo",
			"maxTotalSockets": null,
			"totalSocketCount": 2,
			"maxCachedSessions": 100,
			"_sessionCache": {
				"map": {
					"stardewvalleywiki.com:443:::::::::::::::::::::": {
						"type": "Buffer",
						"data": [
						# long list of numbers omitted
						]
					}
				},
				"list": [
					"stardewvalleywiki.com:443:::::::::::::::::::::"
				]
			}
		},
		"responseType": "arraybuffer",
		"method": "get",
		"url": "https://stardewvalleywiki.com/Stardew_Valley/wiki/"
	},
	"code": "ERR_BAD_REQUEST",
	"status": 404
}


**********

Request failed with status code 404

**********

```

**Comment by kelson42** [comment]
@IronCraftMan We have now a recipe here https://farm.openzim.org/recipes/stardewvalley_wiki in our Zimfarm. The problem is that you don't use the VisualEditor, so there is no API for us to consume to make an offline version.
