### ISSUE TITLE
Unable to find appropriate API end-point to retrieve article HTML

### ISSUE THREAD

**Issue by maxslug** [openzim/mwoffliner#1913]
I'm having a problem running the tool.   I tried the fixes in #1892 #1857 #1836 #1584 but without any luck.

Tool Command run
```
npm run mwoffliner -- \
        --mwUrl="https://mkv-gti.net" \
        --mwWikiPath="/wiki/"  \
        --mwApiPath="/wiki/api.php"  \
        --mwRestApiPath="/wiki/rest.php" \
        --mwModulePath="/wiki/load.php" \
        --adminEmail=admin@mkv-gti.net \
        --redis="redis://localhost:6379" \
        --outputDirectory=out \
        --optimisationCacheUrl=\"\" \
        --verbose
```

Output:

```
> mwoffliner@1.13.0 mwoffliner
> node ./lib/cli.js --mwUrl=https://mkv-gti.net --mwWikiPath=/wiki/ --mwApiPath=/wiki/api.php --mwRestApiPath=/wiki/rest.php --mwModulePath=/wiki/load.php --adminEmail=admin@mkv-gti.net --redis=redis://localhost:6379 --outputDirectory=out --optimisationCacheUrl="" --verbose

(node:28081) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[log] [2023-09-21T18:58:28.899Z] Starting mwoffliner v1.13.0...
[info] [2023-09-21T18:58:28.905Z] Using custom flavour: no
[log] [2023-09-21T18:58:28.913Z] Getting text direction...
[log] [2023-09-21T18:58:28.914Z] Getting site info...
[log] [2023-09-21T18:58:28.914Z] Getting sub-title...
[info] [2023-09-21T18:58:28.916Z] Downloading [https://mkv-gti.net/wiki/]
[info] [2023-09-21T18:58:28.923Z] Getting JSON from [https://mkv-gti.net/wiki/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2023-09-21T18:58:28.928Z] Downloading [https://mkv-gti.net/wiki/]
[log] [2023-09-21T18:58:28.959Z] closing sanitize redis DB
[log] [2023-09-21T18:58:29.200Z] Text direction is [ltr]
[info] [2023-09-21T18:58:29.201Z] Getting JSON from [https://mkv-gti.net/wiki/api.php?action=query&meta=siteinfo&format=json]
[info] [2023-09-21T18:58:29.226Z] Downloading [https://mkv-gti.net/wiki/resources/assets/Fast_mkvgti_wiki_logo.jpg]
[info] [2023-09-21T18:58:29.436Z] Getting JSON from [https://mkv-gti.net/wiki/api.php?action=query&format=json&prop=redirects%7Crevisions%7Ccoordinates&rdlimit=max&rdnamespace=]
[info] [2023-09-21T18:58:29.455Z] Coordinates not available on this wiki
[log] [2023-09-21T18:58:29.456Z] Base Url:  undefined
[log] [2023-09-21T18:58:29.457Z] Base Url for Main Page:  undefined
[error] [2023-09-21T18:58:29.458Z] Failed to run mwoffliner after [1s]: {
        "stack": "Error: Unable to find appropriate API end-point to retrieve article HTML\n    at Downloader.setBaseUrls (file:///home/max/migrate/wiki/mwoffliner/mwoffliner-1.13.0/lib/Downloader.js:172:19)\n    at Module.execute (file:///home/max/migrate/wiki/mwoffliner/mwoffliner-1.13.0/lib/mwoffliner.lib.js:134:22)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
        "message": "Unable to find appropriate API end-point to retrieve article HTML"
}
[error] [2023-09-21T18:58:29.459Z]

**********

Unable to find appropriate API end-point to retrieve article HTML

**********
```

Any ideas? Thanks!

**Comment by kelson42** [comment]
For third-party Mediawiki instances, the only end-point supported for now, is the one created if you have the extension VisualEditor installed. Here this seems not to be the case which explains the current situation. Next release should integrate the support of the very new Mediawiki REST API (will need a recent version of Mediawiki). You can follow[ this ticket](https://github.com/openzim/mwoffliner/issues/1601)... and we would be glad, once we are that far, if you can test it (if you control the Mediawiki instance of https://mkv-gti.net), This should be the matter of a few feeks.

**Comment by maxslug** [comment]
Thanks @kelson42 !

Looks like you need at least MW 1.35 to install VisualEditor : https://www.mediawiki.org/wiki/Special:ExtensionDistributor/VisualEditor .  My wiki is on an ancient 1.25.

Unfortunately, the box will be decommissioned soon, so I can't do an upgrade and test of the new API in a few weeks.

**Comment by kelson42** [comment]
@maxslug Hopefully you have a good backup!

**Comment by maxslug** [comment]
@kelson42 yes, luckily I'm able to dump the SQL database and run the dump that archive.org uses.

I'm trying to sunset these sites, but I was hoping to create a static browseable site with the help of mwoffliner.  I'll just put it on the Internet Archive and point to that, but unfortunately it's not browseable. 

```
mysqldump -p wiki | gzip > wiki.sql.gz
cd ~/public_html/wiki/maintenance
tar cvfz wiki.images.tar.gz -C ~/public_html/wiki archive images thumb
# Use the top of one of the XML dumps to figure out which namespaces you want to keep. 
php dumpBackup.php --current --include-files --filter=namespace:0,6 --output=gzip:~/wiki.current.xml.gz > /dev/null
php dumpBackup.php --full    --include-files --filter=namespace:0,6 --output=gzip:~/wiki.full.xml.gz > /dev/null
```
