### ISSUE TITLE
Bug with Paradox Wikis [EU4]: mwUrl [https://eu4.paradoxwikis.com/] is not valid.

### ISSUE THREAD

**Issue by DataAddict42** [openzim/mwoffliner#1977]
I was trying to download the paradox wiki for EU4, and I found that mwoffliner will not even start downloading it. It just says its an invalid URL.

Command I ran:

`mwoffliner --mwUrl="https://eu4.paradoxwikis.com/" --adminEmail="foo@bar.net" --mwWikiPath="/Europa_Universalis_4_Wiki" --mwApiPath="/api.php" --verbose --speed="4" --resume --mwModulePath="/load.php" --format="nopic,novid" --osTmpDir="/tmp" --outputDirectory="/output" --webp --customZimDescription="Europa Universalis IV - Paradox Wikis" --mwRestApiPath="/wiki/" --requestTimeout="10000"`

Terminal Output:

```
(node:2118) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[error] [2024-01-21T21:37:46.813Z] Failed to run mwoffliner after [0s]: {
	"stack": "Error: mwUrl [https://eu4.paradoxwikis.com/] is not valid.\n    at file:///usr/lib/node_modules/mwoffliner/lib/sanitize-argument.js:103:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async sanitize_mwUrl (file:///usr/lib/node_modules/mwoffliner/lib/sanitize-argument.js:102:5)\n    at async sanitize_all (file:///usr/lib/node_modules/mwoffliner/lib/sanitize-argument.js:54:5)",
	"message": "mwUrl [https://eu4.paradoxwikis.com/] is not valid."
}
[error] [2024-01-21T21:37:46.813Z] 

**********

mwUrl [https://eu4.paradoxwikis.com/] is not valid.

**********

```

**Comment by adilsyed518** [comment]
I have this problem with other sites as well. It seems ca certificate is not loaded for ssl. I am looking for a configuration option that will use the provided ca-certificate file so that it will allow ssl handshake. Please let me know if you find any?

**Comment by kelson42** [comment]
@benoit74 I see you have tried to restart our recipe a few days ago https://farm.openzim.org/pipeline/824a03a0-8701-4b7f-abe0-6fe2ce231e9c/debug

Any clue what goes wrong with this wiki?

**Comment by Markus-Rost** [comment]
The wiki is using a custom skin called `vectorparadox`, it's just vector-legacy with minor modifications but the different name means ActionParse will only get errors when trying to use `useskin=vector`

**Comment by benoit74** [comment]
ZIM request is at https://github.com/openzim/zim-requests/issues/1319
Last (known) issue preventing to ZIM this wiki is already registered at https://github.com/openzim/mwoffliner/issues/2373.
The problem encountered by op seems to be fixed with work (merged but not released) related to User-Agent.
I propose to close this issue which is now a kind of duplicate (we have more precise issue to track the matter).
