### ISSUE TITLE
mwoffliner 1.13.0 & OVM ubuntu 22.04.3 & mediawiki 1.17 - Status 404

### ISSUE THREAD

**Issue by banO1ne** [openzim/mwoffliner#2006]
Hi all,
I'm new to this topic. I installed OVM ubuntu 22.04.3 and managed to get mwoffliner installed. 

edvab@edvab:~$ mwoffliner --version
1.13.0

Everytime i try to generate ZIM file of our local private Wiki system / Version 1.17 (with user / passwd authentication) it get's me an error.

mwoffliner --mwUrl=http://192.168.1.115/mediawiki --adminEmail=foo@bar.net --verbose --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php --mwUsername=user --mwPassword=password

(node:12347) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).

For more information, check the migration guide at https://a.co/7PzMCcy

(Use `node --trace-warnings ...` to show where the warning was created)

[log] [2024-03-11T15:19:39.498Z] Starting mwoffliner v1.13.0...

[info] [2024-03-11T15:19:39.501Z] Using custom flavour: no

[info] [2024-03-11T15:19:39.504Z] Downloading [http://192.168.1.115/mediawiki/api.php?action=query&meta=tokens&type=login&format=json]

[log] [2024-03-11T15:19:39.510Z] closing sanitize redis DB

[error] [2024-03-11T15:19:39.562Z] Failed to run mwoffliner after [0s]: {

	"stack": "TypeError: Cannot read property 'tokens' of undefined\n    at MediaWiki.login (file:///home/edvab/.nvm/versions/node/v14.19.0/lib/node_modules/mwoffliner/lib/MediaWiki.js:62:66)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Module.execute (file:///home/edvab/.nvm/versions/node/v14.19.0/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:105:5)",

	"message": "Cannot read property 'tokens' of undefined"

}

[error] [2024-03-11T15:19:39.562Z] 

**********

Cannot read property 'tokens' of undefined

**********

What might be the problem? 

Thanks in advance.

**Comment by kelson42** [comment]
This seems to be a problem with the authentication indeed... we never used that feature, so it might be broken.

**Comment by kelson42** [comment]
@benoit74 [has fixed a few days the handling of scraping of private wiki (with user/login)](https://github.com/openzim/mwoffliner/pull/2363). I guess it probably fixes this issue which could be closed as duplicate of https://github.com/openzim/mwoffliner/issues/2361?

**Comment by benoit74** [comment]
Yep, think so, please reopen if you still face issue with `main` version (or `latest` if you use Docker). This is going to be released in 1.16.0
