### ISSUE TITLE
wikipedia_bs_all is failing with `Cannot read properties of undefined (reading 'type')`

### ISSUE THREAD

**Issue by benoit74** [openzim/mwoffliner#2007]
See https://github.com/openzim/zim-requests/issues/881

Error:

```
[error] [2024-03-11T17:32:55.260Z] Failed to run mwoffliner after [1892s]: {
	"stack": "TypeError: Cannot read properties of undefined (reading 'type')\n    at TokenStream.LA (/tmp/mwoffliner/node_modules/domino/lib/cssparser.js:810:30)\n    at TokenStream.advance (/tmp/mwoffliner/node_modules/domino/lib/cssparser.js:683:20)\n    at Parser._readDeclarations (/tmp/mwoffliner/node_modules/domino/lib/cssparser.js:3402:42)\n    at Parser.parseStyleAttribute (/tmp/mwoffliner/node_modules/domino/lib/cssparser.js:3581:22)\n    at parseStyles (/tmp/mwoffliner/node_modules/domino/lib/CSSStyleDeclaration.js:23:10)\n    at CSSStyleDeclaration.get (/tmp/mwoffliner/node_modules/domino/lib/CSSStyleDeclaration.js:38:28)\n    at CSSStyleDeclaration.value (/tmp/mwoffliner/node_modules/domino/lib/CSSStyleDeclaration.js:178:23)\n    at file:///tmp/mwoffliner/lib/util/saveArticles.js:768:24\n    at Array.map (<anonymous>)\n    at applyOtherTreatments (file:///tmp/mwoffliner/lib/util/saveArticles.js:765:39)",
	"message": "Cannot read properties of undefined (reading 'type')"
}
[error] [2024-03-11T17:32:55.261Z] 

**********

Cannot read properties of undefined (reading 'type')

**********
```

Might be related to #1998

**Comment by kelson42** [comment]
@benoit74 Imstrongly suspect we could close that one
