### ISSUE TITLE
Input buffer contains unsupported image format

### ISSUE THREAD

**Issue by benoit74** [openzim/mwoffliner#2028]
Zimfarm recipe: https://farm.openzim.org/recipes/encyclopediaofmath.org_en_all

Zim-request details: https://github.com/openzim/zim-requests/issues/964#issuecomment-2124736481

Log:
```
[error] [2024-05-22T12:56:44.462Z] Failed to run mwoffliner after [18s]: {
	"stack": "Error: Input buffer contains unsupported image format",
	"message": "Input buffer contains unsupported image format"
}
[error] [2024-05-22T12:56:44.462Z] 

**********

Input buffer contains unsupported image format

**********
```

It is pretty hard to tell which image has been grabbed and failed to be read, making the fix even more delicate.

**Comment by audiodude** [comment]
From googling, it looks like that's an error message from the `sharp` library.

Probably happening here?

https://github.com/openzim/mwoffliner/blob/9cc613fb246150e25df68041332a869810018cf9/src/Downloader.ts#L488

Might just be a bad URL that's getting erroneously read as image data.

**Comment by audiodude** [comment]
The proximate cause of the error is the fact that the URL:

https://encyclopediaofmath.org/common/spr_logo.gif

Does a 301 to https://encyclopediaofmath.org/wiki/Main_Page

Presumably, this "logo" link is somewhere in the initial metadata that mwoffliner gathers about the wiki. So the bug is that mwoffliner is hardcoded to download this as image data and doesn't consider 301 to be an error status. It then crashes early on in the scraping process.

**Comment by audiodude** [comment]
If the folks putting in the request would like to fix their problem without waiting for mwoffliner, I would suggest putting an image (even a 1x1 PNG) at that URL.

**Comment by kelson42** [comment]
Here the solution is IMHO to test the format of the image at the same time (early) like other ZIM metadata.

**Comment by kelson42** [comment]
This issue is still valid after upgrading sharp, see https://farm.openzim.org/pipeline/1c1fbd14-2480-4338-a16f-ade566504ba7/debug

**Comment by benoit74** [comment]
> Here the solution is IMHO to test the format of the image at the same time (early) like other ZIM metadata.

IMHO there is nothing to fix.

Scraper requests logo URL from https://encyclopediaofmath.org/api.php?action=query&format=json&meta=siteinfo&formatversion=2&siprop=general|skins

Here it finds that the logo is at https://encyclopediaofmath.org/common/spr_logo.gif

It download this image which is in fact an HTML document since https://encyclopediaofmath.org/common/spr_logo.gif redirects to https://encyclopediaofmath.org/wiki/Main_Page and scrapers properly follow the redirect.

Scraper then stops with a message saying that image is of unrecognized format, which is true.

Check is done early as other ZIM metadata (it takes less than 10 secs for scraper to fail).

This is just a misconfiguration at Mediawiki / hosting level. Nothing the scraper can workaround on its own.

Adding a `--customZimFavicon` image is sufficient to workaround the Mediawiki misconfiguration, see https://farm.openzim.org/pipeline/187cbd83-aef8-4da7-a0bd-45e61bcc4059/debug (might fail at a later stage, but at least it achieved to download the icon).

I propose to close this issue.

**Comment by benoit74** [comment]
Also note that log is now way clearer about which image failed to download since we now have proper stacktrace, we see problem occurred in `getIllustrationMetadata`:

```
[error] [2025-07-25T11:08:04.479Z] Failed to run mwoffliner after [3s]:
 Error: Input buffer contains unsupported image format
    at Sharp.toBuffer (/tmp/mwoffliner/node_modules/sharp/lib/output.js:163:17)
    at getIllustrationMetadata (/tmp/mwoffliner/src/mwoffliner.lib.ts:567:63)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Module.execute (/tmp/mwoffliner/src/mwoffliner.lib.ts:211:29)
```
