### ISSUE TITLE
Zim package Wikiversité is not working properly

### ISSUE THREAD

**Issue by journuit** [openzim/mwoffliner#2031]
Hi and thanks for the great work with kiwix and zimit!

Within kiwix I downloaded many zim files which work great, but the "Wikiversité" file is not working properly: the links to the various "falcultés" are not links (not clickable) so the content of the site is not reachable.

I tried to generate a new zim file with zimit and it did work. The generated file is almost 8 GB large (versus less than 2 GB for the file packaged with kiwix). 

The links are clickable now, but the problem is now with the drop down menus within each faculté (e.g. philosophie or politique) for the mobile version of the site. They do not work so the content is still unreachable.

Any help would be greatly appreciated :-)

https://fr.wikiversity.org/wiki/Wikiversit%C3%A9:Accueil

**Comment by journuit** [comment]
Hi @kelson42,
thank you for your reply, no problem with waiting, this is not urgent, just a bit frustrating.
Thanks again to all of you for the great work on those tools!

**Comment by benoit74** [comment]
I just checked with "new to come" ActionParse API (to be made available in 1.15, and might become the default in 2.0) and it works well.

We will probably close this issue then, once we've confirmed in 2.0 that ActionParse renderer is good to go. I doubt we will invest any effort until then in fixing this issue which comes from another API (but from end-user perspective, bug will be fixed anyway).

**Comment by kelson42** [comment]
I just have added namespace `106` (or `Faculté`) to the recipe.

**Comment by kelson42** [comment]
I have restarted a new attempt with current `dev` version https://farm.openzim.org/pipeline/26320a03-7a4a-42a8-a486-1753372eab5f

**Comment by kelson42** [comment]
@benoit74 The scrape dies with whatblooks to me to be a new scenario
```
[warn] [2025-06-27T06:22:15.824Z] Article Signaux_physiques_(PCSI)/Exercices/Optique_géométrique_:_lentilles_minces failed to download from 'https://fr.wikiversity.org/w/api.php?action=parse&format=json&prop=modules%7Cjsconfigvars%7Cheadhtml%7Ctext%7Cdisplaytitle&parsoid=1&page=Signaux_physiques_%28PCSI%29%2FExercices%2FOptique_g%C3%A9om%C3%A9trique_%3A_lentilles_minces&useskin=vector-2022&redirects=1&formatversion=2' with 'null' error code, '200' HTTP return code and 'application/json; charset=utf-8' content-type returned instead:
{"error":{"code":"internal_api_error_Wikimedia\\RequestTimeout\\RequestTimeoutException","info":"[fb5e3c74-66e5-4318-a4f3-35136d1c8c9f] Caught exception of type Wikimedia\\RequestTimeout\\RequestTimeoutException","errorclass":"Wikimedia\\RequestTimeout\\RequestTimeoutException"},"servedby":"mw-api-ext.eqiad.main-74c966b8c9-g8pvx"}
[error] [2025-06-27T06:22:15.825Z] Error downloading/rendering article Signaux_physiques_(PCSI)/Exercices/Optique_géométrique_:_lentilles_minces
[error] [2025-06-27T06:22:15.826Z] Failed to run mwoffliner after [82s]:
 TypeError: Cannot read properties of null (reading 'includes')
    at <anonymous> (/tmp/mwoffliner/src/error.manager.ts:262:95)
    at Array.findIndex (<anonymous>)
    at findFirstMatchingRule (/tmp/mwoffliner/src/error.manager.ts:262:60)
    at Downloader.getArticle (/tmp/mwoffliner/src/Downloader.ts:509:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async <anonymous> (/tmp/mwoffliner/src/util/saveArticles.ts:308:18)

```

**Comment by benoit74** [comment]
This issue is https://github.com/openzim/mwoffliner/issues/2386, fixed in `main` / `dev`

**Comment by benoit74** [comment]
Now the problem is that too many articles failed to download: https://github.com/openzim/mwoffliner/issues/2336

Nothing left to fix here, so closing.
