### ISSUE TITLE
pokemon.fandom.com test failing after site API now has "404" page that returns 200

### ISSUE THREAD

**Issue by audiodude** [openzim/mwoffliner#2035]
At some point, the following test started failing:

```
 FAIL  test/unit/mwApiCapabilities.test.ts
  Checking Mediawiki capabilities
    ✕ test capabilities of pokemon.fandom.com with default receipt (1304 ms)
    ○ skipped test capabilities of en.wikipedia.org
    ○ skipped test capabilities of wiki.openstreetmap.org
    ○ skipped test capabilities of fo.wikisource.org
    ○ skipped test capabilities of minecraft.wiki with correct VisualEditor receipt
    ○ skipped test capabilities of pokemon.fandom.com with correct VisualEditor receipt
    ○ skipped test capabilities of pokemon.fandom.com with RestApi receipt

  ● Checking Mediawiki capabilities › test capabilities of pokemon.fandom.com with default receipt

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      64 |     expect(await MediaWiki.hasWikimediaMobileApi()).toBe(false)
      65 |     expect(await MediaWiki.hasRestApi()).toBe(false)
    > 66 |     expect(await MediaWiki.hasVisualEditorApi()).toBe(false)
         |                                                  ^
      67 |   })
      68 |
      69 |   test('test capabilities of pokemon.fandom.com with RestApi receipt', async () => {

      at Object.<anonymous> (test/unit/mwApiCapabilities.test.ts:66:50)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 6 skipped, 7 total
```

The test for API availability looks for a 200 response without certain headers: https://github.com/openzim/mwoffliner/blob/main/src/util/mw-api.ts#L269

The current response for `https://pokemon.fandom.com/w/api.php` (the default URL which is supposed to fail) returns a 301 to `https://pokemon.fandom.com/wiki/Api.php`, which then returns a 200 with no error headers. At that point, `mwoffliner` assumes the API exists.

It seems likely that this behavior should be fixed/accounted for. Not clear if this is only for fandom wikis.

A similar thing happens with:

```
  ● Checking Mediawiki capabilities › test capabilities of pokemon.fandom.com with RestApi receipt

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      74 |     expect(await MediaWiki.hasWikimediaDesktopApi()).toBe(false)
      75 |     expect(await MediaWiki.hasWikimediaMobileApi()).toBe(false)
    > 76 |     expect(await MediaWiki.hasVisualEditorApi()).toBe(false)
         |                                                  ^
      77 |
      78 |     /* TODO:
      79 |       Title MediaWiki:Sidebar does not exist for Mediawiki Rest Api in pokemon.fandom.com for some reason. This will lead to incorrect capability check

      at Object.<anonymous> (test/unit/mwApiCapabilities.test.ts:76:50)
  ● Checking Mediawiki capabilities › test capabilities of pokemon.fandom.com with RestApi receipt

    expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      74 |     expect(await MediaWiki.hasWikimediaDesktopApi()).toBe(false)
      75 |     expect(await MediaWiki.hasWikimediaMobileApi()).toBe(false)
    > 76 |     expect(await MediaWiki.hasVisualEditorApi()).toBe(false)
         |                                                  ^
      77 |
      78 |     /* TODO:
      79 |       Title MediaWiki:Sidebar does not exist for Mediawiki Rest Api in pokemon.fandom.com for some reason. This will lead to incorrect capability check

      at Object.<anonymous> (test/unit/mwApiCapabilities.test.ts:76:50)
```

For now however, we should simply disable the failing tests.

**Comment by kelson42** [comment]
Works fine with https://farm.openzim.org/pipeline/4895ecf9-eab3-4402-a184-b969a08e7426 (so lastest released version of MWoffliner), so we have a problem somewhere our side.

**Comment by kelson42** [comment]
I confirm the configuration of Fandom is very weird and autodetection is fooled.

Real `api.php` is available at `/api.php` but `/w/api.php` returns a 200... but without delivering the content.

We should harden our `hasVisualEditorApi()` and `checkApiAvailability()`.
