### ISSUE TITLE
Remove mwoffliner module logging from e2e tests

### ISSUE THREAD

**Issue by audiodude** [openzim/mwoffliner#2038]
The logging from the offliner creates a lot of logspam in e2e test logs, making it hard to read and identify failures.

**Comment by triemerge** [comment]
We may just pass `verbose: 'error'` directly to all `mwoffliner.execute(...)` calls in the E2E tests (mainly in `testRenders.ts`, plus direct calls in `extra`, `forceRender`, and `javaScript`). This cleans up the E2E logs without affecting unit tests. Happy to open a PR if that sounds good.

**Comment by benoit74** [comment]
I don't think this will be sufficient because we will still have few libzim logs which will make the thing even harder to understand, because we will end-up with a succession of these lines:

```
Resolve redirect
set index
```

I think that a first improvement could be to only have normal logs instead of the very verbose logs we currently have.

Instead of:

```
  console.warn
    [warn] [2026-04-02T12:38:43.972Z] Unknown JS module [ext.tmh.player.dialog] removed

      16 | const doLog = (type: LogLevel, args: any[]) => {
      17 |   if (isVerbose(type)) {
    > 18 |     console[type](`[${type}] [${getTs()}]`, ...args)
         |                  ^
      19 |   }
      20 | }
      21 |

      at doLog (src/Logger.ts:18:18)
      at Module.warn (src/Logger.ts:39:3)
      at src/mwoffliner.lib.ts:511:25
          at Set.forEach (<anonymous>)
      at doDump (src/mwoffliner.lib.ts:507:28)
      at Module.execute (src/mwoffliner.lib.ts:398:7)
      at Object.<anonymous> (test/e2e/javaScript.e2e.test.ts:199:22)

  console.log
    [log] [2026-04-02T12:38:43.973Z] Found [26] js module dependencies

      at doLog (src/Logger.ts:18:18)
```

we should have 

```
    [warn] [2026-04-02T12:38:43.972Z] Unknown JS module [ext.tmh.player.dialog] removed
    [log] [2026-04-02T12:38:43.973Z] Found [26] js module dependencies
```

Is this something feasible? Do you have another idea to capture all logs (not only Node.JS ones)?

**Comment by triemerge** [comment]
Thanks @benoit74 for raising this, I looked into both.

The stack trace noise is because `Logger.ts` uses `console[type]()` which Jest wraps and decorates. I think switching to `process.stderr.write()` should avoid that decoration:

```diff
+import { format } from 'util'

 const doLog = (type: LogLevel, args: any[]) => {
   if (isVerbose(type)) {
-    console[type](`[${type}] [${getTs()}]`, ...args)
+    process.stderr.write(format(`[${type}] [${getTs()}]`, ...args) + '\n')
   }
 }
```

This does move `info`/`log` from stdout to stderr though, so worth discussing whether that's acceptable. Logger unit tests spy on `console` methods so those would need updating too.

For the libzim native logs, `@openzim/libzim` exposes `Creator.configVerbose(bool)` which we never call, so i think we can wire it into the Creator chain in `mwoffliner.lib.ts`:

```diff
-    const zimCreator = new Creator().configCompression(Compression.Zstd)
+    const zimCreator = new Creator()
+      .configVerbose(verbose === 'info' || verbose === true)
+      .configCompression(Compression.Zstd)
```

Looking at [creator.cpp](https://github.com/openzim/libzim/blob/main/src/writer/creator.cpp), libzim has two logging macros: `TINFO` (gated by the verbose flag, used for progress/timing lines) and `INFO` (always prints to stdout). Some lines like `set index` and `Resolve redirect` use `INFO`, so `configVerbose(false)` would reduce the progress noise but not fully silence those. Fully suppressing them would likely need a change upstream in libzim.

Still, between `process.stderr.write`, `configVerbose`, and `verbose: 'error'` in e2e calls, i think this gets us most of the way. 

WDYT?

**Comment by benoit74** [comment]
You're right, small amendments:
- I would prefer all logs go to STDOUT instead of all to STDERR: this is already what most scrapers do, and it seems to be a convention to reserve STDERR for errors ; I'm fine if errors and warnings goes in STDOUT
- Configuring libzim verbosity based on scraper verbosity is indeed long overdue ... but this will only produce more logs, not less
- We should probably systematically print test case name in the logs as well so that we have clearer logs as well thanks to this separator

Please propose a PR
