### ISSUE TITLE
Error: Zim Creator being destroyed when fetching one article

### ISSUE THREAD

**Issue by audiodude** [openzim/mwoffliner#2054]
It seems this might be a race condition, where article data is being added after mwoffliner thinks ZIM creation is finished.

Command:

```
node lib/cli.js --webp --mwUrl=https://ca.wikipedia.org/ --format=nodet,nopic:mini --format=nopic:nopic -- \ 
format=novid:maxi --osTmpDir=/dev/shm --adminEmail=contact@kiwix.org --customZimTitle=Viquipèdia -- \
outputDirectory=/tmp/output --customZimFavicon=https://drive.farm.openzim.org/wikipedia_all/favicon-48x48.png \ 
--customZimDescription='versió fora de línia de Wikipedia en català' --publisher=openZIM --articleList=ca_one.txt \
--verbose=info
```

Stack Trace:

```
[warn] [2024-07-07T14:29:46.052Z] Couldn't find strings file for [ca]
[log] [2024-07-07T14:29:46.052Z] Doing dump
[log] [2024-07-07T14:29:46.052Z] Writing zim to [/tmp/output/wikipedia_ca_ca_one_maxi_2024-07.zim]
[info] [2024-07-07T14:29:46.109Z] Finding stylesheets to download
[info] [2024-07-07T14:29:46.109Z] Downloading [https://ca.wikipedia.org/wiki/]
[log] [2024-07-07T14:29:46.128Z] Exiting with code [1]
[log] [2024-07-07T14:29:46.128Z] Deleting temporary directory [/dev/shm/mwoffliner-1720362582750]
/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:108
                            throw new Error("This Creator has been destroyed");
                                  ^

Error: This Creator has been destroyed
    at ZimCreator.<anonymous> (/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:108:35)
    at step (/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:52:23)
    at Object.next (/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:33:53)
    at /home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:27:71
    at new Promise (<anonymous>)
    at __awaiter (/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:23:12)
    at ZimCreator.addArticle (/home/tmoney/code/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:103:16)
    at importPolyfillModules (file:///home/tmoney/code/mwoffliner/lib/util/dump.js:178:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.20.3
```

**Comment by audiodude** [comment]
[log.txt](https://github.com/user-attachments/files/16119693/log.txt)
