### ISSUE TITLE
Mwoffliner fails always with mwurl is not valid

### ISSUE THREAD

**Issue by nish2482** [openzim/mwoffliner#2099]
I am trying to run my mwoffliner for my wiki at path http://10.156.40.44/vascular_wiki and i get the error mwurl is invalid  , even though i am able view my wiki at  http://10.156.40.44/vascular_wiki .

attaching the output logs

docker run --volume=$(pwd)/out:/out  -ti ghcr.io/openzim/mwoffliner:dev  mwoffliner --mwUrl=http://10.156.40.44 --adminEmail=foo@bar.net --mwWikiPath=/vascular_wiki --insecure  --mwActionApiPath=http://10.156.40.44/vascular_wiki/api.php

starting redis-server in the background…
[error] [2024-11-07T04:44:23.130Z] Failed to run mwoffliner after [0s]: {
        "stack": "Error: mwUrl [http://10.156.40.44] is not valid.\n    at file:///tmp/mwoffliner/lib/sanitize-argument.js:134:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async sanitize_mwUrl (file:///tmp/mwoffliner/lib/sanitize-argument.js:133:5)\n    at async sanitize_all (file:///tmp/mwoffliner/lib/sanitize-argument.js:55:5)",
        "message": "mwUrl [http://10.156.40.44] is not valid."
}
[error] [2024-11-07T04:44:23.132Z]

Also tried this way as well

[iresolve@iresolve-app1-us-east-1 ~]$ sudo docker run --volume=$(pwd)/out:/out  -ti ghcr.io/openzim/mwoffliner  mwoffliner --mwUrl=https://10.156.40.44 --adminEmail=foo@bar.net --mwWikiPath=/vascular_wiki  --mwApiPath=https://10.156.40.44/vascular_wiki/api.php
starting redis-server in the background…
(node:13) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[error] [2024-11-07T04:52:37.332Z] Failed to run mwoffliner after [0s]: {
        "stack": "Error: mwUrl [https://10.156.40.44] is not valid.\n    at file:///tmp/mwoffliner/lib/sanitize-argument.js:103:15\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async sanitize_mwUrl (file:///tmp/mwoffliner/lib/sanitize-argument.js:102:5)\n    at async sanitize_all (file:///tmp/mwoffliner/lib/sanitize-argument.js:54:5)",
        "message": "mwUrl [https://10.156.40.44] is not valid."
}
[error] [2024-11-07T04:52:37.333Z]

**********

mwUrl [https://10.156.40.44] is not valid.

**********

**Comment by kelson42** [comment]
@nish2482 Thank you for your bug report and sorry to come back to you so late.

Once think which is wrong is ` --mwActionApiPath` which should not be a full URL, but only the path. Here it might be `/api.php`

But since the time you have reported this issue we have done important changes to MWoffliner and it would be better to give a new attempt and tell us if it works and what is the log otherwise. Would you be able to do so?

**Comment by kelson42** [comment]
@nish2482 Claoing for the moment but issue can be reopen any time. I would reall like to know if it works now.
