### ISSUE TITLE
Make a ZIM of Klexikon.de

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#21]
They do not seem to use the visual editor, this problem should be fixed first.

**Comment by kelson42** [comment]
Here was my command:
```
mwoffliner --mwApiPath="api.php" --mwUrl="https://klexikon.zum.de/" --adminEmail="kelson@kiwix.com" --localParsoid --verbose
```

and I got the following error
```
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/watch-icon-loading.gif
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/user-icon.png
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/watch-icons.png
Executing command : pngquant --verbose --strip --nofs --force --ext=".xd4i9.png" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.xd4i9.png"; fi
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/note.png
Saving favicon.png...
Downloading https://klexikon.zum.de/api.php?action=query&meta=siteinfo&format=json...
Executing command : gifsicle --verbose --colors 64 -O3 "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif" -o "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif" "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.ncska.gif"; fi
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/klexikon_de_all_2018-09/s/warning.gif
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:150:11)
    at Object.urlParse [as parse] (url.js:144:13)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2083:29
    at async.retry (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:176:7)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17

```

**Comment by kelson42** [comment]
This issue was moved to openzim/zim-requests#100
