### ISSUE TITLE
404 error gives TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by godane** [openzim/mwoffliner#211]
I'm trying figure out how to make a zim file of wikinews. It was taking too long and failing so i make list of one article to see if builds. 
> Next_seasons_Coppa_Italia_football_tournament_adopts_new_format.html

Can anyone here tell me what i'm doing wrong?

```
root@debian:/run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs# mwoffliner --mwUrl=http://en.wikinews.org/ --mwApiPath="/w/api.php" --adminEmail=slaxemulator@gmail.com --resume --verbose --keepHtml --speed 0.5 --withZimFullTextIndex --format nopic --localParsoid --articleList list.txt
Starting Parsoid
info loading ...
info ready on :8000
Parsoid Started Successfully
Getting text direction...
Downloading http://en.wikinews.org/wiki/...
Text direction is ltr
Getting web site name...
Downloading http://en.wikinews.org//w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc...
Getting sub-title...
Downloading http://en.wikinews.org/wiki/...
Downloading http://en.wikinews.org//w/api.php?action=query&meta=siteinfo&siprop=namespaces|namespacealiases&format=json...
Creating base directories...
Preparing cache...
Downloading http://en.wikinews.org//w/api.php?action=query&redirects&format=json&prop=revisions|coordinates&titles=Next_seasons_Coppa_Italia_football_tournament_adopts_new_format.html...
Article Next_seasons_Coppa_Italia_football_tournament_adopts_new_format.html is not available on this wiki.
List of article ids to mirror completed
All redirect ids retrieve successfuly.
Reset redirects cache file (or create it)
Caching redirects...
All redirects were cached successfuly.
Starting a new dump...
Creating sub directories at "/run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/"...
Dumping stylesheets...
Cache hit for http://en.wikinews.org/wiki/ (/run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/cac/wikinews_en/0fd736743f23367e8bfe)
Downloading CSS from http://en.wikinews.org/w/load.php?debug=false&lang=en&modules=ext.dismissableSiteNotice.styles|ext.flaggedRevs.basic|ext.inputBox.styles|ext.uls.interlanguage|ext.visualEditor.desktopArticleTarget.noscript|ext.wikimediaBadges|mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.interface|mediawiki.ui.button%2Ccheckbox%2Cinput|skins.vector.styles|wikibase.client.init&only=styles&skin=vector
Downloading http://en.wikinews.org/w/load.php?debug=false&lang=en&modules=ext.dismissableSiteNotice.styles|ext.flaggedRevs.basic|ext.inputBox.styles|ext.uls.interlanguage|ext.visualEditor.desktopArticleTarget.noscript|ext.wikimediaBadges|mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.interface|mediawiki.ui.button%2Ccheckbox%2Cinput|skins.vector.styles|wikibase.client.init&only=styles&skin=vector...
Downloading CSS from http://en.wikinews.org/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=vector
Downloading http://en.wikinews.org/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=vector...
Downloading CSS from http://en.wikinews.org/wiki/Mediawiki:offline.css?action=raw
Downloading http://en.wikinews.org/wiki/Mediawiki:offline.css?action=raw...
Downloading http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png at /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/Badge_right_top.png...
Downloading http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png...
Downloading http://upload.wikimedia.org/wikipedia/commons/7/7d/Wikinews_banner_2.png at /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/Wikinews_banner_2.png...
Downloading http://upload.wikimedia.org/wikipedia/commons/7/7d/Wikinews_banner_2.png...
Unable to download content [1] http://en.wikinews.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [1] http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png (statusCode=404).
Unable to download content [2] http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png (statusCode=404).
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_20.png?aac48 at /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/bar_20.png...
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_20.png?aac48...
Unable to download content [2] http://en.wikinews.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Successfuly optimized /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/Wikinews_banner_2.png
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_40.png?ac841 at /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/bar_40.png...
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_40.png?ac841...
Successfuly optimized /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/bar_20.png
Unable to download content [3] http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://upload.wikimedia.org/wikinews/en/5/5a/Badge_right_top.png (statusCode=404).
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_60.png?a06f7 at /run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs/tmp/wikinews_en_list_nopic_2018-03/s/bar_60.png...
Downloading http://en.wikinews.org/w/extensions/FlaggedRevs/frontend/modules/img/bar_60.png?a06f7...
TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:383:11)
    at exports.spawn (child_process.js:496:38)
    at Object.exports.execFile (child_process.js:212:15)
    at exports.exec (child_process.js:142:18)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:567:33
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:651:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
root@debian:/run/initramfs/memory/data/slackware/debootstrap/sources/zimwriterfs# 
```

**Comment by kelson42** [comment]
Please post your article list

**Comment by kelson42** [comment]
```
mwoffliner --verbose --mwUrl=http://en.wikinews.org/ --mwApiPath="/w/api.php" --adminEmail=foobar@kiwix.org --verbose --keepHtml --withZimFullTextIndex --format=nopic --articleList=list.txt
```
