### ISSUE TITLE
Unable to make ZIM file of en.wikibooks.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#264]
```
mwoffliner --format=novid --format=nopic --withZimFullTextIndex --deflateTmpHtml --verbose --adminEmail=contact@kddiwix.org --skipCacheCleaning --skipHtmlCache --tmpDirectory=/dev/shm/ --mwUrl="https://en.wikibooks.org/" $WIKIBOOKS_ARGS --addNamespaces="112"
```
gives
```
Getting (desktop) article from https://en.wikibooks.org/w/api.php?action=visualeditor&format=json&paction=parse&page=C_Sharp_Programming%2FKeywords%2Fstatic&oldid=3227488
Downloading https://en.wikibooks.org/w/api.php?action=visualeditor&format=json&paction=parse&page=C_Sharp_Programming%2FKeywords%2Fstatic&oldid=3227488...
Saving article C_Sharp_Programming/Keywords/try...
Js dependencies of C_Sharp_Programming/Keywords/int : startup,jquery,mediawiki,site
Css dependencies of C_Sharp_Programming/Keywords/int : ext.pygments
created dep jsConfigVars.js for article C_Sharp_Programming/Keywords/int
Js dependencies of C_Sharp_Programming/Keywords/catch : startup,jquery,mediawiki,site
Css dependencies of C_Sharp_Programming/Keywords/catch : ext.pygments
created dep jsConfigVars.js for article C_Sharp_Programming/Keywords/catch
Treating and saving article C_Sharp_Programming/Keywords/using at /dev/shm//wikibooks_en_all_novid_2018-03/C_Sharp_Programming_Keywords_using.html...
Dumped successfully article C_Sharp_Programming/Keywords/try
Getting (desktop) article from https://en.wikibooks.org/w/api.php?action=visualeditor&format=json&paction=parse&page=C_Sharp_Programming%2FKeywords%2Fstring&oldid=3227504
Downloading https://en.wikibooks.org/w/api.php?action=visualeditor&format=json&paction=parse&page=C_Sharp_Programming%2FKeywords%2Fstring&oldid=3227504...
Treating and saving article C_Sharp_Programming/Keywords/namespace at /dev/shm//wikibooks_en_all_novid_2018-03/C_Sharp_Programming_Keywords_namespace.html...
Treating and saving article C_Sharp_Programming/Keywords/static at /dev/shm//wikibooks_en_all_novid_2018-03/C_Sharp_Programming_Keywords_static.html...
Js dependencies of Calculus/Print_version : startup,jquery,mediawiki,site,ext.math.scripts,ext.cite.a11y
Css dependencies of Calculus/Print_version : ext.math.scripts,ext.cite.a11y,ext.math.styles,ext.cite.styles
created dep jsConfigVars.js for article Calculus/Print_version
TypeError: Cannot read property 'innerHTML' of undefined
    at setFooter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1317:56)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at Immediate.iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
```

**Comment by kelson42** [comment]
This seems to be an upstream problem, I have open a bug here https://phabricator.wikimedia.org/T191139

**Comment by kelson42** [comment]
@ISNIT0 Do you think you could have time to look at that one? The problem did not vanished and each month the scrapping runs into trouble because of this.

**Comment by ISNIT0** [comment]
What is the value of `WIKIBOOKS_ARGS`? Also, I found that using multiple `--formats` doesn't actually pass multiple values to the code, I used `--formats=nopic,nozim` instead

**Comment by kelson42** [comment]
```
#!/bin/sh

# Allows to write core file
ulimit -c unlimited

ZIM2INDEX=/srv/upload/zim2index/
ARGS="--withZimFullTextIndex --deflateTmpHtml --verbose --adminEmail=contact@kiwix.org --skipCacheCleaning --skipHtmlCache --tmpDirectory=/dev/shm/"
MWOFFLINER="mwoffliner --format=novid --format=nopic $ARGS"
MWOFFLINER_MOBILE="$MWOFFLINER --mobileLayout"
MWMATRIXOFFLINER="mwmatrixoffliner --mwUrl=https://meta.wikimedia.org/ $ARGS"
MWMATRIXOFFLINER=_MOBILE="$MWMATRIXOFFLINER --mobileLayout"

# Wikibooks
WIKIBOOKS_ARGS="--outputDirectory=$ZIM2INDEX/wikibooks/"
$MWOFFLINER --mwUrl="https://en.wikibooks.org/" $WIKIBOOKS_ARGS --addNamespaces="112"
```

**Comment by ISNIT0** [comment]
I can't reproduce this locally - do we think the issue has gone now?

**Comment by kelson42** [comment]
@ISNIT0 You probably right, currently running a test. I'll reopen it if it still fails.
