### ISSUE TITLE
Scrapping he.wikisource.org is generating a lot of errors

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#276]
```
Saving article ��ר_� saving article ��ר_�liner/lib/mwoffliner.lib.js:2003:12)
    at treatMedias (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:884:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Js dependencies of ��ר_�/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Saving article ��ר_�%9D_%D7%A8%D7%A6%D7%94/817009
Downloading https://he.wikisource.org/api/rest_v1/page/html/��ר_�.lib.js:2030:22)
    at getMediaUrl (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2003:12)
    at treatMedias (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:884:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Js dependencies of ��ר_�/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Saving article ��ר_�Utils.js:27:14)
    at getMediaBase (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2030:22)
    at getMediaUrl (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2003:12)
    at treatMedias (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:884:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Dumped successfully article ��ר_�/api/rest_v1/page/html/��ר_�ules/mwoffliner/lib/mwoffliner.lib.js:884:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Saving article ��ר_�al/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Dumped successfully article ��ר_�t_v1/page/html/%D7%98%D7%95%D7%A8_%D7%90%D7%95%D7%A8%D7%97_%D7%97%D7%99%D7%99%D7%9D_%D7%A9/731554
Downloading https://he.wikisource.org/api/rest_v1/page/html/��ר_�r/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Js dependencies of ��ר_�/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
Treating and saving article ��ר_�03
Downloading https://he.wikisource.org/api/rest_v1/page/html/��ר_�usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
```

**Comment by kelson42** [comment]
@ISNIT0 @automactic I strongly suspect this errors doe not occur anymore. Any feedback would be welcome.

**Comment by automactic** [comment]
Still failing with 1.8.4, but with the error in #698
