### ISSUE TITLE
Unable to scrape dandwiki.com

### ISSUE THREAD

**Issue by fattredd** [openzim/mwoffliner#347]
Running in the most recent docker image. The script runs for about 4 hours before it (seems like) it finishes downloading pages. I think this is at the transition from downloading to building the articles.

Here's the command I'm running:
`mwoffliner --redis="redis://redis" --mwUrl="https://www.dandwiki.com/" --adminEmail=admin@kiwix.com --localParsoid --verbose`

Looks like a replace() call is getting called on an empty string. I've been trying to figure out why for a while now. Any ideas?

```
. . .
Downloading https://www.dandwiki.com/w/api.php?action=query&meta=siteinfo&format=json...
Successfuly optimized /root/tmp/dandwiki_en_all_2018-07/s/Pathfinder_PFSRD_Banner.jpg
Successfuly optimized /root/tmp/dandwiki_en_all_2018-07/s/OGC_Banner.jpg
Downloading http://www.dandwiki.com/w/images/3/3f/D%26D_Wiki_Logo_-_final.svg at /root/tmp/dandwiki_en_all_2018-07/favicon.png...
Downloading http://www.dandwiki.com/w/images/3/3f/D%26D_Wiki_Logo_-_final.svg...
Successfuly optimized /root/tmp/dandwiki_en_all_2018-07/favicon.png
Successfuly optimized /root/tmp/dandwiki_en_all_2018-07/favicon.png
Create main page redirection...
Saving articles...
Getting (desktop) article from http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/Main_Page?oldid=1028349
Getting (desktop) article from http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/MediaWiki_talk%3ACopyrightpage?oldid=85398
Downloading http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/Main_Page?oldid=1028349...
Downloading http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/MediaWiki_talk%3ACopyrightpage?oldid=85398...
warn/api/main { logType: 'warn/api/main',
  wiki: 'wiki$0',
  title: 'Main_Page',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (admin@kiwix.com)',
  msg: 'Config Request Unrecognized parameter: \'rawcontinue\'',
  longMsg: 'Config Request\nUnrecognized parameter: \'rawcontinue\'' }
warn/api/siteinfo { logType: 'warn/api/siteinfo',
  wiki: 'wiki$0',
  title: 'Main_Page',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (admin@kiwix.com)',
  msg: 'Config Request Unrecognized value for parameter \'siprop\': languagevariants',
  longMsg: 'Config Request\nUnrecognized value for parameter \'siprop\': languagevariants' }
warn/api/main { logType: 'warn/api/main',
  wiki: 'wiki$0',
  title: 'MediaWiki_talk:Copyrightpage',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (admin@kiwix.com)',
  msg: 'Config Request Unrecognized parameter: \'rawcontinue\'',
  longMsg: 'Config Request\nUnrecognized parameter: \'rawcontinue\'' }

. . .
. . .

warn/api/main { logType: 'warn/api/main',
  wiki: 'wiki$0',
  title: 'Main_Page',
  oldId: 1028349,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (admin@kiwix.com)',
  msg: 'Template Expansion Unrecognized parameters: \'prop\', \'revid\'',
  longMsg: 'Template Expansion\nUnrecognized parameters: \'prop\', \'revid\'' }
Js dependencies of MediaWiki_talk:Copyrightpage : startup,jquery,mediawiki,site,,
Css dependencies of MediaWiki_talk:Copyrightpage : ,
Error fetching api.php for https://www.dandwiki.com/w/api.php?action=parse&format=json&page=MediaWiki_talk%3ACopyrightpage&prop=modules%7Cjsconfigvars%7Cheadhtml TypeError: Cannot read property 'replace' of undefined
TypeError: Cannot read property 'replace' of undefined
    at jsPath (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:283:48)
    at genHeaderScript (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:289:30)
    at domino.createDocument.replace.replace.jsDependenciesList.length.jsDependenciesList.map.oneJsDep (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1294:52)
    at Array.map (native)
    at setFooter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1294:36)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at Immediate.iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
```

**Comment by kelson42** [comment]
Trying again with the last version of mwoffliner and got that error
```
Caching https://www.dandwiki.com/wiki/ at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/d020425407cfbaa06f5e...
Downloading CSS from http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=ext.smw.style|ext.smw.tooltip.styles&only=styles&skin=sledged
Downloading http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=ext.smw.style|ext.smw.tooltip.styles&only=styles&skin=sledged...
Downloading CSS from http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.content.externallinks|mediawiki.skinning.interface|skins.sledged.styles&only=styles&skin=sledged
Downloading http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=mediawiki.legacy.commonPrint%2Cshared|mediawiki.sectionAnchor|mediawiki.skinning.content.externallinks|mediawiki.skinning.interface|skins.sledged.styles&only=styles&skin=sledged...
Downloading CSS from http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=sledged
Downloading http://www.dandwiki.com/w/load.php?debug=false&lang=en&modules=site.styles&only=styles&skin=sledged...
Downloading CSS from https://www.dandwiki.com/wiki/Mediawiki:offline.css?action=raw
Downloading https://www.dandwiki.com/wiki/Mediawiki:offline.css?action=raw...
Downloading http://www.dandwiki.com/w/images/searchgray_iconsmall.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/searchgray_iconsmall.png...
Downloading http://www.dandwiki.com/w/images/searchgray_iconsmall.png...
Downloading http://www.dandwiki.com/w/images/search_icon.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/search_icon.png...
Downloading http://www.dandwiki.com/w/images/search_icon.png...
Downloading http://www.dandwiki.com/w/images/browse_iconsmall.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/browse_iconsmall.png...
Downloading http://www.dandwiki.com/w/images/browse_iconsmall.png...
Downloading http://www.dandwiki.com/w/images/browse_icon.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/browse_icon.png...
Downloading http://www.dandwiki.com/w/images/browse_icon.png...
Downloading http://www.dandwiki.com/w/images/world.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/world.png...
Downloading http://www.dandwiki.com/w/images/world.png...
Downloading http://www.dandwiki.com/w/images/rdf_flyer.18.gif at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/rdf_flyer.18.gif...
Downloading http://www.dandwiki.com/w/images/rdf_flyer.18.gif...
Downloading http://www.dandwiki.com/w/world.png at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/world.png...
Downloading http://www.dandwiki.com/w/world.png...
Downloading http://www.dandwiki.com/w/rdf_flyer.18.gif at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/rdf_flyer.18.gif...
Downloading http://www.dandwiki.com/w/rdf_flyer.18.gif...
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type object
    at assertPath (path.js:39:11)
    at Object.basename (path.js:1299:5)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1611:41
    at async.retry (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:176:7)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17
```

**Comment by kelson42** [comment]
Still dying

```
Downloading https://www.dandwiki.com/w/api.php?action=query&meta=siteinfo&format=json...
Executing command : gifsicle --verbose --colors 64 -O3 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.gif" -o "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.inn99.gif" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.inn99.gif") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.gif") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.inn99.gif" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.gif"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.inn99.gif"; fi
Executing command : pngquant --verbose --strip --nofs --force --ext=".e6rl0.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.e6rl0.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.e6rl0.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.e6rl0.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.e6rl0.png"; fi
Executing command : gifsicle --verbose --colors 64 -O3 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.gif" -o "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.0t6dp.gif" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.0t6dp.gif") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.gif") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.0t6dp.gif" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.gif"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.0t6dp.gif"; fi
Executing command : pngquant --verbose --strip --nofs --force --ext=".m0w8t.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.m0w8t.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.m0w8t.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.m0w8t.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.m0w8t.png"; fi
Executing command : gifsicle --verbose --colors 64 -O3 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.gif" -o "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.e3eik.gif" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.e3eik.gif") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.gif") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.e3eik.gif" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.gif"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.e3eik.gif"; fi
Executing command : pngquant --verbose --strip --nofs --force --ext=".x42b1.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.x42b1.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.x42b1.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.x42b1.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.x42b1.png"; fi
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/file_icon.gif
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/user.gif
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/document.png
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/discussionitem_icon.gif
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/news_icon.png
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/audio.png
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/s/video.png
Downloading http://www.dandwiki.com/w/images/3/3f/D%26D_Wiki_Logo_-_final.svg at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.png...
Downloading http://www.dandwiki.com/w/images/3/3f/D%26D_Wiki_Logo_-_final.svg...
Executing command : pngquant --verbose --strip --nofs --force --ext=".adrg2.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.adrg2.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.adrg2.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.adrg2.png" "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/favicon.adrg2.png"; fi
Executing command : undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:394:3)
    at spawn (child_process.js:527:38)
    at Object.execFile (child_process.js:216:15)
    at exec (child_process.js:147:18)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:470:11
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:651:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29

```

**Comment by kelson42** [comment]
The root cause of the problem is that the Mediawiki icon is in SVG format https://www.dandwiki.com/w/images/3/3f/D%26D_Wiki_Logo_-_final.svg and it should be PNG. Here we should at least stop and print an error OR (better) convert the potential SVG/JPEG to a PNG.

On the top of it, the retry process to optimize PNG should not retry with `undefined` as a string, it should instead just ignore, print an error and continue.

**Comment by kelson42** [comment]
Last run died with an other error:

```
Caching http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/Greater_Ameliorated_Burden_(3.5e_Feat)?oldid=547130 at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/24fc199f9a5b72131259...
Treating and saving article Greater_Ameliorated_Burden_(3.5e_Feat) at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/Greater_Ameliorated_Burden_(3.5e_Feat).html...
Caching gallery%2FArtistsM%2Fmucha2.jpg at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/m/6b52890f8ba67f0d7603.jpg...
Caching gallery%2FCrane%2Fcrane9.jpg at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/m/a32add466a2d9ebe2ace.jpg...
Unable to create symlink to /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/m/gallery/ArtistsM/mucha2.jpg at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/m/6b52890f8ba67f0d7603.jpg: Error: ENOENT: no such file or directory, symlink '/srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/m/6b52890f8ba67f0d7603.jpg' -> '/srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-09/m/gallery/ArtistsM/mucha2.jpg' true
```

**Comment by ISNIT0** [comment]
Have you seen this happen again on the live server?

**Comment by ISNIT0** [comment]
@kelson42 Have you seen this again?

**Comment by kelson42** [comment]
@ISNIT0 What is the "live server"?

**Comment by ISNIT0** [comment]
@kelson42 I mean - is this still happening with the latest master branch?

**Comment by kelson42** [comment]
@ISNIT0 I just have restarted a new scrapping process

**Comment by ISNIT0** [comment]
Waiting on #425

**Comment by kelson42** [comment]
@ISNIT0 Still does not scrappe properly:

```
mwoffliner --mwUrl="https://www.dandwiki.com/" --adminEmail=kelson@kiwix.org --localParsoid --verbose
```

...

```
info { logType: 'info',
  wiki: 'wiki$0',
  title: 'Ætheric_Aura_(5e_Spell)',
  oldId: 1102937,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.org)',
  msg: 'completed parsing in 641 ms',
  longMsg: 'completed parsing in 641 ms' }
Saving article Ætheric_Ballista_(5e_Spell)...
Successfully dumped article Ætheric_Ballista_(5e_Spell)
Saving article Ætherstorm_(5e_Spell)...
Caching http://localhost:8000/www.dandwiki.com/v3/page/pagebundle/%C3%86theric_Aura_(5e_Spell)?oldid=1102937 at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/b89d0e7983c1b27e1bcd...
Successfully dumped article Ætherstorm_(5e_Spell)
Treating and saving article Ætheric_Aura_(5e_Spell) at /srv/kiwix-maintenance/mwoffliner/tmp/dandwiki_en_all_2018-11/Ætheric_Aura_(5e_Spell).html...
Js dependencies of Ætheric_Aura_(5e_Spell) : startup,jquery,mediawiki,site,ext.smw.style,ext.smw.tooltips
Css dependencies of Ætheric_Aura_(5e_Spell) : ext.smw.style,ext.smw.tooltips
Getting [js] module [startup]
Getting [js] module [jquery]
Getting [js] module [mediawiki]
Getting [js] module [site]
Getting [js] module [ext.smw.style]
Getting [js] module [ext.smw.tooltips]
Getting [css] module [ext.smw.style]
Getting [css] module [ext.smw.tooltips]
created dep jsConfigVars.js for article Ætheric_Aura_(5e_Spell)
Saving article Ætheric_Aura_(5e_Spell)...
Successfully dumped article Ætheric_Aura_(5e_Spell)
All articles were retrieved and saved.
0 images still to be downloaded.
Absolutely unable to retrieve async. URL: Unable to download content [3] http://media.giantbomb.com/uploads/1/15399/671423-ruto2.jpg (request error: Error: getaddrinfo ENOTFOUND media.giantbomb.com media.giantbomb.com:80 ).
Caching 671423-ruto2.jpg at /srv/kiwix-maintenance/mwoffliner/cac/dandwiki_en/m/e9a202fc855f89e2d8a7.jpg...


```
... and then stuck!

**Comment by ISNIT0** [comment]
I'm unable to reproduce this so far, I'm going to try and scrape the whole site again, it'll take a while

**Comment by ISNIT0** [comment]
After fixing the scraping on a local branch, I'm finding some WikiText source is returned by Parsoid.
I've created an issue here: https://phabricator.wikimedia.org/T210509

I'll open a PR for the scraping fixes so far anyway.

**Comment by kelson42** [comment]
I re-open the ticket because the problem is not fixed and I'm sure this is not the only one problem:

I see this kind of warnings:
```
[log] [2019-07-10T11:12:55.758Z] Got [500] articles from namespace [0]
[info] [2019-07-10T11:12:55.758Z] Getting JSON from [https://www.dandwiki.com/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0%7C1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7C10%7C11%7C12%7C13%7C14%7C15%7C100%7C101%7C102%7C103%7C104%7C105%7C106%7C107%7C110%7C111%7C152%7C153%7C158%7C159%7C170%7C171%7C180%7C181%7C190%7C191%7C200%7C201%7C-2%7C-1&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=Necrorm_(3.5e_Race)]
[warn] [2019-07-10T11:12:57.108Z] Got warning from MW Query {
	"redirects": {
		"*": "Unrecognized values for parameter \"rdnamespace\": -2, -1."
	},
	"query": {
		"*": "Unrecognized value for parameter \"prop\": pageimages."
	}
}
[log] [2019-07-10T11:12:57.171Z] Got [500] articles from namespace [0]
[info] [2019-07-10T11:12:57.172Z] Getting JSON from [https://www.dandwiki.com/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0%7C1%7C2%7C3%7C4%7C5%7C6%7C7%7C8%7C9%7C10%7C11%7C12%7C13%7C14%7C15%7C100%7C101%7C102%7C103%7C104%7C105%7C106%7C107%7C110%7C111%7C152%7C153%7C158%7C159%7C170%7C171%7C180%7C181%7C190%7C191%7C200%7C201%7C-2%7C-1&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=Nymph]
[warn] [2019-07-10T11:12:58.524Z] Got warning from MW Query {
	"redirects": {
		"*": "Unrecognized values for parameter \"rdnamespace\": -2, -1."
	},
	"query": {
		"*": "Unrecognized value for parameter \"prop\": pageimages."
	}
}
```

**Comment by kelson42** [comment]
Have created a recipe https://farm.openzim.org/recipes/dandwiki/

**Comment by kelson42** [comment]
Works now https://farm.openzim.org/recipes/dandwiki
