### ISSUE TITLE
Image optimisation seems to be unstable with nodejs 10.6(.0)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#351]
I have installed the last version of nodejs and it seems unstable now (around the picture optimisation).

Here and example of reproducable crash
```
./bin/mwoffliner.script.js --mwUrl="https://www.dandwiki.com/" --adminEmail=admin@kiwix.com --localParsoid --verbose --articleList=articles
```

With
```
$ cat articles 
MediaWiki_talk:Copyrightpage
```

gives
```
.png" && if [ $(stat -c%s "/home/kelson/code/mwoffliner/tmp/dandwiki_en_articles_2018-07/s/video.dkqs8.png") -lt $(stat -c%s "/home/kelson/code/mwoffliner/tmp/dandwiki_en_articles_2018-07/s/video.png") ]; then mv "/home/kelson/code/mwoffliner/tmp/dandwiki_en_articles_2018-07/s/video.dkqs8.png" "/home/kelson/code/mwoffliner/tmp/dandwiki_en_articles_2018-07/s/video.png"; else rm "/home/kelson/code/mwoffliner/tmp/dandwiki_en_articles_2018-07/s/video.dkqs8.png"; fi
pngquant: unrecognized option '--strip'
)
Executing command : undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at normalizeSpawnArguments (child_process.js:397:11)
    at spawn (child_process.js:522:38)
    at Object.execFile (child_process.js:218:15)
    at exec (child_process.js:148:18)
    at /home/kelson/code/mwoffliner/lib/mwoffliner.lib.js:467:11
    at /home/kelson/code/mwoffliner/node_modules/async/lib/async.js:651:21
    at /home/kelson/code/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/home/kelson/code/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /home/kelson/code/mwoffliner/node_modules/async/lib/async.js:274:29
    at /home/kelson/code/mwoffliner/node_modules/async/lib/async.js:44:16
```

**Comment by kelson42** [comment]
Might be fixed, we should try

**Comment by kelson42** [comment]
Seems to not die anymore here.
