### ISSUE TITLE
Create a ZIM for Art of Problem Solving Wiki

### ISSUE THREAD

**Issue by Maths01** [openzim/mwoffliner#354]
Art of Problem Solving Wiki provides many useful articles on mathematical theorems , problems , competitions ,... etc and it is based on WikiMedia 
Main page:
https://artofproblemsolving.com/wiki/index.php?title=Main_Page

**Comment by kelson42** [comment]
@Maths01 Might be doable.. but the licensing is really not clear :(

**Comment by Maths01** [comment]
I'll be grateful if you can do it :)

**Comment by kelson42** [comment]
@ISNIT0 I tried but the process failed with the folloging error:
```
mwoffliner --mwUrl="https://artofproblemsolving.com/" --mwApiPath="/wiki/api.php" --adminEmail="kelson@kiwix.com" --localParsoid --verbose

...

Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/file_icon.gif (response code: 404).
Unable to download content [2] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/discussionitem_icon.gif (response code: 404).
Unable to download content [3] http://artofproblemsolving.com/assets/css/"//assets.artofproblemsolving.com/images/aops-logo.svg" (response code: 404).
Unable to download content [2] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/audio.png (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://artofproblemsolving.com/assets/css/"//assets.artofproblemsolving.com/images/aops-logo.svg" (response code: 404).
Unable to download content [2] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/video.png (response code: 404).
Unable to download content [2] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/user.gif (response code: 404).
Unable to download content [2] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/document.png (response code: 404).
Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/discussionitem_icon.gif (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/discussionitem_icon.gif (response code: 404).
Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/audio.png (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/audio.png (response code: 404).
Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/user.gif (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/user.gif (response code: 404).
Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/document.png (response code: 404).
Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/video.png (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/document.png (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://wiki-5.artofproblemsolving.com/wiki/skins/aops/video.png (response code: 404).
Saving favicon.png...
Downloading https://artofproblemsolving.com//wiki/api.php?action=query&meta=siteinfo&format=json...
Successfuly optimized /srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/s/index-ba-footer-2.png
Downloading http: at /srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png...
Downloading http:...
Executing command : pngquant --verbose --strip --nofs --force --ext=".w9p83.png" "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.w9p83.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.w9p83.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.w9p83.png" "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.w9p83.png"; fi
Executing command : pngquant --verbose --strip --nofs --force --ext=".i91fe.png" "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png" && advdef -q -z -4 -i 5 "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.i91fe.png" && if [ $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.i91fe.png") -lt $(stat -c%s "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png") ]; then mv "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.i91fe.png" "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.png"; else rm "/srv/kiwix-maintenance/mwoffliner/tmp/artofproblemsolving_en_all_2018-09/favicon.i91fe.png"; fi
Executing command : undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:394:3)
    at spawn (child_process.js:527:38)
    at Object.execFile (child_process.js:216:15)
    at exec (child_process.js:147:18)
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:470:11
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:651:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:274:29
```

**Comment by ISNIT0** [comment]
This looks like a similar issue to #363

**Comment by ISNIT0** [comment]
This is the same issue as #363
