### ISSUE TITLE
make a zim of wikiwel.com

### ISSUE THREAD

**Issue by Popolechien** [openzim/mwoffliner#368]
Permission was granted via email.

**Comment by kelson42** [comment]
Tried but got that error
```
Downloading http://wikiwel.com/wikihealing/images/thumb/b/b8/Google-Plus.png/39px-Google-Plus.png at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/f225934371222aa9458f.png...
Downloading http://wikiwel.com/wikihealing/images/thumb/b/b8/Google-Plus.png/39px-Google-Plus.png...
Downloading http://wikiwel.com/wikihealing/images/thumb/f/f7/Twitter.png/35px-Twitter.png at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/ebb8ed9a8ce85bf16df1.png...
Downloading http://wikiwel.com/wikihealing/images/thumb/f/f7/Twitter.png/35px-Twitter.png...
Downloading http://wikiwel.com/wikihealing/images/thumb/8/89/FacebookLogo.gif/39px-FacebookLogo.gif at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/8f4e158adf8f19198ac2.gif...
Downloading http://wikiwel.com/wikihealing/images/thumb/8/89/FacebookLogo.gif/39px-FacebookLogo.gif...
Downloading http://wikiwel.com/wikihealing/images/thumb/3/30/Echinacea2.jpg/350px-Echinacea2.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/564e17de343ebfddb061.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/3/30/Echinacea2.jpg/350px-Echinacea2.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/e/ef/Chinese-Herbs.jpg/330px-Chinese-Herbs.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/221241aae8b200090a82.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/e/ef/Chinese-Herbs.jpg/330px-Chinese-Herbs.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/5/51/Ayurveda.jpg/330px-Ayurveda.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/1587c917e88613cd2d4e.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/5/51/Ayurveda.jpg/330px-Ayurveda.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/e/e4/Homeopathy.jpg/340px-Homeopathy.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/9f93d4cbe622370a9d73.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/e/e4/Homeopathy.jpg/340px-Homeopathy.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/b/b8/Healthcare.jpg/200px-Healthcare.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/bf4674cc0a2a42ac24c3.jpg...
Downloading http://wikiwel.com/wikihealing/images/thumb/b/b8/Healthcare.jpg/200px-Healthcare.jpg...
Downloading http://wikiwel.com/wikihealing/images/1/1e/TCM.jpg at /srv/kiwix-maintenance/mwoffliner/cac/wikiwel_en/m/282d064ba64403124dbf.jpg...
Downloading http://wikiwel.com/wikihealing/images/1/1e/TCM.jpg...
TypeError: Cannot read property 'replace' of undefined
    at jsPath (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:286:49)
    at genHeaderScript (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:292:30)
    at domino.createDocument.replace.replace.jsDependenciesList.length.jsDependenciesList.map.oneJsDep (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1297:52)
    at Array.map (<anonymous>)
    at setFooter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1297:36)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:1149:20
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:375:13
    at Immediate.iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)

```

**Comment by kelson42** [comment]
I still need to make the ZIM :)

**Comment by kelson42** [comment]
done https://download.kiwix.org/zim/other/wikiwel_en_all_2018-09.zim
