### ISSUE TITLE
Exception by scrapping cyclowiki.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#387]
```
mwoffliner --mwUrl="http://cyclowiki.org" --adminEmail="kelson@kiwix.com" --localParsoid --verbose --customZimFavicon=Cyclowiki.png
```

makes

```
Caching 250px-Колесо-года.jpg at /srv/kiwix-maintenance/mwoffliner/cac/cyclowiki_ru/m/d3ec7fb358f4af4233b6...
warn/api/imageinfo { logType: 'warn/api/imageinfo',
  wiki: 'wiki$0',
  title: '10_декабря',
  oldId: 678465,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Image Info Request Unrecognized value for parameter \'iiprop\': badfile',
  longMsg:
   'Image Info Request\nUnrecognized value for parameter \'iiprop\': badfile' }
warn/api/imageinfo { logType: 'warn/api/imageinfo',
  wiki: 'wiki$0',
  title: '10_декабря',
  oldId: 678465,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Image Info Request Unrecognized value for parameter \'iiprop\': badfile',
  longMsg:
   'Image Info Request\nUnrecognized value for parameter \'iiprop\': badfile' }
warn/api/imageinfo { logType: 'warn/api/imageinfo',
  wiki: 'wiki$0',
  title: '10_декабря',
  oldId: 678465,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Image Info Request Unrecognized value for parameter \'iiprop\': badfile',
  longMsg:
   'Image Info Request\nUnrecognized value for parameter \'iiprop\': badfile' }
warn/api/imageinfo { logType: 'warn/api/imageinfo',
  wiki: 'wiki$0',
  title: '10_декабря',
  oldId: 678465,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Image Info Request Unrecognized value for parameter \'iiprop\': badfile',
  longMsg:
   'Image Info Request\nUnrecognized value for parameter \'iiprop\': badfile' }
warn/api/imageinfo { logType: 'warn/api/imageinfo',
  wiki: 'wiki$0',
  title: '10_декабря',
  oldId: 678465,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Image Info Request Unrecognized value for parameter \'iiprop\': badfile',
  longMsg:
   'Image Info Request\nUnrecognized value for parameter \'iiprop\': badfile' }
Saving article Заглавная_страница...
Dumped successfully article Заглавная_страница
Getting (desktop) article from http://localhost:8000/cyclowiki.org/v3/page/pagebundle/10_%D0%B8%D1%8E%D0%BB%D1%8F?oldid=727572
Downloading http://localhost:8000/cyclowiki.org/v3/page/pagebundle/10_июля?oldid=727572...
Js dependencies of 1-я_улица_Строителей_(Уфа) : startup,jquery,mediawiki,site
Css dependencies of 1-я_улица_Строителей_(Уфа) :
created dep jsConfigVars.js for article 1-я_улица_Строителей_(Уфа)
Downloading http://cyclowiki.org/"./Special:FilePath/Баланово_—_Ново-Александровка.jpg/" at /srv/kiwix-maintenance/mwoffliner/cac/cyclowiki_ru/m/8cd2bc28879618034e71...
Downloading http://cyclowiki.org/"./Special:FilePath/Баланово_—_Ново-Александровка.jpg/"...
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:114:13)
    at Object.request (http.js:41:10)
    at defaultMakeRequest (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:83:37)
    at cb (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:71:57)
    at execute (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:27:23)
    at H.get (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:113:14)
    at async.retry.finished (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:103:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:651:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
```

**Comment by ISNIT0** [comment]
The cause of this issue is that an IMG tag actually has `"` characters in the `src` attribute: `http://cyclowiki.org/"./Special:FilePath/Баланово_—_Ново-Александровка.jpg/"`

This is invalid and in a browser only resolves when the extra quote characters are removed:
`http://cyclowiki.org/./Special:FilePath/Баланово_—_Ново-Александровка.jpg`
NOTE, the file actually sits at:
`http://cyclowiki.org/wiki/Special:FilePath/Баланово_—_Ново-Александровка.jpg` on the wiki.

The fix here is to continue scraping even when an error like this is encountered. (try/catch)

**Comment by kelson42** [comment]
Seems to still fail by me, but for an other reason:
```
$ mwoffliner --mwUrl="http://cyclowiki.org" --adminEmail="kelson@kiwix.com" --localParsoid --verbose --customZimFavicon=Cyclowiki.png
Starting Parsoid
Error: BreakException
    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:248:23
    at Array.forEach (<anonymous>)
    at Object.execute (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:245:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:34:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
fs.js:143
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/srv/kiwix-maintenance/mwoffliner/res/templates/redirects.html'
    at Object.fs.openSync (fs.js:577:3)
    at Object.fs.readFileSync (fs.js:483:33)
    at readTemplate (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:264:29)
    at Object.execute (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:286:61)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:34:15)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by ISNIT0** [comment]
I can't reproduce this, I think it may have been fixed in the master branch. Could you try again please?

**Comment by kelson42** [comment]
Will try again

**Comment by ISNIT0** [comment]
@kelson42 Have you tried again?

**Comment by kelson42** [comment]
@ISNIT0 Pretty much blocked by #421 so far.

**Comment by ISNIT0** [comment]
@kelson42 Could you try this again please?

**Comment by kelson42** [comment]
@ISNIT0 Have you tried it yourself? `mwoffliner` works, but the output is totally broken (mix json/html) if I test it with `kiwix-serve`.

**Comment by ISNIT0** [comment]
I was looking at exceptions being thrown. Hadn't realised the content was broken. I've fixed the content with PR #433

**Comment by kelson42** [comment]
@ISNIT0 please test things properly and verify that the ZIM file looks good: I have run it again, but only the homepage seems to be scrapped!

**Comment by ISNIT0** [comment]
@kelson42 I think this is a different issue?
I have been testing with articleLists which is why I didn't find this.

**Comment by ISNIT0** [comment]
Waiting on #425

**Comment by ISNIT0** [comment]
@kelson42 I've now successfully scraped this completely

**Comment by kelson42** [comment]
@ISNIT0 I confirm :)
