### ISSUE TITLE
Unable to scrappe Inciclopedia

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#399]
```
mwoffliner --mwApiPath="api.php" --mwUrl="http://inciclopedia.wikia.com" --adminEmail="kelson@kiwix.com" --localParsoid --verbose --customZimFavicon=inciclopedia.png
```

then

```
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"',
  longMsg:
   'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"' }
Downloading http://localhost:8000/inciclopedia.wikia.com/v3/page/pagebundle/Super_Secreto?oldid=1491314...
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/9/94/Timewave.jpg/revision/latest/scale-to-width-down/220?cb=20110125232416\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/3/3e/Finn_SW.jpg/revision/latest/scale-to-width-down/250?cb=20160128222724\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/c/cd/Kellogs.jpeg/revision/latest?cb=20110125233315\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/9/91/Star_Wars_7_Poster.jpg/revision/latest/scale-to-width-down/250?cb=20160128170403\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/7/77/DMT.jpeg/revision/latest/scale-to-width-down/220?cb=20110125235700\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/f/f7/Kylo_Ren.jpg/revision/latest/scale-to-width-down/200?cb=20160128222423\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/b/bc/ReyFinnBB8.jpg/revision/latest/scale-to-width-down/210?cb=20160128232722\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/a/ab/Its-a-trap.jpg/revision/latest/scale-to-width-down/430?cb=20160129001140\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/8/8c/Han_Chewie1.jpg/revision/latest/scale-to-width-down/240?cb=20160128230043\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/4/4b/Planta_amiga.jpg/revision/latest/scale-to-width-down/220?cb=20110125234233\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/2/2c/Lukeold.jpg/revision/latest/scale-to-width-down/250?cb=20160128230250\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/4/4e/Mckenna_terence.jpg/revision/latest?cb=20110125235133\" (response code: 404).
Unable to download content [2] http://inciclopedia.wikia.com/"//vignette.wikia.nocookie.net/inciclopedia/images/6/6f/Adamski.gif/revision/latest/scale-to-width-down/220?cb=20110125234006\" (response code: 404).
error/api/version { logType: 'error/api/version',
  wiki: 'wiki$0',
  title: 'Super_Secreto',
  oldId: null,
  reqId: null,
  userAgent: 'MWOffliner/HEAD (kelson@kiwix.com)',
  msg:
   'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"',
  longMsg:
   'Unacceptable profile string: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"' }
Downloading http://inciclopedia.wikia.com/"./Special:FilePath/George-Lucas-Disney-Star-Wars.jpgthumbleft210px/" at /srv/kiwix-maintenance/mwoffliner/cac/inciclopedia_es/m/47e12b4bcb13618cd193...
Downloading http://inciclopedia.wikia.com/"./Special:FilePath/George-Lucas-Disney-Star-Wars.jpgthumbleft210px/"...
Downloading http://inciclopedia.wikia.com/"./Special:FilePath/Jay_Jay_R2.jpgthumb200px—''No_R2_no_te_estamos_reemplazando_con_BB-8''./" at /srv/kiwix-maintenance/mwoffliner/cac/inciclopedia_es/m/c3bfdf8580e730d4a8c2...
Downloading http://inciclopedia.wikia.com/"./Special:FilePath/Jay_Jay_R2.jpgthumb200px—''No_R2_no_te_estamos_reemplazando_con_BB-8''./"...
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:105:13)
    at Object.request (http.js:41:10)
    at defaultMakeRequest (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:83:37)
    at cb (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:71:57)
    at execute (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:27:23)
    at H.get (/usr/local/lib/node_modules/mwoffliner/node_modules/follow-redirects/create.js:113:14)
    at async.retry.finished (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:103:28)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:651:21
    at /usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:718:13
    at iterate (/usr/local/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:262:13)
```

**Comment by ISNIT0** [comment]
This is a similar issue to https://github.com/openzim/mwoffliner/issues/387

It seems the url is malformed and our only real option is to ignore the files

**Comment by kelson42** [comment]
@ISNIT0 I have retried with 1.7, but this is still not working fine:
```
mwoffliner --mwApiPath="api.php" --mwUrl="http://inciclopedia.wikia.com" --adminEmail="kelson@kiwix.com" --localMcs --verbose --customZimFavicon="https://vignette.wikia.nocookie.net/logopedia/images/9/9d/Inciclopedia.jpg/revision/latest/scale-to-width-down/220
```
gives
```
[info] [2019-02-11T15:39:49.076Z] Downloading [https://images.wikia.nocookie.net/inciclopedia/images/c/c9/ChixpyLogoIncinoticias.png]
[info] [2019-02-11T15:39:49.076Z] Downloading https://images.wikia.nocookie.net/inciclopedia/images/7/78/Logo_patataboy.png at /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.png...
[info] [2019-02-11T15:39:49.076Z] Downloading [https://images.wikia.nocookie.net/inciclopedia/images/7/78/Logo_patataboy.png]
[info] [2019-02-11T15:39:49.079Z] Downloading https://images.wikia.nocookie.net/es.pokemon/images/0/0e/Flecha_derecha.gif?1 at /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.gif...
[info] [2019-02-11T15:39:49.079Z] Downloading [https://images.wikia.nocookie.net/es.pokemon/images/0/0e/Flecha_derecha.gif?1]
[info] [2019-02-11T15:39:49.080Z] Downloading https://images.wikia.nocookie.net/inciclopedia/images/5/5d/Checker-16x16.png at /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Checker-16x16.png...
[info] [2019-02-11T15:39:49.080Z] Downloading [https://images.wikia.nocookie.net/inciclopedia/images/5/5d/Checker-16x16.png]
[info] [2019-02-11T15:39:49.100Z] Downloading https://images.wikia.nocookie.net/inciclopedia/images/b/b7/Banner_gradient.gif at /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Banner_gradient.gif...
[info] [2019-02-11T15:39:49.100Z] Downloading [https://images.wikia.nocookie.net/inciclopedia/images/b/b7/Banner_gradient.gif]
[info] [2019-02-11T15:39:49.101Z] Executing command : gifsicle --verbose --colors 64 -O3 "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.gif" -o "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.q5455.gif" &&          if [ $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.q5455.gif") -lt $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.gif") ]; then mv "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.q5455.gif" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.gif"; else rm "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.q5455.gif"; fi
[info] [2019-02-11T15:39:49.113Z] Successfuly optimized /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ajax.gif
[error] [2019-02-11T15:39:49.150Z] Absolutely unable to retrieve async. URL: https://slot1-images.wikia.nocookie.net/skins/commom/images/help-question-hover.gif
[info] [2019-02-11T15:39:49.178Z] Executing command : gifsicle --verbose --colors 64 -O3 "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.gif" -o "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.kndku.gif" &&          if [ $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.kndku.gif") -lt $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.gif") ]; then mv "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.kndku.gif" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.gif"; else rm "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.kndku.gif"; fi
[info] [2019-02-11T15:39:49.189Z] Successfuly optimized /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Flecha_derecha.gif
[info] [2019-02-11T15:39:49.204Z] Executing command : pngquant --verbose --strip --nofs --force --ext=".hphij.png" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.png" &&          advdef -q -z -4 -i 5 "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.hphij.png" &&          if [ $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.hphij.png") -lt $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.png") ]; then mv "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.hphij.png" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.png"; else rm "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/ChixpyLogoIncinoticias.hphij.png"; fi
[info] [2019-02-11T15:39:49.265Z] Executing command : pngquant --verbose --strip --nofs --force --ext=".5ap9m.png" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.png" &&          advdef -q -z -4 -i 5 "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.5ap9m.png" &&          if [ $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.5ap9m.png") -lt $(stat -c%s "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.png") ]; then mv "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.5ap9m.png" "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.png"; else rm "/tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/Logo_patataboy.5ap9m.png"; fi
[info] [2019-02-11T15:39:49.452Z] Successfuly optimized /tmp/mwoffline/tmp/inciclopedia_es_all_2019-02/s/sprite.png
[error] [2019-02-11T15:39:49.565Z] Absolutely unable to retrieve async. URL: https://images.wikia.nocookie.net/inciclopedia/images/5/5d/Checker-16x16.png
[error] [2019-02-11T15:39:49.594Z] Absolutely unable to retrieve async. URL: https://images.wikia.nocookie.net/inciclopedia/images/b/b7/Banner_gradient.gif
[error] [2019-02-11T15:39:49.607Z] Absolutely unable to retrieve async. URL: http://inciclopedia.wikia.com/images/1/11/Newmsg.png
[log] [2019-02-11T15:39:49.608Z] Saving favicon.png...
{"name":"mwoffliner","hostname":"camber","pid":28132,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot read property 'size' of undefined\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1655:89\n    at FSReqWrap.oncomplete (fs.js:158:21)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot read property 'size' of undefined","time":"2019-02-11T15:39:49.632Z","v":0}
{"name":"mwoffliner","hostname":"camber","pid":28132,"level":60,"levelPath":"fatal/service-runner/unhandled","msg":"Cannot read property 'size' of undefined","time":"2019-02-11T15:39:49.633Z","v":0}
[log] [2019-02-11T15:39:49.733Z] Deleting tmp dump dir [/tmp/mwoffline/tmp/mwo-dump-1549899579513]
```
```

**Comment by kelson42** [comment]
The problem has been fixed https://download.kiwix.org/zim/other/inciclopedia_es_all_2019-05.zim
