### ISSUE TITLE
Support HTTP(S) links for options asking for a path

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#457]
We need to expand support of options asking for a path to a file like:
* `--articleList`
* `--customZimFavicon`

These options should also support HTTP(S) links, in that case the content would be downloaded first to `/tmp` and the `mwoffliner` would read the file from here. If the download would failed, then `mwoffliner` would failed. The temporary files should be deleted at the end of the run.

This feature is quite important/urgent to be able to make properly ZIM of sub-selection of articles from Wikipedia.

**Comment by kelson42** [comment]
This seems to fail to me. Tested with git master HEAD:
```
$ mwoffliner --articleList="https://download.kiwix.org/wp1/enwiki/tops/100" --adminEmail="kelson@kiwix.org" --verbose --mwUrl="https://en.wikipedia.org/"
[warn] [2019-01-02T15:03:49.534Z] ***********

	Current node version is [v8.11.3]. We recommend [>=8.12.0]

***********
Failed to run mwoffliner after [0s]: {
	"stack": "Error: ENOENT: no such file or directory, open 'https://download.kiwix.org/wp1/enwiki/tops/100'\n    at Object.fs.openSync (fs.js:646:18)\n    at Object.fs.readFileSync (fs.js:551:33)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1836:67)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:10:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:6:12)\n    at Object.execute (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:87:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:36:15)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Function.Module.runMain (module.js:693:10)",
	"message": "ENOENT: no such file or directory, open 'https://download.kiwix.org/wp1/enwiki/tops/100'",
	"errno": -2,
	"code": "ENOENT",
	"syscall": "open",
	"path": "https://download.kiwix.org/wp1/enwiki/tops/100"
}
```

**Comment by ISNIT0** [comment]
This was caused by changes involving the article list home page. The above PR fixes the issue

**Comment by ISNIT0** [comment]
I was successfully able to run `mwoffliner --verbose --articleList="https://download.kiwix.org/wp1/frwiki/tops/100" --withZimFullTextIndex --adminEmail="kelson@kiwix.org" --mwUrl="https://fr.wikipedia.org/" --redis=redis://127.0.0.1:6379`
