### ISSUE TITLE
Virtual machine: how to use / update? Parsoid problem, unable to download content, statusCode=404

### ISSUE THREAD

**Issue by electronum** [openzim/mwoffliner#46]
Hello, I am running Windows 10 64bit, so I wanted to give the virtual machine from http://www.openzim.org/wiki/Build_your_ZIM_file#MWoffliner a try first.

I would like to dump a mediawiki installation inside my company´s **intranet**.

# Original version
Calling `./mwoffliner.js` produced an error (I did not call `npm install` before that though):
![virtualbox_zimmakervm](https://cloud.githubusercontent.com/assets/25344206/22541195/27a6ae82-e925-11e6-9b48-b513ed8de190.png)

File versions are from December 2015:
```Shell
zimmaker@zimmaker:~/mwoffliner$ ll
total 132
drwxrwxr-x  4 zimmaker zimmaker  4096 Feb  1 15:53 ./
drwxrwxr-x 13 zimmaker zimmaker  4096 Dec 30  2015 ../
-rwxrwxr-x  1 zimmaker zimmaker 11019 Dec 30  2015 mwmatrixoffliner.js*
-rwxrwxr-x  1 zimmaker zimmaker 88083 Dec 30  2015 mwoffliner.js*
drwxrwxr-x 51 zimmaker zimmaker  4096 Feb  1 15:53 node_modules/
-rw-rw-r--  1 zimmaker zimmaker   977 Dec 30  2015 package.json
-rw-rw-r--  1 zimmaker zimmaker   910 Dec 30  2015 README
drwxrwxr-x  2 zimmaker zimmaker  4096 Dec 30  2015 servers/
-rwxrwxr-x  1 zimmaker zimmaker  8188 Dec 30  2015 wpselectionsoffliner.js*
```

# GIt Master version
So I downloaded the current version of mwoffliner, called `npm install` which failed with some errors (forgot to save them). 
As next step I updated nodejs to recent version http://askubuntu.com/a/480642/491867

Now I am stuck at following error when calling `npm install`

```
zimmaker@zimmaker:~/mwoffliner-master$ npm install

> contextify@0.1.15 install /home/zimmaker/mwoffliner-master/node_modules/contextify
> node-gyp rebuild

make: Entering directory `/home/zimmaker/mwoffliner-master/node_modules/contextify/build'
  CXX(target) Release/obj.target/contextify/src/contextify.o
../src/contextify.cc: In static member function â€˜static v8::Local<v8::Context> ContextWrap::createV8Context(v8::Local<v8::Object>)â€™:
../src/contextify.cc:131:68: warning: â€˜v8::Local<v8::Object> v8::Function::NewInstance() constâ€™ is deprecated (declared at /home/zimmaker/.node-gyp/7.5.0/include/node/v8.h:3292): Use maybe version [-Wdeprecated-declarations]
         Local<Object> wrapper = Nan::New(constructor)->NewInstance();
                                                                    ^
../src/contextify.cc:150:16: error: â€˜class v8::ObjectTemplateâ€™ has no member named â€˜SetAccessCheckCallbacksâ€™
         otmpl->SetAccessCheckCallbacks(GlobalPropertyNamedAccessCheck,
                ^
../src/contextify.cc: In static member function â€˜static void ContextWrap::GlobalPropertyGetter(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Value>&)â€™:
../src/contextify.cc:182:80: warning: â€˜v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)â€™ is deprecated (declared at /home/zimmaker/.node-gyp/7.5.0/include/node/v8.h:2948): Use maybe version [-Wdeprecated-declarations]
         Local<Value> rv = Nan::New(ctx->sandbox)->GetRealNamedProperty(property);
                                                                                ^
../src/contextify.cc: In static member function â€˜static void ContextWrap::GlobalPropertyQuery(v8::Local<v8::String>, const Nan::PropertyCallbackInfo<v8::Integer>&)â€™:
../src/contextify.cc:209:67: warning: â€˜v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)â€™ is deprecated (declared at /home/zimmaker/.node-gyp/7.5.0/include/node/v8.h:2948): Use maybe version [-Wdeprecated-declarations]
         if (!Nan::New(ctx->sandbox)->GetRealNamedProperty(property).IsEmpty() ||
                                                                   ^
../src/contextify.cc:210:71: warning: â€˜v8::Local<v8::Value> v8::Object::GetRealNamedProperty(v8::Local<v8::String>)â€™ is deprecated (declared at /home/zimmaker/.node-gyp/7.5.0/include/node/v8.h:2948): Use maybe version [-Wdeprecated-declarations]
             !Nan::New(ctx->proxyGlobal)->GetRealNamedProperty(property).IsEmpty()) {
                                                                       ^
make: *** [Release/obj.target/contextify/src/contextify.o] Error 1
make: Leaving directory `/home/zimmaker/mwoffliner-master/node_modules/contextify/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:192:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.19.0-42-generic
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/zimmaker/mwoffliner-master/node_modules/contextify
gyp ERR! node -v v7.5.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.5.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zimmaker/mwoffliner-master/npm-debug.log
```

Versions are, as you see:
* node-gyp -v v3.5.0
* node v7.5.0
* npm  v4.1.2

I have been looking at lots of issues having the displayed error `Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.` and tried many steps so far, like updating some packages, removing, reinstalling and so on (I am sorry I cannot replicate all them now)

I understand the error seems to be quite generic and more nodejs related, lots of users are having it with totally different packages. Log file `npm-debug.log` is attached:
[npm-debug.log.txt](https://github.com/kiwix/mwoffliner/files/747156/npm-debug.log.txt)

Maybe someone has some experience or can explain how to setup a working configuration of mwoffliner? Is there a more recent version of the virtual machine?

Last, I found the following instructions https://labtestwikitech.wikimedia.org/wiki/Nova_Resource_Talk:Mwoffliner but will need time to get through it.

# Documentation
Some more information and references in the http://www.openzim.org/wiki/ on working with the Virtual machine would be nice. I am glad if I can contribute some experience if I achieve a working configuration.
Examples:
* `sudo apt-get install openssh-server` (which is not included) for more convenient access through host ssh client
* how to update nodejs

**Comment by electronum** [comment]
Update: I am sorry, I made some major mistakes, I am retrying the script now, please do not replay yet.

**Comment by kelson42** [comment]
@electronum What kind of problem do you finally have with the VM? The documentation tries indeed to be limited to zimwriterfs itself. The rest concern GNU/Linux or Ubuntu or nodejs and we do not try to cover/maintain that part. Let us also know if we can close the ticket.

**Comment by electronum** [comment]
Hello, my setup is following:
* the MediaWiki installation is running within the intranet under http://172.18.200.40/wiki/
  * Parsoid is not (yet) installed there, but according #2 this should be possible
* I am trying the VirtualBox installation first, just for the reasons of convenience 

# Parsoid
* I went through the official guide https://www.mediawiki.org/wiki/Parsoid/Setup#Ubuntu_.2F_Debian
* `/etc/mediawiki/parsoid/config.yaml` is configured as:
```
        # Configure Parsoid to point to your MediaWiki instances.
        mwApis:
        - # This is the only required parameter,
          # the URL of you MediaWiki API endpoint.
          uri: 'http://172.18.200.40/himtwiki/api.php'
          prefix: 'localhost'
          # The "domain" is used for communication with Visual Editor
          # and RESTBase.  It defaults to the hostname portion of
          # the `uri` property below, but you can manually set it
          # to an arbitrary string.
          domain: 'localhost'  # optional
```
* Parsoid has been restarted: `sudo service parsoid restart`
* Now following https://www.mediawiki.org/wiki/Parsoid/Troubleshooting
  * `curl http://172.18.200.40/himtwiki/api.php` -> api.php is accessible
  * `curl -L http://localhost:8142/localhost/v3/page/html/Main_Page` -> the output of 'Main_Page' is successful
  * Unfortunately opening `http://localhost:8142/_wikitext/` or `http://localhost:8142/_wikitext/localhost` in web browser does not work. Do I need apache web server installed for that?

# Redis
`/etc/redis/redis.conf` compared to https://labtestwikitech.wikimedia.org/wiki/Nova_Resource_Talk:Mwoffliner#Configure_redis
is:
```
unixsocket /dev/shm/redis.sock
unixsocketperm 777

save 900 1
save 300 10
save 60 10000

appendfsync everysec
```

# mwoffliner.js
* I tried the version from December 2015 shipped with the Virtual Machine first
```
zimmaker@zimmaker:~/mwoffliner$ ll
total 144
drwxrwxr-x  7 zimmaker zimmaker  4096 Feb  2 16:41 ./
drwxrwxr-x 13 zimmaker zimmaker  4096 Dec 30  2015 ../
drwxrwxr-x  3 zimmaker zimmaker  4096 Feb  2 16:41 cac/
-rwxrwxr-x  1 zimmaker zimmaker 11019 Dec 30  2015 mwmatrixoffliner.js*
-rwxrwxr-x  1 zimmaker zimmaker 88083 Dec 30  2015 mwoffliner.js*
drwxrwxr-x 16 zimmaker zimmaker  4096 Dec 30  2015 node_modules/
drwxrwxr-x  2 zimmaker zimmaker  4096 Feb  3 15:28 out/
-rw-rw-r--  1 zimmaker zimmaker   977 Dec 30  2015 package.json
-rw-rw-r--  1 zimmaker zimmaker   910 Dec 30  2015 README
drwxrwxr-x  2 zimmaker zimmaker  4096 Dec 30  2015 servers/
drwxrwxr-x  2 zimmaker zimmaker  4096 Feb  3 15:28 tmp/
-rwxrwxr-x  1 zimmaker zimmaker  8188 Dec 30  2015 wpselectionsoffliner.js*
```
* Executed `npm install`
* I continued with the instructions from [#10 comment](https://github.com/kiwix/mwoffliner/issues/10#issuecomment-248880674)
* The command `./mwoffliner.js  --mwUrl=http://172.18.200.40/ --parsoidUrl=http://localhost:8142/ --adminEmail=test@test.com --mwApiPath=himtwiki/api.php --verbose` finishes
* The log begin looks promising:
```
[...]
Getting redirects for article Nano...
Downloading http://172.18.200.40/himtwiki/api.php?action=query&list=backlinks&blfilterredir=redirects&bllimit=max&format=json&bltitle=Nano&rawcontinue=...
2 redirect(s) found for Text_editor
[...]
All redirect ids retrieve successfuly.
Starting a new dump...
Creating sub directories at "/home/zimmaker/kiwix-other/mwoffliner/tmp/172_en_all_2017-02/"...
Creating javascript...
Get the javascript from http://172.18.200.40/wiki/
Downloading http://172.18.200.40/wiki/...
Writting dummy js at/home/zimmaker/kiwix-other/mwoffliner/tmp/172_en_all_2017-02/j/local.js
Adding load listener on window
Listener (to load javascript added to window)...
Going through scripts in head and body to dump javascript...
Downloading javascript from http://172.18.200.40/himtwiki/load.php?debug=true&lang=en&modules=startup&only=scripts&skin=monobook&*
Downloading http://172.18.200.40/himtwiki/load.php?debug=true&lang=en&modules=startup&only=scripts&skin=monobook&*...
All CSS/JS dependencies downloaded successfuly.
[...]
Getting article from http://localhost:8142/Errorcodes&oldid=28185
Cache hit for http://localhost:8142/Errorcodes&oldid=28185 (/home/zimmaker/kiwix-other/mwoffliner/cac/172_en/ba629379035ba04b3b4a)
Getting article from http://localhost:8142/Configuration_files_(list)&oldid=28311
Cache hit for http://localhost:8142/Configuration_files_(list)&oldid=28311 (/home/zimmaker/kiwix-other/mwoffliner/cac/172_en/471a01998e8cc9c773b3)
[...]
```

Log end:
```
All articles were retrieved and saved.
0 images still to be downloaded.
Process still downloading images...
All images successfuly downloaded
0 images still to be optimized.
Process still being optimizing images...
All images successfuly optimized
Building ZIM file /home/zimmaker/kiwix-other/mwoffliner/out/172_en_all_2017-02.zim (zimwriterfs --welcome=index.htm --favicon=favicon.png --language=eng --title="wiki" --description="From wiki" --creator="172" --publisher="Kiwix" "/home/zimmaker/kiwix-other/mwoffliner/tmp/172_en_all_2017-02/" "/home/zimmaker/kiwix-other/mwoffliner/out/172_en_all_2017-02.zim")...
create directory entries
collect articles
sort 56 directory entries (aid)
remove invalid redirects from 56 directory entries
sort 56 directory entries (url)
set index
translate redirect aid to index
56 directory entries created
create title index
56 title index created
create clusters
0% ready
10% ready
20% ready
30% ready
40% ready
50% ready
60% ready
70% ready
80% ready
90% ready
46 clusters created
fill header
write zimfile
ready
ZIM file built at /home/zimmaker/kiwix-other/mwoffliner/out/172_en_all_2017-02.zim
Dumping finished with success.
Cleaning cache
Flushing redis databases...
Redis databases flushed.
Quitting redis databases...
Closing HTTP agents...
All dumping(s) finished with success.
```

But I get several errors in between and the resulting ZIM file contains the logo picture only.

## Error: Unable to download content, Socket timeout
This is one is not really bothering me, because of files belonging to wikimedia.
```
http://bits.wikimedia.org/static-current/skins/common/images/bullet.gif (request error: Error: getaddrinfo ENOTFOUND bits.wikimedia.org ).
Unable to download content [1] http://bits.wikimedia.org/static-current/skins/Vector/images/bullet-icon.png (request error: Error: getaddrinfo ENOTFOUND bits.wikimedia.org ).
Socket timeout
Executing command : undefined
Failed to optim /home/zimmaker/kiwix-other/mwoffliner/tmp/172_en_all_2017-02/s/bullet.gif, with size=0 (Unable to find optimization command.)
Unable to download content [2] http://bits.wikimedia.org/static-current/skins/Vector/images/bullet-icon.png (request error: Error: getaddrinfo ENOTFOUND bits.wikimedia.org ).
Socket timeout
Unable to download content [3] http://bits.wikimedia.org/static-current/skins/Vector/images/bullet-icon.png (request error: Error: getaddrinfo ENOTFOUND bits.wikimedia.org ).
Socket timeout
```

## Error: Unable to download content [2] (statusCode=404)
None of the the actual wiki pages can be downloaded (similar to [#10 comment](https://github.com/kiwix/mwoffliner/issues/10#issuecomment-255952206)):
```
Getting article from http://localhost:8142/Text_editor&oldid=28231
Downloading http://localhost:8142/Text_editor&oldid=28231...
Unable to download content [1] http://localhost:8142/Text_editor&oldid=28231 (statusCode=404).
Unable to download content [2] http://localhost:8142/Text_editor&oldid=28231 (statusCode=404).
Unable to download content [3] http://localhost:8142/Text_editor&oldid=28231 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://localhost:8142/Text_editor&oldid=28231 (statusCode=404).
Caching http://localhost:8142/Text_editor&oldid=28231 at /home/zimmaker/kiwix-other/mwoffliner/cac/172_en/1ba239e370d840475685...
Getting article from http://localhost:8142/Map_network_drive&oldid=28233
[...]
Downloading http://localhost:8142/Map_network_drive&oldid=28233...
Unable to download content [1] http://localhost:8142/Map_network_drive&oldid=28233 (statusCode=404).
Unable to download content [2] http://localhost:8142/Map_network_drive&oldid=28233 (statusCode=404).
Unable to download content [3] http://localhost:8142/Map_network_drive&oldid=28233 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://localhost:8142/Map_network_drive&oldid=28233 (statusCode=404).
Caching http://localhost:8142/Map_network_drive&oldid=28233 at /home/zimmaker/kiwix-other/mwoffliner/cac/172_en/ab5e1c923256c4d9629a...
```
# mwoffliner-master from GitHub
Tried the master-version, it only failed at the end:
```
All images successfuly optimized
Building ZIM file /home/zimmaker/mwoffliner-master/out/172_en_all_2017-02.zim (zimwriterfs --welcome=index.htm --favicon=favicon.png --language=eng--welcome=Main_Page.html --verbose  --name="kiwix.172_en_all" --redirects="/home/zimmaker/mwoffliner-master/cac/172_en/172_en_all.redirects" --title="HIMTwiki" --description="From HIMTwiki" --creator="172" --publisher="Kiwix" "/home/zimmaker/mwoffliner-master/tmp/172_en_all_2017-02/" "/home/zimmaker/mwoffliner-master/out/172_en_all_2017-02.zim")...
RAID: kiwix.172_en_all
zimwriterfs: unrecognized option '--redirects=/home/zimmaker/mwoffliner-master/cac/172_en/172_en_all.redirects'
zimwriterfs: unrecognized option '--name=kiwix.172_en_all'
zimwriterfs: unable to find welcome page at '
/home/zimmaker/mwoffliner-master/tmp/172_en_all_2017-02
/
Main_Page.html
. --welcome path/value must be relative to HTML_DIRECTORY.

Failed to build successfuly the ZIM file /home/zimmaker/mwoffliner-master/out/172_en_all_2017-02.zim (Error by executing zimwriterfs)
```
Should I install a newer version of zimwriterfs?

**Comment by kelson42** [comment]
@electronum 
* For Parsoid, I recommend to to deal with the Parsoid team. I have it running on many Mediawikis but I'm not an expert of it. You should better have a working VisualEditor before going to next steps.
* For Redis, the main point is to have it listening on the right socket for mwoffliner (but Parsoid relies on it too). Mwoffliner has a parameter for it. The rest is just optimization.
* For the VM, as long we are not 100% Parsoid runs fine, no way to have a look.

In general:
* In the next months we will try to extend mwoffliner to embeds the Parsoid (to avoid users to have to install Parsoid themself)
* I should create a new version of the zimmaker VM

**Comment by electronum** [comment]
> * For Parsoid, I recommend to to deal with the Parsoid team. I have it running on many Mediawikis but I'm not an expert of it. You should better have a working VisualEditor before going to next steps.
>
> * For the VM, as long we are not 100% Parsoid runs fine, no way to have a look.

All right, I tried to install Parsoid and Visual Editor on my MediaWiki (for all the last days :pensive:), to sum it up, it fails with the same error 404. So It does not look to be mwoffliner´s fault. The Parsoid error 404 appears on some other few issues, but so far nothing helped. Something seems to be wrong with the server configuration, neither Parsoid nor Visual Editor produce any error logs.
I have opened threads at Parsoid and Visual Editor discussion groups, hoping to get it solved there.

>* For Redis, the main point is to have it listening on the right socket for mwoffliner (but Parsoid relies on it too). Mwoffliner has a parameter for it. The rest is just optimization.

Could you please give some hints or examples where I should look for?

**Question:** what I do not understand looking at the log, why does mwoffliner try to get the page from `http://localhost:8142/Main_Page?oldid=28384` (which is not existing)?
I would expect the other path `http://localhost:8142/localhost/v3/page/html/Main_Page` which is definitely working.

Could you give an example, how a typical request should look like? What would be a correct address? I just would like to understand what happens there, maybe my server configuration redirects the request to a wrong path.

**Comment by electronum** [comment]
I recognized Redis was not installed on my server, though `/etc/redis/redis.conf` was existing. Now I have installed Redis, using the default configuration, Redis service is running.

According to https://www.mediawiki.org/wiki/Offline_content_generator/Installation/en#Starting I called `netstat -tuln`, the output:
```
server223:/etc/init.d # netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:873             0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:21              0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:6556            0.0.0.0:*               LISTEN
tcp        0      0 :::8000                 :::*                    LISTEN
tcp        0      0 :::873                  :::*                    LISTEN
tcp        0      0 :::3306                 :::*                    LISTEN
tcp        0      0 :::22                   :::*                    LISTEN
udp        0      0 0.0.0.0:57053           0.0.0.0:*
udp        0      0 0.0.0.0:57231           0.0.0.0:*
udp        0      0 0.0.0.0:33014           0.0.0.0:*
udp        0      0 0.0.0.0:54328           0.0.0.0:*
udp        0      0 0.0.0.0:5353            0.0.0.0:*
udp        0      0 0.0.0.0:43376           0.0.0.0:*
udp        0      0 0.0.0.0:47603           0.0.0.0:*
udp        0      0 :::38093                :::*
udp        0      0 :::5353                 :::*
```
* `tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN` probably belongs to Redis
* `tcp        0      0 :::8000                 :::*                    LISTEN` should belong to Parsoid, however the address `:::8000` looks suspicious to me, should it be `0.0.0.0:8000` with _zeros_ instead? Or even something different like _127.0.0.1?_

**Comment by kelson42** [comment]
@electronum sorry for not coming back to you regarding your problems, but days have only 24h. We have published a new zimwriterfs VM and we also have now a docker image. We them everything should work fine.
