### ISSUE TITLE
[REGRESSION] --articleList seems not to be able with a local file anymore

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#480]
```
$ wget https://download.kiwix.org/wp1/enwiki/tops/100
--2019-01-02 16:08:39--  https://download.kiwix.org/wp1/enwiki/tops/100
Resolving download.kiwix.org (download.kiwix.org)... 195.154.156.115
Connecting to download.kiwix.org (download.kiwix.org)|195.154.156.115|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.kiwix.org/wp1/enwiki_2019-01/tops/100 [following]
--2019-01-02 16:08:39--  https://download.kiwix.org/wp1/enwiki_2019-01/tops/100
Reusing existing connection to download.kiwix.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 1175 (1.1K)
Saving to: ‘100’

100                                                100%[================================================================================================================>]   1.15K  --.-KB/s    in 0s      

2019-01-02 16:08:39 (164 MB/s) - ‘100’ saved [1175/1175]

$ mwoffliner --articleList="100" --adminEmail="kelson@kiwix.org" --verbose --mwUrl="https://en.wikipedia.org/"
[warn] [2019-01-02T15:08:44.112Z] ***********

	Current node version is [v8.11.3]. We recommend [>=8.12.0]

***********
Failed to run mwoffliner after [0s]: {
	"stack": "Error: EBADF: bad file descriptor, fstat\n    at tryStatSync (fs.js:517:13)\n    at Object.fs.readFileSync (fs.js:553:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1836:67)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:10:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:6:12)\n    at Object.execute (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:87:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:36:15)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Function.Module.runMain (module.js:693:10)",
	"message": "EBADF: bad file descriptor, fstat",
	"errno": -9,
	"code": "EBADF",
	"syscall": "fstat"
}
```

It should work IMO

**Comment by ISNIT0** [comment]
Could you try passing article list as `./100` rather than just `100` please?

**Comment by kelson42** [comment]
@ISNIT0 Works better, but still a problem.
