### ISSUE TITLE
A proper error message should be printed if --articleList URL or path is wrong

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#481]
Not sure if this is a regressions but, if the --articleList URL or path is not available, a proper error should be displayed. I get a this:
```
$ mwoffliner --articleList="42424242" --adminEmail="kelson@kiwix.org" --verbose --mwUrl="https://en.wikipedia.org/"
[warn] [2019-01-02T15:10:09.072Z] ***********

	Current node version is [v8.11.3]. We recommend [>=8.12.0]

***********
Failed to run mwoffliner after [0s]: {
	"stack": "Error: EBADF: bad file descriptor, fstat\n    at tryStatSync (fs.js:517:13)\n    at Object.fs.readFileSync (fs.js:553:3)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1836:67)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:10:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:6:12)\n    at Object.execute (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:87:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:36:15)\n    at Module._compile (module.js:652:30)\n    at Object.Module._extensions..js (module.js:663:10)\n    at Module.load (module.js:565:32)\n    at tryModuleLoad (module.js:505:12)\n    at Function.Module._load (module.js:497:3)\n    at Function.Module.runMain (module.js:693:10)",
	"message": "EBADF: bad file descriptor, fstat",
	"errno": -9,
	"code": "EBADF",
	"syscall": "fstat"
}
```

**Comment by ISNIT0** [comment]
We now get an error to this effect:
`[error] [2019-01-15T09:13:45.170Z] Failed to download article list from [https://download.kiwix.org/wp1/frwtops/100]`
