### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by p-deli** [openzim/mwoffliner#492]
After having solved the `rsvg-convert` problem by installing `librsvg2-bin` (see [issue 491](https://github.com/openzim/mwoffliner/issues/491)), I now get the following when typing `mwoffliner --mwUrl=http://192.168.56.5/UnifiedICTDoc --adminEmail=foo@bar.net --verbose`:

```
Getting text direction...
Downloading http://192.168.56.5/UnifiedICTDoc/wiki/...
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to /dev/shm/redis.sock failed - connect ENOENT /dev/shm/redis.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
Emitted 'error' event at:
    at RedisClient.on_error (/home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

Or this when I type `mwoffliner --mwUrl=https://ts.wikipedia.org --adminEmail=foo@bar.net --verbose`:

```
Getting text direction...
Downloading https://ts.wikipedia.org/wiki/...
(node:16355) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to /dev/shm/redis.sock failed - connect ENOENT /dev/shm/redis.sock
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1082:14)
Emitted 'error' event at:
    at RedisClient.on_error (/home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:188:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
``

**Comment by kelson42** [comment]
@p-deli Which version of the mwoffliner? Which OS? Have you read the README file?

**Comment by ISNIT0** [comment]
@p-deli You need Redis to use MWOffliner. By default MWOffliner will try to connect via `/dev/shm/redis.sock`. You can provide a custom Redis connection string using something like `--redis=redis://127.0.0.1:6379`

**Comment by p-deli** [comment]
> @p-deli Which version of the mwoffliner? Which OS? Have you read the README file?

Please find here below the answers to your above mentioned questions:
- mwoffliner version 1.6.0
- Ubuntu release 18.10 (cosmic, desktop edition)
- Yes, I read the README file, as a matter of fact that is what I used to install mwoffliner (although I needed much more things; I can provide you the installation guide I made myself if you want)

**Comment by p-deli** [comment]
> @p-deli You need Redis to use MWOffliner. By default MWOffliner will try to connect via `/dev/shm/redis.sock`. You can provide a custom Redis connection string using something like `--redis=redis://127.0.0.1:6379`

@ISNIT0 thank you for your comment. Please find here under the details concerning redis:
- `redis-server --version`: Redis server v=4.0.11 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=fc908f68b3e66abd
- typing `redis-server`and pressing return gives the following:
```
3216:C 09 Jan 13:47:39.642 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
3216:C 09 Jan 13:47:39.643 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=3216, just started
3216:C 09 Jan 13:47:39.643 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
3216:M 09 Jan 13:47:39.644 * Increased maximum number of open files to 10032 (it was originally set to 1024).
3216:M 09 Jan 13:47:39.645 # Creating Server TCP listening socket *:6379: bind: Address already in use
```
- I tested redis as suggested [here](https://redis.io/topics/quickstart) and it worked
- therefore, I tried to specify `--redis=redis://127.0.0.1:6379` in my initial command as follows `mwoffliner --mwUrl=http://192.168.56.5/UnifiedICTDoc --adminEmail=foo@bar.net --verbose --redis=redis://127.0.0.1:6379`but got this in return:
```
Getting text direction...
Downloading http://192.168.56.5/UnifiedICTDoc/wiki/...
Unable to download content [1] http://192.168.56.5/UnifiedICTDoc/wiki/ (response code: 404).
Unable to download content [2] http://192.168.56.5/UnifiedICTDoc/wiki/ (response code: 404).
Unable to download content [3] http://192.168.56.5/UnifiedICTDoc/wiki/ (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://192.168.56.5/UnifiedICTDoc/wiki/ (response code: 404).
Unable to get the language direction, fallback to ltr
Text direction is ltr
Getting web site name...
Downloading http://192.168.56.5/UnifiedICTDoc/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc...
Unable to download content [1] http://192.168.56.5/UnifiedICTDoc/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc (response code: 404).
Unable to download content [2] http://192.168.56.5/UnifiedICTDoc/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc (response code: 404).
Unable to download content [3] http://192.168.56.5/UnifiedICTDoc/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc (response code: 404).
Absolutely unable to retrieve async. URL: Unable to download content [3] http://192.168.56.5/UnifiedICTDoc/w/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc (response code: 404).
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/lib/MediaWiki.js:159:36
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/lib/Downloader.js:199:13
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:676:51
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:726:13
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:52:16
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:264:21
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:44:16
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:723:17
    at /home/pit/.nvm/versions/node/v11.6.0/lib/node_modules/mwoffliner/node_modules/async/lib/async.js:167:37
```

**Comment by kelson42** [comment]
@p-deli yes please.

**Comment by p-deli** [comment]
> @p-deli yes please.

Will do @kelson42 . However, before doing that I was wondering if I should open 2 or only one. `--verbose` shows a recurring 4 lines out of which the fourth always ends up in error (like shown below) and there is another error where `zimwriterfs` seems to receive 2 contradictory arguments leading to the failure of the ZIM file creation (shown at the end of this comment). My question: should I treat them as separate issues or one issue?

Recurring error:
```
Getting (desktop) article from http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69
Downloading http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69...
Caching http://192.168.56.5/UnifiedICTDoc/api.php?action=visualeditor&format=json&paction=parse&page=IT&oldid=69 at /home/pit/Downloads/cac/192_en/6a89ec3991120c028d52...
Error by retrieving article: Unrecognized value for parameter "action": visualeditor.
```

Two `--welcome` arguments received by `zimwriterfs` (`--welcome=index.htm` and `--welcome=Main_Page.html`) which _looks_ odd:
```
zimwriterfs --welcome=index.htm --favicon=favicon.png --language=eng --welcome=Main_Page.html --verbose  --tags="56" --name="kiwix.192_en_all" --redirects="/home/pit/Downloads/cac/192_en/192_en_all.redirects" --title="Unified ICT Doc" --description="From Unified ICT Doc" --creator="192" --publisher="Kiwix" "/home/pit/Downloads/tmp/192_en_all_2019-01/" "/home/pit/Downloads/out/192_en_all_2019-01.zim")...
```

**Comment by kelson42** [comment]
@p-deli What is the status on this? It seems that visual editor is not installed properly and you don't use the localMCS option!

**Comment by p-deli** [comment]
> @p-deli What is the status on this? It seems that visual editor is not installed properly and you don't use the localMCS option!

@kelson42  Please find below what I do for the installation of VisualEditor. As for `localMCS` you are right I don't recall seeing that option. Will look into it and come back to you asap.

```
git clone https://github.com/wikimedia/mediawiki-extensions-VisualEditor.git /var/www/html/Wiki/extensions/VisualEditor/
cd /var/www/html/Wiki/extensions/VisualEditor
git submodule update --init
nano /var/www/html/Wiki/LocalSettings.php
```

Add the following lines at the end of the `LocalSettings.php`:

```
// Added for VisualEditor on 20190130 as per
// https://www.mediawiki.org/wiki/Topic:Trpwvcu1lk3k3omr
$wgVirtualRestConfig['modules']['parsoid'] = array(
// URL to the Parsoid instance
// Use port 8142 if you use the Debian package
'url' => 'http://localhost:8142',
// Parsoid "domain", see below (optional)
'domain' => 'localhost',
// Parsoid "prefix", see below (optional)
'prefix' => 'localhost'
);
```

**Comment by kelson42** [comment]
@p-deli I can not really help for the installation of visual editor. But this should not be necessary as with 1.8 everything is handled by MWoffliner is the Mediawiki does not provide it. Considering that MWoffliner has evolved a lot these last 6 months. I think it would be good to restart a new ticket if you still have a mwoffliner error with version 1.8.5.
