### ISSUE TITLE
[REGRESSION] Does not work anymore without --articleList argument

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#502]
```
$ mwoffliner --verbose --adminEmail="kelson@kiwix.org" --mwUrl=https://bm.wikipedia.org/ --keepHtml
[error] [2019-01-12T15:54:24.764Z] Failed to read articleList from [undefined] { Error: ENOENT: no such file or directory, open 'undefined'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2091:75)
    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)
    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)
    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:7:58) errno: -2, syscall: 'open', code: 'ENOENT', path: 'undefined' }
Failed to run mwoffliner after [0s]: {
	"stack": "Error: ENOENT: no such file or directory, open 'undefined'\n    at Object.openSync (fs.js:443:3)\n    at Object.readFileSync (fs.js:348:35)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:2091:75)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:7:58)",
	"message": "ENOENT: no such file or directory, open 'undefined'",
	"errno": -2,
	"syscall": "open",
	"code": "ENOENT",
	"path": "undefined"
}
```

**Comment by kelson42** [comment]
@ISNIT0 It is pretty important that we close 1.7 ASAP, could you have a look to this issue too please?
