### ISSUE TITLE
rsvg-convert related error with running mwoffliner

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#560]
command run: `mwoffliner --mwUrl=https://ik.wikipedia.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --withZimFullTextIndex --useCache --redis=redis://redis --outputDirectory=/output`

exit code 2

```
\t"stack": "Error: Command failed: rsvg-convert --version\
/bin/sh: 1: rsvg-convert: not found\
\
    at ChildProcess.exithandler (child_process.js:294:12)\
    at ChildProcess.emit (events.js:189:13)\
    at maybeClose (internal/child_process.js:970:16)\
    at Socket.stream.socket.on (internal/child_process.js:389:11)\
    at Socket.emit (events.js:189:13)\
    at Pipe._handle.close (net.js:600:12)",
\t"message": "Command failed: rsvg-convert --version\
/bin/sh: 1: rsvg-convert: not found\
",
\t"killed": false,
\t"code": 127,
\t"signal": null,
\t"cmd": "rsvg-convert --version"
```

**Comment by kelson42** [comment]
@automactic This should be fixed in a few minutes/hours when openzim/mwoffliner:latest docker image will be rebuilt. Sorry for the inconvenience. Having zimfarm jobs with specific image tag will avoid this kind of problem too.
