### ISSUE TITLE
Error offlining zh-min-nan.wikiquote.org

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#563]
```
Traceback (most recent call last):
  File "/usr/src/app/operations/run_mwoffliner.py", line 37, in execute
    links={self.redis_container_name: 'redis'}, name='mwoffliner_{}'.format(self.task_id))
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 814, in run
    container, exit_status, command, image, out
docker.errors.ContainerError: Command 'mwoffliner --mwUrl=https://zh-min-nan.wikiquote.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --withZimFullTextIndex --useCache --redis=redis://redis --outputDirectory=/output' in image 'openzim/mwoffliner:1.7.1' returned non-zero exit status 2: b'Couldn\'t find strings file for [nan], falling back to [en]
[error] [2019-02-13T03:39:16.918Z] Absolutely unable to retrieve async. URL: https://zh-min-nan.wikiquote.org/wiki/Mediawiki:offline.css?action=raw
[error] [2019-02-13T03:39:20.137Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.141Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.147Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.152Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.156Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.159Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.164Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.194Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.212Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.240Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.252Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.257Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.262Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.277Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.282Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.293Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.302Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.326Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.328Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.334Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.349Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.352Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.353Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.357Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.364Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.374Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.384Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.386Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.393Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.400Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.403Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.428Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.435Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.446Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-13T03:39:20.451Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.458Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.466Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.476Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.479Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-13T03:39:20.484Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.501Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.511Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.514Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.515Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.538Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.542Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-13T03:39:20.587Z] Error handling json response from api. Error: No HTML was found
Failed to run mwoffliner after [8s]: "Failed to build successfuly the ZIM file /output/wikiquote_nan_all_nopic_2019-02.zim (Error when executing zimwriterfs)"
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 67, in run
    raise e
  File "/usr/src/app/tasks/mwoffliner.py", line 52, in run
    offliner_stdout = run_mwoffliner.execute()
  File "/usr/src/app/operations/run_mwoffliner.py", line 43, in execute
    raise OfflinerError(code='docker.ContainerError', stderr=e.stderr)
operations.base.OfflinerError
```

**Comment by kelson42** [comment]
@ISNIT0 Can you please verify it works with 1.8?
