### ISSUE TITLE
Unable to get version with 1.8

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#566]
on my Linux:
```
sudo npm install -g openzim/mwoffliner
```

then
```
$ mwoffliner --version
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/mwoffliner.lib.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/bin/mwoffliner.script.js:7:23)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
```

**Comment by kelson42** [comment]
New error
```
$ mwoffliner --version
\internal/modules/cjs/loader.js:718
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /usr/local/lib/node_modules/mwoffliner/node_modules/libzim-binding/dist/nbind.node: undefined symbol: _ZNK3zim6writer7Article12getParameterB5cxx11Ev
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at initNode (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:141:15)
    at /usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:115:13
    at findCompiledModule (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:79:13)
    at find (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:93:13)
```

**Comment by ISNIT0** [comment]
@kelson42 Are there any build errors above?

**Comment by kelson42** [comment]
@ISNIT0  no

**Comment by ISNIT0** [comment]
I can't reproduce the bug

**Comment by kelson42** [comment]
@ISNIT0 You use the same install line on ubuntu?

**Comment by ISNIT0** [comment]
In a docker container, so it's slightly different, but it works

**Comment by kelson42** [comment]
@ISNIT0 Have testing and testing, now I'm back at the first error.

The problem seems to be that line:
```
const parameterList = require('../lib/parameterList').default;
```

considering that:

```
$ which mwoffliner 
/usr/local/bin/mwoffliner
$ find /usr/local -name "*parameterList*"
/usr/local/lib/node_modules/mwoffliner/src/parameterList.ts
```
Which version of `npm` do you use?

**Comment by kelson42** [comment]
Now it works, but dies later:
```
[log] [2019-02-17T18:09:22.664Z] 20 redirect(s) found
[log] [2019-02-17T18:09:22.665Z] All redirect ids retrieve successfuly.
Couldn't find strings file for [bm], falling back to [en]
[log] [2019-02-17T18:09:22.666Z] Doing dump: [[object Object]]
[log] [2019-02-17T18:09:22.667Z] Writing zim to [/dev/shm/out/wikipedia_bm_all_2019-02.zim]
Failed to run mwoffliner after [5s]: {
	"stack": "Error: failed to create temporary directory /dev/shm/out/wikipedia_bm_all_2019-02.tmp\n    at ZimCreator._createZimCreator (/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:70:51)\n    at new ZimCreator (/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js:66:14)\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:97:42\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:10:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:6:12)\n    at doDump (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:86:20)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:591:42)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:35:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:16:53)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:7:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "failed to create temporary directory /dev/shm/out/wikipedia_bm_all_2019-02.tmp"
}


**********

failed to create temporary directory /dev/shm/out/wikipedia_bm_all_2019-02.tmp

**********


[log] [2019-02-17T18:09:22.669Z] Deleting tmp dump dir [/dev/shm/tmp/mwo-dump-1550426957823]

```

**Comment by kelson42** [comment]
* I think the `tmp` directory should not be created either.
* It seems to be a misunderstanding in the error message, it should be "failed to create output directory", not "failed to create temporary directory"

**Comment by ISNIT0** [comment]
@kelson42 the "failed to create temporary directory" log comes from LibZim, not MWOffliner

Do you mean the "tmp dump dir"?

**Comment by kelson42** [comment]
OK, so nothing you can do then about this wording.

**Comment by ISNIT0** [comment]
Which "tmp directory" do you think shouldn't be created?

**Comment by kelson42** [comment]
There is only one tmpDirectory in mwoffliner and per default this was "tmp" (relative to current directory). It is still created.

**Comment by ISNIT0** [comment]
@kelson42 we also make this tmp directory `/dev/shm/tmp/mwo-dump-1550426957823`
