### ISSUE TITLE
Unable to scrape bm.wikipedia.org

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#577]
```
$ mwoffliner --mwUrl=https://bm.wikipedia.org/ --adminEmail=kelson@kiwix.org
[log] [2019-02-19T06:41:56.307Z] Getting text direction...
[log] [2019-02-19T06:41:56.311Z] Getting site info...
[log] [2019-02-19T06:41:56.312Z] Getting sub-title...
[log] [2019-02-19T06:41:56.678Z] Text direction is [ltr]
[log] [2019-02-19T06:41:56.815Z] Using a remote MCS instance
[log] [2019-02-19T06:41:57.010Z] Getting article ids for [namespace=] 
[log] [2019-02-19T06:41:57.551Z] Getting article ids for [namespace=]  (from Malakoff_(Hauts-de-Seine))
[error] [2019-02-19T06:41:58.444Z] Error: Failed to parse JSON response
    at resps.reduce.pages (/usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:66:43)
    at Array.reduce (<anonymous>)
    at /usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:63:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] [2019-02-19T06:41:58.667Z] Error: Failed to parse JSON response
    at resps.reduce.pages (/usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:66:43)
    at Array.reduce (<anonymous>)
    at /usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:63:42
    at process._tickCallback (internal/process/next_tick.js:68:7)
[error] [2019-02-19T06:41:58.864Z] Error: Failed to parse JSON response
    at resps.reduce.pages (/usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:66:43)
    at Array.reduce (<anonymous>)
    at /usr/local/lib/node_modules/mwoffliner/lib/queues/redirectQueue.js:63:42
```

**Comment by ISNIT0** [comment]
Which IP is this from? With the exact same command it works fine for me. I guess the you're getting HTML error pages instead of JSON back?

**Comment by ISNIT0** [comment]
You will get more info about the error using `--verbose`

**Comment by ISNIT0** [comment]
@kelson42 Still unable to reproduce this

**Comment by ISNIT0** [comment]
@kelson42  👈

**Comment by ISNIT0** [comment]
I can scrape BM on my development machine and my vps
