### ISSUE TITLE
Error offlining co.wikibooks.org

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#607]
```
Traceback (most recent call last):
  File "/usr/src/app/operations/run_mwoffliner.py", line 37, in execute
    links={self.redis_container_name: 'redis'}, name='mwoffliner_{}'.format(self.task_id))
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 814, in run
    container, exit_status, command, image, out
docker.errors.ContainerError: Command 'mwoffliner --mwUrl=https://co.wikibooks.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --withZimFullTextIndex --useCache --deflateTmpHtml --redis=redis://redis --outputDirectory=/output' in image 'openzim/mwoffliner:1.7.1' returned non-zero exit status 2: b'Couldn\'t find strings file for [co], falling back to [en]
[error] [2019-02-26T06:19:58.104Z] Absolutely unable to retrieve async. URL: https://co.wikibooks.org/wiki/Mediawiki:offline.css?action=raw
[error] [2019-02-26T06:19:59.689Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.692Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.694Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.697Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.700Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.702Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.704Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.756Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.760Z] Error handling json response from api. Error: No HTML was found
[error] [2019-02-26T06:19:59.773Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
[error] [2019-02-26T06:19:59.779Z] Error handling json response from api. TypeError: Cannot read property \'displaytitle\' of undefined
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.789Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.789Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.795Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.804Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.804Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.841Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.861Z] Error handling json response from api. Error: No HTML was found
Error by retrieving article: HTTP 404
[error] [2019-02-26T06:19:59.943Z] Error handling json response from api. Error: No HTML was found
Failed to run mwoffliner after [5s]: "Failed to build successfuly the ZIM file /output/wikibooks_co_all_nopic_2019-02.zim (Error when executing zimwriterfs)"
'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 67, in run
    self.retry(exc=e, countdown=600)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 667, in retry
    raise_with_context(exc)
  File "/usr/src/app/tasks/mwoffliner.py", line 52, in run
    offliner_stdout = run_mwoffliner.execute()
  File "/usr/src/app/operations/run_mwoffliner.py", line 43, in execute
    raise OfflinerError(code='docker.ContainerError', stderr=e.stderr)
operations.base.OfflinerError
```

**Comment by ISNIT0** [comment]
@automactic Which version of mowffliner are you using?

**Comment by ISNIT0** [comment]
@automactic I'm not getting this same error on `master`, I guess it's been fixed in all the `1.8.0` changes 😄

**Comment by ISNIT0** [comment]
@kelson42 This is closed, but you've assigned it to me. Was that deliberate?

**Comment by kelson42** [comment]
@ISNIT0 Yes, just to know who handles what
