### ISSUE TITLE
Couldn't find strings file for xx, falling back to [en]

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#608]
This happens for a lot of language, wiki-site combos. An example can be seen below.

```
Traceback (most recent call last):
  File "/usr/src/app/operations/run_mwoffliner.py", line 37, in execute
    links={self.redis_container_name: 'redis'}, name='mwoffliner_{}'.format(self.task_id))
  File "/usr/local/lib/python3.6/site-packages/docker/models/containers.py", line 814, in run
    container, exit_status, command, image, out
docker.errors.ContainerError: Command 'mwoffliner --mwUrl=https://bi.wikibooks.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --withZimFullTextIndex --useCache --deflateTmpHtml --redis=redis://redis --outputDirectory=/output' in image 'openzim/mwoffliner:1.7.1' returned non-zero exit status 2: b'Couldn\'t find strings file for [bi], falling back to [en]\n[error] [2019-02-26T05:19:01.770Z] Absolutely unable to retrieve async. URL: https://bi.wikibooks.org/wiki/Mediawiki:offline.css?action=raw\nError by retrieving article: HTTP 404\n[error] [2019-02-26T05:19:03.867Z] Error handling json response from api. Error: No HTML was found\nFailed to run mwoffliner after [5s]: "Failed to build successfuly the ZIM file /output/wikibooks_bi_all_nopic_2019-02.zim (Error when executing zimwriterfs)"\n'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 382, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 641, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/tasks/mwoffliner.py", line 67, in run
    self.retry(exc=e, countdown=600)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 667, in retry
    raise_with_context(exc)
  File "/usr/src/app/tasks/mwoffliner.py", line 52, in run
    offliner_stdout = run_mwoffliner.execute()
  File "/usr/src/app/operations/run_mwoffliner.py", line 43, in execute
    raise OfflinerError(code='docker.ContainerError', stderr=e.stderr)
operations.base.OfflinerError
```

**Comment by automactic** [comment]
Maybe related to #579? feel free to close if duplicate

**Comment by ISNIT0** [comment]
This is because there are no translations :) https://github.com/openzim/mwoffliner/tree/master/translation

**Comment by ISNIT0** [comment]
@kelson42 Said he would import translations

**Comment by kelson42** [comment]
@ISNIT0 You are right, but not translation means it should fallback to English.

**Comment by ISNIT0** [comment]
Hence `Couldn't find strings file for xx, falling back to [en] ` :)

**Comment by kelson42** [comment]
@ISNIT0 OK, but it seems it crashes! see `returned non-zero exit status 2`

**Comment by ISNIT0** [comment]
This wiki is closed, but I'm not seeing this error any more on `master`
![image](https://user-images.githubusercontent.com/5173131/55494954-22992880-563c-11e9-865f-50dc2ccaa80c.png)

**Comment by kelson42** [comment]
@ISNIT0 OK, but the fact that the wiki is closed just mean it is not editable anymore. Should not have any impact on mwoffliner.
