### ISSUE TITLE
Exited with status 2 when offline got.wikibooks.org

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#623]
```
docker.errors.ContainerError: Command 'mwoffliner --mwUrl=https://got.wikibooks.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --useCache --addNamespaces=4 --redis=redis://redis --outputDirectory=/output' in image 'openzim/mwoffliner:1.8.0' returned non-zero exit status 2: b'Failed to run mwoffliner after [4s]: { Error: Request failed with status code 404
    at createError (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/usr/local/lib/node_modules/mwoffliner/node_modules/axios/lib/adapters/http.js:201:11)
    at Unzip.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { \'0\': [Function: transformRequest] },
     transformResponse: { \'0\': [Function: transformResponse] },
     timeout: 60000,
     xsrfCookieName: \'XSRF-TOKEN\',
     xsrfHeaderName: \'X-XSRF-TOKEN\',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: \'application/json, text/plain, */*\',
        accept:
         \'text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\',
        \'cache-control\': \'public, max-stale=2678400\',
        \'accept-encoding\': \'gzip, deflate\',
        \'user-agent\': \'MWOffliner/HEAD (contact@kiwix.org)\',
        cookie: \'\' },
     method: \'get\',
     url: \'https://got.wikibooks.org/wiki/\',
     responseType: \'arraybuffer\',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: \'\',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: \'got.wikibooks.org\',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: \'got.wikibooks.org\',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: \'\',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 689,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 7827,
        [Symbol(kBytesWritten)]: 309,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: \'got.wikibooks.org\',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: \'got.wikibooks.org\',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: \'\',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 689,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 7827,
        [Symbol(kBytesWritten)]: 309,
        [Symbol(connect-options)]: [Object] },
     _header:
      \'GET /wiki/Haubidaseido(ac) HTTP/1.1\\r\
accept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\\r\
cache-control: public, max-stale=2678400\\r\
accept-encoding: gzip, deflate\\r\
user-agent: MWOffliner/HEAD (contact@kiwix.org)\\r\
cookie: \\r\
Host: got.wikibooks.org\\r\
Connection: close\\r\
\\r\
\',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: \'https:\',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: \'GET\',
     path: \'/wiki/Haubidaseido(ac)\',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: \'1.1\',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: \'\',
        method: null,
        statusCode: 404,
        statusMessage: \'Not Found\',
        client: [TLSSocket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: \'https://got.wikibooks.org/wiki/Haubidaseido(ac)\',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _ended: true,
        _ending: true,
        _redirectCount: 1,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: \'https://got.wikibooks.org/wiki/Haubidaseido(ac)\',
        _isRedirect: true },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        \'cache-control\': [Array],
        \'accept-encoding\': [Array],
        \'user-agent\': [Array],
        cookie: [Array],
        host: [Array] } },
  response:
   { status: 404,
     statusText: \'Not Found\',
     headers:
      { date: \'Sat, 16 Mar 2019 00:42:26 GMT\',
        \'content-type\': \'text/html; charset=UTF-8\',
        \'content-length\': \'5633\',
        connection: \'close\',
        server: \'mw1321.eqiad.wmnet\',
        \'x-content-type-options\': \'nosniff\',
        p3p:
         \'CP="This is not a P3P policy! See https://got.wikibooks.org/wiki/Special:CentralAutoLogin/P3P for more info."\',
        \'x-powered-by\': \'HHVM/3.18.6-dev\',
        \'content-language\': \'got\',
        \'content-security-policy-report-only\':
         \'script-src \\\'unsafe-eval\\\' \\\'self\\\' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org \\\'unsafe-inline\\\'; default-src \\\'self\\\' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org; style-src \\\'self\\\' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org \\\'unsafe-inline\\\'; report-uri /w/api.php?action=cspreport&format=json&reportonly=1&\',
        \'backend-timing\': \'D=146696 t=1552696943631464\',
        vary: \'Accept-Encoding,Cookie,Authorization,X-Seven\',
        \'x-varnish\': \'930826483, 935739438 972666808\',
        via: \'1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)\',
        age: \'3\',
        \'x-cache\': \'cp1089 miss, cp1085 hit/10\',
        \'x-cache-status\': \'hit-front\',
        \'server-timing\': \'cache;desc="hit-front"\',
        \'strict-transport-security\': \'max-age=106384710; includeSubDomains; preload\',
        \'set-cookie\': [Array],
        \'x-analytics\': \'https=1\',
        \'x-client-ip\': \'172.16.7.221\',
        \'cache-control\': \'private, s-maxage=0, max-age=0, must-revalidate\' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: \'XSRF-TOKEN\',
        xsrfHeaderName: \'X-XSRF-TOKEN\',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: \'get\',
        url: \'https://got.wikibooks.org/wiki/\',
        responseType: \'arraybuffer\',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: \'\',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         \'GET /wiki/Haubidaseido(ac) HTTP/1.1\\r\
accept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\\r\
cache-control: public, max-stale=2678400\\r\
accept-encoding: gzip, deflate\\r\
user-agent: MWOffliner/HEAD (contact@kiwix.org)\\r\
cookie: \\r\
Host: got.wikibooks.org\\r\
Connection: close\\r\
\\r\
\',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: \'GET\',
        path: \'/wiki/Haubidaseido(ac)\',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 3e 0a 3c 68 74 6d 6c 20 63 6c 61 73 73 3d 22 63 6c 69 65 6e 74 2d 6e 6f 6a 73 22 20 6c 61 6e 67 3d 22 67 6f ... > } }


**********

Request failed with status code 404

**********
```

**Comment by ISNIT0** [comment]
I'm not sure what's going on here...
Hitting the url (`https://got.wikibooks.org/wiki/`) with `wget` gives a 404, but `curl` and my web browser are fine...
Any thoughts?

Worth noting that the url redirects to `https://got.wikibooks.org/wiki/Haubidaseido(ac)`. I don't see why this should cause an issue here though.

**Comment by kelson42** [comment]
I see no `404`

```
$ curl --dump-header /tmp/headers "https://got.wikibooks.org/wiki/" && cat /tmp/headers
HTTP/2 301 
date: Sat, 16 Mar 2019 15:48:33 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: https://got.wikibooks.org/wiki/Haubidaseido(ac)
server: mw1261.eqiad.wmnet
x-powered-by: HHVM/3.18.6-dev
p3p: CP="This is not a P3P policy! See https://got.wikibooks.org/wiki/Special:CentralAutoLogin/P3P for more info."
x-content-type-options: nosniff
last-modified: Sat, 16 Mar 2019 15:46:56 GMT
backend-timing: D=27321 t=1552751216057489
vary: Accept-Encoding,X-Forwarded-Proto,Cookie,Authorization,X-Seven
x-varnish: 124651907, 487045827 494346346, 921209046 899997707
via: 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)
age: 96
x-cache: cp1089 pass, cp3030 hit/1, cp3041 hit/2
x-cache-status: hit-front
server-timing: cache;desc="hit-front"
strict-transport-security: max-age=106384710; includeSubDomains; preload
set-cookie: WMF-Last-Access=16-Mar-2019;Path=/;HttpOnly;secure;Expires=Wed, 17 Apr 2019 12:00:00 GMT
set-cookie: WMF-Last-Access-Global=16-Mar-2019;Path=/;Domain=.wikibooks.org;HttpOnly;secure;Expires=Wed, 17 Apr 2019 12:00:00 GMT
x-analytics: https=1;nocookies=1
x-client-ip: 2a02:168:6062:0:4f79:59d4:dda9:8755
cache-control: private, s-maxage=0, max-age=0, must-revalidate
set-cookie: GeoIP=CH:ZH:Zurich:47.37:8.55:v4; Path=/; secure; Domain=.wikibooks.org

```

**Comment by ISNIT0** [comment]
@kelson42 Yes, `curl` is fine, but `wget` is not

**Comment by kelson42** [comment]
@ISNIT0 What do you do/get exactly with `wget`?

**Comment by ISNIT0** [comment]
```
➜  ~ wget https://got.wikibooks.org/wiki
--2019-03-16 16:03:16--  https://got.wikibooks.org/wiki
Resolving got.wikibooks.org (got.wikibooks.org)... 91.198.174.192
Connecting to got.wikibooks.org (got.wikibooks.org)|91.198.174.192|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://got.wikibooks.org/wiki/Haubidaseido(ac) [following]
--2019-03-16 16:03:16--  https://got.wikibooks.org/wiki/Haubidaseido(ac)
Reusing existing connection to got.wikibooks.org:443.
HTTP request sent, awaiting response... 404 Not Found
2019-03-16 16:03:16 ERROR 404: Not Found.
```

**Comment by kelson42** [comment]
Indeee, I have open a ticket upstream https://phabricator.wikimedia.org/T218520

**Comment by kelson42** [comment]
@ISNIT0 Could we show the default "selection page" if the homepage returns 404.

**Comment by ISNIT0** [comment]
This would be a rather large amount of work to implement, but also in this case, there is a main page: Haubidaseido(ac)

**Comment by kelson42** [comment]
@ISNIT0 This page does not exist, otherwise you would not get a HTTP 404 error.

**Comment by ISNIT0** [comment]
@kelson42 
It's a `301` in the same way that
`https://en.wikipedia.org/wiki/` redirects to `https://en.wikipedia.org/wiki/Main_Page

The redirect target, https://got.wikibooks.org/wiki/Haubidaseido(ac) is a valid url. Curl can follow the redirect, as can my browser. It's wget and the js http client that can't follow

**Comment by kelson42** [comment]
> @kelson42
> It's a `301` in the same way that
> `https://en.wikipedia.org/wiki/` redirects to `https://en.wikipedia.org/wiki/Main_Page`

It's not
```
$ curl -I "https://got.wikibooks.org/wiki/Haubidaseido(ac)"
HTTP/2 404 
date: Wed, 20 Mar 2019 07:35:54 GMT
content-type: text/html; charset=UTF-8
server: mw1333.eqiad.wmnet
x-content-type-options: nosniff
p3p: CP="This is not a P3P policy! See https://got.wikibooks.org/wiki/Special:CentralAutoLogin/P3P for more info."
x-powered-by: HHVM/3.18.6-dev
content-language: got
content-security-policy-report-only: script-src 'unsafe-eval' 'self' meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org 'unsafe-inline'; default-src 'self' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org; style-src 'self' data: blob: upload.wikimedia.org https://commons.wikimedia.org meta.wikimedia.org *.wikimedia.org *.wikipedia.org *.wikinews.org *.wiktionary.org *.wikibooks.org *.wikiversity.org *.wikisource.org wikisource.org *.wikiquote.org *.wikidata.org *.wikivoyage.org *.mediawiki.org wikimedia.org 'unsafe-inline'; report-uri /w/api.php?action=cspreport&format=json&reportonly=1&
backend-timing: D=99763 t=1553067022210307
vary: Accept-Encoding,Cookie,Authorization,X-Seven
x-varnish: 781166973, 519221212, 574346441 571881745
via: 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1), 1.1 varnish (Varnish/5.1)
age: 332
x-cache: cp1089 pass, cp3040 miss, cp3032 hit/1
x-cache-status: hit-front
server-timing: cache;desc="hit-front"
strict-transport-security: max-age=106384710; includeSubDomains; preload
set-cookie: WMF-Last-Access=20-Mar-2019;Path=/;HttpOnly;secure;Expires=Sun, 21 Apr 2019 00:00:00 GMT
set-cookie: WMF-Last-Access-Global=20-Mar-2019;Path=/;Domain=.wikibooks.org;HttpOnly;secure;Expires=Sun, 21 Apr 2019 00:00:00 GMT
x-analytics: https=1;nocookies=1
x-client-ip: 163.172.47.33
cache-control: private, s-maxage=0, max-age=0, must-revalidate
set-cookie: GeoIP=FR:PDL:La_Tessoualle:47.00:-0.85:v4; Path=/; secure; Domain=.wikibooks.org
```

**Comment by ISNIT0** [comment]
Oh, okay.
I thought I was being shown some actual content. Probably not helpful I don't even have a valid font installed!
My mistake

**Comment by kelson42** [comment]
@automactic This wiki like a few other one is closed. You can see it in the matrix json output. https://en.wikipedia.org/w/api.php?action=sitematrix&formatversion=2. Can you please secure that none of the closed wiki is scheduled?

**Comment by automactic** [comment]
Removed all sites with `closed: True`.

I have to rant a bit, but that is some seriously horrible json design right there in the site matrix json.

I you don't pass `formatversion=2`  in the URL, the response is `closed: ""`; if you add `formatversion=2`, the response is `closed: True`. The former case, most programming language will treat it as falsy, so not closed.

**Comment by kelson42** [comment]
@automactic Indeed! But thank you very much to have done the necessary to fix the problem.
