### ISSUE TITLE
The url argument must be of type string. Received type object

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#651]
command: `mwoffliner --mwUrl=https://br.wikipedia.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --useCache --redis=redis://redis --outputDirectory=/output`

exit code: 2

~~stdout~~ stderr
```
Failed to run mwoffliner after [2711s]: {
	"stack": "TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received type object\n    at Url.parse (url.js:154:11)\n    at Object.urlParse [as parse] (url.js:148:13)\n    at Object.getFullUrl (/usr/local/lib/node_modules/mwoffliner/lib/util/misc.js:89:35)\n    at /usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:216:33\n    at Array.forEach (<anonymous>)\n    at treatMedias (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:210:12)\n    at /usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:180:29\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:32:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:13:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:3:12)\n    at processArticleHtml (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:173:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:90:42)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:32:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/util/saveArticles.js:13:53)",
	"message": "The \"url\" argument must be of type string. Received type object"
}


**********

The "url" argument must be of type string. Received type object

**********


```

**Comment by automactic** [comment]
I am seeing this a lot

**Comment by ISNIT0** [comment]
What stage was the scrape in? (downloading files, etc)

**Comment by ISNIT0** [comment]
I've added some logging for 1.8.2, but I'm not really sure where this comes from

**Comment by automactic** [comment]
Zimfarm scheduled tasks that has failed because of this so far in April
```
["Wikibooks_ml", "Wikipedia_br", "Wikipedia_mk", "Wikibooks_is", "Wikibooks_it", "Wikiversity_fr", "Wikibooks_fr", "Wikiversity_cs", "Wikibooks_nl", "Wikipedia_hr", "Wikibooks_en", "Wikiversity_es", "Wikiversity_ar", "Wikibooks_he", "Wikiversity_fi", "Wikipedia_hi", "Wikipedia_id", "Wikibooks_de", "Wikibooks_ca", "Wikiversity_en", "Wikiversity_de", "Wikinews_ca", "Wikiversity_it", "Wikinews_el"]
```

**Comment by automactic** [comment]
I will see if I can produce a full stdout to help debug

**Comment by kelson42** [comment]
@ISNIT0 What is the status on this problem?

**Comment by automactic** [comment]
No longer seems to see this problem in 1.8.4
