### ISSUE TITLE
Error: limit must be a finite integer >= 1

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#653]
Command
```
mwoffliner --mwUrl=https://wikem.org/ --adminEmail=contact@kiwix.org --format=nopic --format=novid --useCache --speed=0.1 --redis=redis://redis --outputDirectory=/output
```

Stderr
```
Failed to run mwoffliner after [6s]: {
	"stack": "Error: limit must be a finite integer >= 1\n    at Object.mapLimit (/usr/local/lib/node_modules/mwoffliner/lib/util/mapLimit.js:5:15)\n    at getArticleIdsForNamespaces (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:257:15)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:59:46)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:32:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:13:53)\n    at /usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:7:71\n    at new Promise (<anonymous>)\n    at __awaiter (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:3:12)\n    at Object.getArticleIds (/usr/local/lib/node_modules/mwoffliner/lib/util/redirects.js:46:12)\n    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:553:54)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:46:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:27:53)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:18:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "limit must be a finite integer >= 1"
}


**********

limit must be a finite integer >= 1

**********


```

**Comment by ISNIT0** [comment]
The speed parameter is now used as a parallelisation parameter, so it doesn't make sense for it to be a non-integer.

We may also remove this anyway https://github.com/openzim/mwoffliner/issues/647

**Comment by kelson42** [comment]
@ISNIT0 Can you please just round the number given?

**Comment by kelson42** [comment]
@automactic I would try to remove the --speed paramter for now. mwoffliner should be able to deal without anyway.

**Comment by automactic** [comment]
ok lemme try

**Comment by automactic** [comment]
removing speed worked

**Comment by kelson42** [comment]
ok, then lets go with it!
