### ISSUE TITLE
Unable to save article detail information to redis

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#658]
command:
```
mwoffliner --mwUrl=https://ar.wikipedia.org --adminEmail=contact@kiwix.org --format=nopic --format=novid --useCache --customMainPage=مستخدم:Stephane_(Kiwix)/Landing --redis=redis://redis --outputDirectory=/output
```
stderr
```
/usr/local/lib/node_modules/mwoffliner/lib/redis.js:168
                    throw new Error("Unable to save article detail information to redis: " + error);
                    ^

Error: Unable to save article detail information to redis: ReplyError: ERR Protocol error: invalid multibulk length
    at /usr/local/lib/node_modules/mwoffliner/lib/redis.js:168:27
    at Object.callbackOrEmit [as callback_or_emit] (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/lib/utils.js:89:9)
    at RedisClient.return_error (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:706:11)
    at JavascriptRedisParser.returnError (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:196:18)
    at JavascriptRedisParser.execute (/usr/local/lib/node_modules/mwoffliner/node_modules/redis-parser/lib/parser.js:572:12)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:274:27)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
```

Zimfarm scheduled tasks that has failed because of this so far in April
```
["Wiktionary_ku", "Wiktionary_nl", "Wikipedia_ar", "Wiktionary_de", "Wikipedia_es", "Wikipedia_ja", "Wikipedia_it", "Wiktionary_lt"]
```

**Comment by ISNIT0** [comment]
I've reduced the number of articles we write at one to Redis for other reasons, but I believe this will be fixed (not tested)

**Comment by ISNIT0** [comment]
We now write a maximum of 50 articles at a time to Redis
