### ISSUE TITLE
Cannot read property 'normalized' of undefined

### ISSUE THREAD

**Issue by automactic** [openzim/mwoffliner#698]
Wildly exists among all the errors

stderr:
```
Failed to run mwoffliner after [6s]: {
	"stack": "TypeError: Cannot read property 'normalized' of undefined\n    at Object.normalizeMwResponse (/usr/local/lib/node_modules/mwoffliner/lib/util/mw-api.js:125:32)\n    at Downloader.<anonymous> (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:231:54)\n    at step (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:43:23)\n    at Object.next (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:24:53)\n    at fulfilled (/usr/local/lib/node_modules/mwoffliner/lib/Downloader.js:15:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "Cannot read property 'normalized' of undefined"
}


**********

Cannot read property 'normalized' of undefined

**********
```

example: https://farm.openzim.org/tasks/5cc058af86ccd8002022123e

**Comment by kelson42** [comment]
@ISNIT0 It looks like that around 50% of all failures in zimfarm with 1.8.4 are caused by this bug.

**Comment by null2014** [comment]
it is  label‘s bug？

**Comment by PLQin** [comment]
删除掉 `layouts\default.vue` 中的 `script` 试试 

<small>Try deleting the 'script' in 'layouts\default.vue'</small>
