### ISSUE TITLE
Mobile layout

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#7]
More and more users access our ZIM files of Mediawiki on mobile. We need to create files which look good on both desktop and mobile. In a way something similar like http://en.m.wikipedia.org/

The MWoffliner should be able for any Mediawiki to transform the DOM/CSS in a way which make it more mobile friendly.

Here are a few pointers:
- Mobile end points (Android app): https://en.wikipedia.org/api/rest_v1/?doc#/Mobile
- Mobile Content Service transformations: https://github.com/wikimedia/mediawiki-services-mobileapps/tree/master/lib/transformations
- Android app styles: https://github.com/wikimedia/apps-android-wikipedia/blob/3d805595044091a9862a1935bcc278f547dcef47/app/src/main/assets/styles.css

**Comment by kelson42** [comment]
New mobile end points: https://lists.wikimedia.org/pipermail/wikitech-l/2017-February/087662.html

**Comment by kelson42** [comment]
@Skylsmoi under certain condition, mwoffliner seems to simply be stuck in the middle of the process. This seems to happen with the --articleList option (even if I'm not convinced this is the trigger). This is running mwoffliner 1.2.2 (so git master head).

I have tested with version 1.2.1 (so before the whole --mobileLayout merge) and it seems to work fine. Using a recent version of node does not help (7.10.0).

Here is my test case:

```
 #!/bin/sh                                                                                                                                                                                                   

ZIM2INDEX=/srv/upload/zim2index/
SCRIPT=`readlink -f $0/../`
SCRIPT_DIR=`dirname "$SCRIPT"`
ARGS="--withZimFullTextIndex --adminEmail=contact@kiwix.org --deflateTmpHtml --verbose --skipHtmlCache --skipCacheCleaning"
MWOFFLINER="mwoffliner --format= --format=nopic $ARGS"
MWMATRIXOFFLINER="mwmatrixoffliner --mwUrl=https://meta.wikimedia.org/ $ARGS"


# Wikipedia ES Venezuela                                                                                                                                                                                    
wget "https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/320px-Flag_of_Venezuela.svg.png" -O "$SCRIPT_DIR/venezuela.png" &&
$MWOFFLINER --mwUrl="https://es.wikipedia.org/" --parsoidUrl="https://es.wikipedia.org/api/rest_v1/page/html/" --customZimTitle="Enciclopedia de Venezuela" --customZimDescription="Selección de artículos \
de Wikipedia para Venezuela" --customMainPage="Wikipedia:Wikipedia_en_CD/Selección_de_artículos_para_Venezuela/Main" --customZimFavicon="$SCRIPT_DIR/venezuela.png" --articleList="$SCRIPT_DIR/selections/v\
enezuela.lst"

```

I have also tested for an other selection of articles and I had similar symptoms... scripts just get stuck.

**Comment by kelson42** [comment]
@Skylsmoi I have merged your last fix and published version 1.2.3, but I'm still unable to run the example given in the previous message with node 7.10.0. The scripts stops (freeze) after a few download of pages, here are the last lines (with stranges log entries)

```
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/20px-Flag_of_the_United_States.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/20px-Flag_of_the_Dominican_Republic.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/20px-Flag_of_Paraguay.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/20px-Flag_of_Argentina.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/20px-Flag_of_Colombia.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/20px-Flag_of_Panama.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/20px-Flag_of_Ecuador.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/20px-Flag_of_El_Salvador.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/20px-Flag_of_Guatemala.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/20px-Flag_of_Croatia.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/20px-Flag_of_Bulgaria.svg.png
Dumped successfully article .ve
Getting article from https://es.wikipedia.org/api/rest_v1/page/html/%C2%A1Qu%C3%A9_clase_de_amor!/99099996
Js dependencies of ¡A_que_te_ríes! : startup,jquery,mediawiki,site,ext.cite.a11y,mediawiki.toc
Css dependencies of ¡A_que_te_ríes! : ext.cite.a11y,mediawiki.toc,ext.cite.styles,skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mediawiki.page.gallery.styles|mobile.app.pagestyles.android|mediawiki.skinning.content.parsoid
created dep jsConfigVars.js for article ¡A_que_te_ríes!
created dep site for article .ve
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Newworldmap.svg/22px-Newworldmap.svg.png
created dep mediawiki for article .ve
created dep skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mediawiki.page.gallery.styles|mobile.app.pagestyles.android|mediawiki.skinning.content.parsoid for article .ve
Treating and saving article ¡Qué_clase_de_amor! at /srv/kiwix-maintenance/mwoffliner/tmp/wikipedia_es_venezuela_2017-05/¡Qué_clase_de_amor!.html...
Saving article ¡Qué_buena_se_puso_Lola!...
created dep startup for article .ve
Dumped successfully article ¡Qué_buena_se_puso_Lola!
Getting article from https://es.wikipedia.org/api/rest_v1/page/html/%C2%BFPor_qu%C3%A9_no_te_callas%3F/98310027
Saving article ¡A_que_te_ríes!...
(node:12378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'displaytitle' of undefined
Js dependencies of ¡Qué_clase_de_amor! : startup,jquery,mediawiki,site,ext.cite.a11y,mediawiki.toc
Css dependencies of ¡Qué_clase_de_amor! : ext.cite.a11y,mediawiki.toc,ext.cite.styles,skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mediawiki.page.gallery.styles|mobile.app.pagestyles.android|mediawiki.skinning.content.parsoid
created dep jsConfigVars.js for article ¡Qué_clase_de_amor!
Dumped successfully article ¡A_que_te_ríes!
Getting article from https://es.wikipedia.org/api/rest_v1/page/html/%C2%A1Qu%C3%A9_locura!/98821748
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/20px-Flag_of_Venezuela.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/20px-Flag_of_Uruguay.svg.png
created dep jquery for article .ve
Treating and saving article ¡Qué_locura! at /srv/kiwix-maintenance/mwoffliner/tmp/wikipedia_es_venezuela_2017-05/¡Qué_locura!.html...
Saving article ¡Qué_clase_de_amor!...
Dumped successfully article ¡Qué_clase_de_amor!
Getting article from https://es.wikipedia.org/api/rest_v1/page/html/%C2%BFQu%C3%A9_pas%C3%B3_con_Jacqueline%3F/95373811
Js dependencies of ¡Qué_locura! : startup,jquery,mediawiki,site,ext.cite.a11y,mediawiki.toc
Css dependencies of ¡Qué_locura! : ext.cite.a11y,mediawiki.toc,ext.cite.styles,skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mediawiki.page.gallery.styles|mobile.app.pagestyles.android|mediawiki.skinning.content.parsoid
created dep jsConfigVars.js for article ¡Qué_locura!
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_UNASUR.svg/20px-Flag_of_UNASUR.svg.png
Cache hit for http://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Spanish_Wikiquote.SVG/12px-Spanish_Wikiquote.SVG.png
Saving article ¡Qué_locura!...
(node:12378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): TypeError: Cannot read property 'displaytitle' of undefined
Dumped successfully article ¡Qué_locura!
Getting article from https://es.wikipedia.org/api/rest_v1/page/html/%C2%BFQui%C3%A9n_quiere_ser_millonario%3F/99208816
(node:12378) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): TypeError: Cannot read property 'displaytitle' of undefined

```

**Comment by kelson42** [comment]
@Skylsmoi I have merged and tested your last code. Now it does not die anymore but we still have problems.

First of all and just for the record, I have put all the errors in mwoffliner on STDERR using console.error() instead of console.log()... to easily be able to make the difference with usual logs.

Then I just have take the last article of the venezuela.lst using

`tail venezuela.lst > venezuela.short.lst `

and used the new file in mwoffliner3_dump.sh ... so it is easier to make the run.

Here is the result:
```
$ ./mwoffliner3_dump.sh  > /dev/null
--2017-05-19 21:41:09--  https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Venezuela.svg/320px-Flag_of_Venezuela.svg.png
Resolving upload.wikimedia.org (upload.wikimedia.org)... 208.80.154.240, 2620:0:861:ed1a::2:b
Connecting to upload.wikimedia.org (upload.wikimedia.org)|208.80.154.240|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4148 (4.1K) [image/png]
Saving to: ‘./venezuela.png’

100%[==================================================================================================================================================================>] 4'148       --.-K/s   in 0s      

2017-05-19 21:41:09 (12.2 MB/s) - ‘./venezuela.png’ saved [4148/4148]

(node:1350) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1350) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:1350) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Unable to download content [1] https://es.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [2] https://es.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [3] https://es.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Absolutly unable to retrieve async. URL: Unable to download content [3] https://es.wikipedia.org/wiki/Mediawiki:offline.css?action=raw (statusCode=403).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-golden-star.png?ed948 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-silver-star.png?70a8c (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-problematic.png?f3177 (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-proofread.png?e81f9 (statusCode=404).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).
Unable to download content [1] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).
Unable to download content [2] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-validated.png?6232c (statusCode=404).
Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).
Absolutly unable to retrieve async. URL: Unable to download content [3] http://es.wikipedia.org/w/extensions/WikimediaBadges/resources/images/badge-digitaldocument.png?d1c50 (statusCode=404).
Error handling json response from api.  TypeError: Cannot read property 'displaytitle' of undefined
    at fetch.then.then.json (/usr/local/lib/node_modules/mwoffliner/lib/mwoffliner.lib.js:1747:83)
    at process._tickCallback (internal/process/next_tick.js:109:7)
zimwriterfs: unable to find welcome page at '/srv/kiwix-maintenance/mwoffliner/tmp/wikipedia_es_venezuela.short_2017-05/Wikipedia:Wikipedia_en_CD_Selección_de_artículos_para_Venezuela_Main.html'. --welcome path/value must be relative to HTML_DIRECTORY.
Failed to build successfuly the ZIM file /srv/kiwix-maintenance/mwoffliner/out/wikipedia_es_venezuela.short_2017-05.zim (Error when executing zimwriterfs)
``` 

I see two problems:
* The "Calling an asynchronous function without callback is deprecated." at the begining
* The "Error handling json response from api." which probably is the reason why the welcomepage is not written correctly to the disk.

**Comment by kelson42** [comment]
Works good now!!! :)
