### ISSUE TITLE
mwoffliner seems to not work with nodejs12 (new current version)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#707]
```
$ mwoffliner --mwUrl="https://no.wikipedia.org" --adminEmail="contact@kiwix.org" --format=nopic --format=novid --useCache --verbose
/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:15
        throw (err);
        ^

Error: Could not locate the bindings file. Tried:
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/12.0.0/linux/x64/nbind.node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Debug/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/Release/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Debug/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Debug/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/out/Release/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Release/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/build/default/nbind.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/compiled/12.0.0/linux/x64/nbind.js
    at findCompiledModule (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:83:15)
    at find (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:93:13)
    at Object.init (/usr/local/lib/node_modules/mwoffliner/node_modules/nbind/dist/nbind.js:104:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/binding.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
kelson@camber:/dev/shm/mwoffliner$ nodejs --version
v12.0.0
```

**Comment by kelson42** [comment]
```
$ find /usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/auto-top.gypi
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/auto.gypi
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/autogypi.json
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/obj.target
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/obj.target/nbind
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/obj.target/nbind/geni
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/obj.target/nbind/geni/symbols.txt
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps/Release
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps/Release/obj.target
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps/Release/obj.target/nbind
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps/Release/obj.target/nbind/geni
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/.deps/Release/obj.target/nbind/geni/symbols.txt.d
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/nbind
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/nbind/src
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Release/nbind/src/common.o.d.raw
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/config.gypi
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/Makefile
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/nbind.target.mk
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/build/binding.Makefile
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/nbind
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/nbind/src
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/build/native/binding.gyp
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/sources.gypi
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/.travis.yml
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/README.md
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/release.sh
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/.env
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/test.zim
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/.vscode
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/.vscode/settings.json
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/v8.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/dns.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/vm.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/perf_hooks.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/os.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/domain.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/README.md
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/stream.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/crypto.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/cluster.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/readline.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/index.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/assert.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/inspector.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/events.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/querystring.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/buffer.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/timers.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/console.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/module.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/fs.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/repl.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/https.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/util.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/zlib.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/path.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/constants.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/child_process.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/worker_threads.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/base.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/tls.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/url.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/process.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/punycode.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/net.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/tty.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/ts3.2
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/ts3.2/index.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/ts3.2/util.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/ts3.2/globals.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/globals.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/dgram.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/package.json
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/trace_events.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/http.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/LICENSE
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/http2.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/string_decoder.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/node_modules/@types/node/async_hooks.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/package.json
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/LICENSE
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/test.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/index.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/index.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Article.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimCreator.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/binding.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimReader.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/test.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/binding.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/Article.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/dist/ZimReader.d.ts
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/tsconfig.json
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download-libzim.js
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/libzim.so.4
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/libzim_linux-x86_64-4.0.5.tar.gz
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/writer
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/writer/article.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/writer/zimcreator.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/fileiterator.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/article.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/uuid.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/file.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/blob.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/fileheader.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/zim.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/search_iterator.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/error.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/include/zim/search.h
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/lib
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/lib/x86_64-linux-gnu
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/lib/x86_64-linux-gnu/libzim.so.4.0.5
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/download/lib/x86_64-linux-gnu/libzim.so.4
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/src
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/src/ZimCreator.cc
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/src/ZimReader.cc
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/src/Article.cc
/usr/local/lib/node_modules/mwoffliner/node_modules/@openzim/libzim/src/ExternalBuffer.hpp
```

**Comment by ISNIT0** [comment]
Pending this PR for nbind: https://github.com/charto/nbind/pull/130

**Comment by ISNIT0** [comment]
This is now pending a new release of nbind

**Comment by kelson42** [comment]
@ISNIT0 Do we have a ticket upstream to ask the release? That is important IMO.

**Comment by ISNIT0** [comment]
https://github.com/charto/nbind/issues/133

**Comment by ISNIT0** [comment]
Worst case we can use a git commit for a version (not ideal though)

**Comment by kelson42** [comment]
Pushing the ticket to 2.0 - nothing more we can do here.

**Comment by kelson42** [comment]
Depends of https://github.com/openzim/node-libzim/issues/31
