### ISSUE TITLE
Scraping of Wikivoyage stuck (at the end)

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#781]
```
mwoffliner --mwUrl=https://en.wikivoyage.org/ --adminEmail=kelson@kiwix.org --format=novid --format=nopic --verbose
```
and log

```
[info] [2019-06-06T16:19:57.838Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Kantara_castle_6.JPG/250px-Kantara_castle_6.JPG] from [13911] to [10050]
[info] [2019-06-06T16:19:57.839Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Aomori_bay_2007_APR.jpg/400px-Aomori_bay_2007_APR.jpg] from [8555] to [6079]
[info] [2019-06-06T16:19:57.944Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3._%D0%9F%D0%B8%D1%81%D0%BA%D0%B0%D1%80%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B5_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%BA%D0%BB%D0%B0%D0%B4%D0%B1%D0%B8%D1%89%D0%B5._%D0%92%D0%B5%D1%87%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B3%D0%BE%D0%BD%D1%8C..JPG/300px-%D0%A1%D0%B0%D0%BD%D0%BA%D1%82-%D0%9F%D0%B5%D1%82%D0%B5%D1%80%D0%B1%D1%83%D1%80%D0%B3._%D0%9F%D0%B8%D1%81%D0%BA%D0%B0%D1%80%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B5_%D0%BC%D0%B5%D0%BC%D0%BE%D1%80%D0%B8%D0%B0%D0%BB%D1%8C%D0%BD%D0%BE%D0%B5_%D0%BA%D0%BB%D0%B0%D0%B4%D0%B1%D0%B8%D1%89%D0%B5._%D0%92%D0%B5%D1%87%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B3%D0%BE%D0%BD%D1%8C..JPG] from [13987] to [9963]
[info] [2019-06-06T16:19:57.944Z] Downloading [http://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Orcas21_8x10.jpg/220px-Orcas21_8x10.jpg]
[info] [2019-06-06T16:19:58.028Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/First_Church_of_Lombard_%28Lombard%2C_Illinois%29_08.JPG/350px-First_Church_of_Lombard_%28Lombard%2C_Illinois%29_08.JPG] from [33457] to [23052]
[info] [2019-06-06T16:19:58.028Z] Downloading [http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Boats_moored_at_Kamperland.jpg/220px-Boats_moored_at_Kamperland.jpg]
[info] [2019-06-06T16:19:58.250Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Orcas21_8x10.jpg/220px-Orcas21_8x10.jpg] from [6629] to [4832]
[info] [2019-06-06T16:19:58.362Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Boats_moored_at_Kamperland.jpg/220px-Boats_moored_at_Kamperland.jpg] from [10888] to [5602]
[info] [2019-06-06T16:19:58.362Z] Downloading [http://upload.wikimedia.org/wikipedia/commons/b/b0/LocationGuinea.png]
[info] [2019-06-06T16:19:58.860Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/b/b0/LocationGuinea.png] from [5641] to [2831]
[info] [2019-06-06T16:19:58.861Z] Downloading [http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/SydneyTramwayMuseum_Phoenix_RNP.JPG/220px-SydneyTramwayMuseum_Phoenix_RNP.JPG]
[info] [2019-06-06T16:19:59.157Z] Compressed data from [http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/SydneyTramwayMuseum_Phoenix_RNP.JPG/220px-SydneyTramwayMuseum_Phoenix_RNP.JPG] from [15293] to [10733]
```

**Comment by ISNIT0** [comment]
What percentage of the way through the scrape was this?
And how log has it hung?

**Comment by kelson42** [comment]
@ISNIT0 I don't know, I just have the last entries of the log here. I will re-run it to see if the problem is sporadic.

**Comment by kelson42** [comment]
New try get stuck with

```
[info] [2019-06-06T17:58:22.582Z] Saved module [mediawiki]
[info] [2019-06-06T17:58:22.686Z] Saved module [mw.PopUpMediaTransform]
[info] [2019-06-06T17:58:22.687Z] Saved module [ext.scribunto.logs]
[info] [2019-06-06T17:58:22.689Z] Saved module [ext.tmh.thumbnail.styles]
[info] [2019-06-06T17:58:22.695Z] Saved module [mw.TMHGalleryHook.js]
[info] [2019-06-06T17:58:22.696Z] Saved module [mw.MediaWikiPlayer.loader]
[info] [2019-06-06T17:58:22.697Z] Saved module [ext.kartographer.frame]
[info] [2019-06-06T17:58:22.697Z] Saved module [mediawiki.ui.input]
[info] [2019-06-06T17:58:22.697Z] Saved module [ext.cite.ux-enhancements]
[info] [2019-06-06T17:58:22.698Z] Saved module [ext.scribunto.logs]
[info] [2019-06-06T17:58:22.698Z] Saved module [mw.PopUpMediaTransform]
[info] [2019-06-06T17:58:22.699Z] Saved module [ext.kartographer.frame]
[info] [2019-06-06T17:58:22.699Z] Saved module [mediawiki.page.gallery.styles]
[info] [2019-06-06T17:58:22.699Z] Saved module [mediawiki.ui.checkbox]
[info] [2019-06-06T17:58:22.699Z] Saved module [ext.inputBox.styles]
[info] [2019-06-06T17:58:22.699Z] Saved module [mw.TMHGalleryHook.js]
[info] [2019-06-06T17:58:22.699Z] Saved module [ext.cite.ux-enhancements]
[info] [2019-06-06T17:58:22.700Z] Saved module [mediawiki.page.gallery]
[info] [2019-06-06T17:58:22.700Z] Saved module [site]
[info] [2019-06-06T17:58:22.700Z] Saved module [ext.cite.styles]
[info] [2019-06-06T17:58:22.700Z] Saved module [ext.kartographer.style]
[info] [2019-06-06T17:58:22.701Z] Saved module [ext.kartographer.link]
[info] [2019-06-06T17:58:22.712Z] Saved module [skins.minerva.base.reset|skins.minerva.content.styles|ext.cite.style|mobile.app.pagestyles.android|mediawiki.page.gallery.styles|mediawiki.skinning.content.parsoid]
[info] [2019-06-06T17:58:23.075Z] Saved module [ext.kartographer.link]
[info] [2019-06-06T17:58:23.122Z] Saved module [mw.MediaWikiPlayer.loader]
[info] [2019-06-06T17:58:23.860Z] Saved module [jquery]
(node:9721) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at FunctionCall.call.retryIf [as retryPredicate_] (/usr/lib/node_modules/mwoffliner/lib/Downloader.js:372:52)
    at FunctionCall.handleFunctionCallback_ (/usr/lib/node_modules/mwoffliner/node_modules/backoff/lib/function_call.js:177:21)
    at /usr/lib/node_modules/mwoffliner/lib/Downloader.js:483:21
    at Generator.throw (<anonymous>)
    at rejected (/usr/lib/node_modules/mwoffliner/lib/Downloader.js:5:65)
(node:9721) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
(node:9721) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by kelson42** [comment]
After trying a third time, it dies with the same (last comment) message again.

**Comment by kelson42** [comment]
I have it also by scraping bm.wikipedia.org. So this is a general problem. Should be easy to reproduce.

**Comment by ISNIT0** [comment]
I can't reproduce this on bm.wikipedia.org, but the status error is fixe here: https://github.com/openzim/mwoffliner/commit/0fdd8fb8e6869ae5ab5a4f4d8d1d65fd2a429f76

**Comment by kelson42** [comment]
OK, then I guess I should close the ticket.
