### ISSUE TITLE
error offlining en.wiktionary.org

### ISSUE THREAD

**Issue by notaz** [openzim/mwoffliner#793]
`./mwoffliner_git/lib/cli.js --mwUrl=https://en.wiktionary.org --adminEmail=foo@bar.net --format="nopic,novid,nopdf" --customMainPage="Wiktionary:Main_Page"`

fails with

> Failed to run mwoffliner after [2180s]: {
>         "stack": "TypeError: (normalized[page.title] || page.title).replace is not a function\n    at Object.values.reduce (/home/notaz/src/mwoffliner/mwoffliner_git/lib/util/mw-api.js:91:66)\n    at Array.reduce (<anonymous>)\n    at Object.normalizeMwResponse (/home/notaz/src/mwoffliner/mwoffliner_git/lib/util/mw-api.js:90:10)\n    at Downloader.<anonymous> (/home/notaz/src/mwoffliner/mwoffliner_git/lib/Downloader.js:209:61)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/notaz/src/mwoffliner/mwoffliner_git/lib/Downloader.js:4:58)\n    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
>         "message": "(normalized[page.title] || page.title).replace is not a function"
> }
> 
> 
> **********
> 
> (normalized[page.title] || page.title).replace is not a function
>

**Comment by ISNIT0** [comment]
@notaz I believe this is fixed in `1.9.3`. Could you give it a go please?

**Comment by notaz** [comment]
Still getting it with 1.9.3.
```
Failed to run mwoffliner after [2441s]: {
        "stack": "TypeError: (normalized[page.title] || page.title || \"\").replace is not a function
    at Object.values.reduce (/home/notaz/src/mwoffliner/mwoffliner_git/lib/util/mw-api.js:91:72)
    at Array.reduce (<anonymous>)
    at Object.normalizeMwResponse (/home/notaz/src/mwoffliner/mwoffliner_git/lib/util/mw-api.js:90:10)
    at Downloader.<anonymous> (/home/notaz/src/mwoffliner/mwoffliner_git/lib/Downloader.js:210:61)
    at Generator.next (<anonymous>)
    at fulfilled (/home/notaz/src/mwoffliner/mwoffliner_git/lib/Downloader.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)",
        "message": "(normalized[page.title] || page.title || \"\").replace is not a function"
}
```

**Comment by kelson42** [comment]
Testing again with git master head.

**Comment by kelson42** [comment]
Still failing with:
```
[info] [2019-06-28T21:02:17.027Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos]
[info] [2019-06-28T21:02:17.729Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=2557375]
[info] [2019-06-28T21:02:18.399Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=2511686]
[info] [2019-06-28T21:02:19.141Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=1317578]
[info] [2019-06-28T21:02:19.851Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=700221]
[info] [2019-06-28T21:02:20.572Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=3320488]
[info] [2019-06-28T21:02:21.249Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=700198]
[info] [2019-06-28T21:02:21.963Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=2473054]
[info] [2019-06-28T21:02:22.675Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=530003]
[info] [2019-06-28T21:02:23.381Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constrangidos&picontinue=1737658]
[log] [2019-06-28T21:02:24.490Z] Got [500] articles from namespace [0]
[info] [2019-06-28T21:02:24.490Z] Getting JSON from [https://en.wiktionary.org/w/api.php?action=query&format=json&prop=redirects%7Crevisions%7Cpageimages&rdlimit=max&rdnamespace=0&rawcontinue=true&generator=allpages&gapfilterredir=nonredirects&gaplimit=max&gapnamespace=0&gapcontinue=constructive_criticisms]
Failed to run mwoffliner after [19569s]: {
	"stack": "TypeError: (normalized[page.title] || page.title || \"\").replace is not a function\n    at Object.values.reduce (/media/kelson/SOTOKI/mwoffliner/src/util/mw-api.ts:107:76)\n    at Array.reduce (<anonymous>)\n    at Object.normalizeMwResponse (/media/kelson/SOTOKI/mwoffliner/src/util/mw-api.ts:106:10)\n    at Downloader.<anonymous> (/media/kelson/SOTOKI/mwoffliner/src/Downloader.ts:208:42)\n    at Generator.next (<anonymous>)\n    at fulfilled (/media/kelson/SOTOKI/mwoffliner/src/Downloader.ts:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "(normalized[page.title] || page.title || \"\").replace is not a function"
}


```
