### ISSUE TITLE
Unable to scrape halachipedia.com

### ISSUE THREAD

**Issue by binyominzeev** [openzim/mwoffliner#810]
Hello,

I am trying to get halachipedia.com, when I get the following output:

```
bz@bz-HP-Laptop-15-bs1xx:~$ mwoffliner --mwUrl=http://www.halachipedia.com --adminEmail=szvbin*****@gmail.com --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php
[log] [2019-06-11T20:05:42.009Z] Using Tmp Directories: { outputDirectory: '/home/bz/out/',
  cacheDirectory: '/home/bz/cac/dumps-1560283542007/',
  dumpTmpDir: '/tmp/mwo-dump-1560283542009' }
[log] [2019-06-11T20:05:42.034Z] Getting text direction...
[log] [2019-06-11T20:05:42.035Z] Getting site info...
[log] [2019-06-11T20:05:42.036Z] Getting sub-title...
[log] [2019-06-11T20:05:45.404Z] Text direction is [ltr]
[log] [2019-06-11T20:05:54.298Z] Using a local MCS instance, couldn't find a remote one
[log] [2019-06-11T20:05:54.299Z] Starting Parsoid & MCS
{"name":"parsoid","hostname":"bz-HP-Laptop-15-bs1xx","pid":11677,"level":30,"levelPath":"info","msg":"loading ...","time":"2019-06-11T20:05:55.123Z","v":0}
{"name":"parsoid","hostname":"bz-HP-Laptop-15-bs1xx","pid":11677,"level":30,"levelPath":"info","msg":"ready on :8000","time":"2019-06-11T20:05:55.169Z","v":0}
{"name":"mcs","hostname":"bz-HP-Laptop-15-bs1xx","pid":11677,"level":30,"levelPath":"info","msg":"Worker 11677 listening on 0.0.0.0:6927","time":"2019-06-11T20:05:55.371Z","v":0}
[log] [2019-06-11T20:05:55.972Z] Worker [0] getting article range [0-50] of [1] [5000%]
[log] [2019-06-11T20:05:59.301Z] Got [500] articles from namespace [0]
[log] [2019-06-11T20:06:00.402Z] Got [257] articles from namespace [0]
[log] [2019-06-11T20:06:00.403Z] Doing dump
[log] [2019-06-11T20:06:00.404Z] Writing zim to [/home/bz/out/halachipedia_en_all_2019-06.zim]
[log] [2019-06-11T20:06:00.404Z] Flushing redis file store
[log] [2019-06-11T20:06:01.695Z] Found [4] stylesheets to download
[log] [2019-06-11T20:06:01.695Z] Downloading stylesheets and populating media queue
{"name":"mwoffliner","hostname":"bz-HP-Laptop-15-bs1xx","pid":11677,"level":60,"err":{"message":"","name":"TypeError","stack":"TypeError: Cannot read property 'status' of undefined\n    at FunctionCall.call.retryIf [as retryPredicate_] (/home/bz/npm/lib/node_modules/mwoffliner/lib/Downloader.js:372:52)\n    at FunctionCall.handleFunctionCallback_ (/home/bz/npm/lib/node_modules/mwoffliner/node_modules/backoff/lib/function_call.js:177:21)\n    at /home/bz/npm/lib/node_modules/mwoffliner/lib/Downloader.js:483:21\n    at Generator.throw (<anonymous>)\n    at rejected (/home/bz/npm/lib/node_modules/mwoffliner/lib/Downloader.js:5:65)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)","levelPath":"fatal/service-runner/unhandled"},"msg":"Cannot read property 'status' of undefined","time":"2019-06-11T20:06:01.720Z","v":0}
{"name":"mwoffliner","hostname":"bz-HP-Laptop-15-bs1xx","pid":11677,"level":60,"levelPath":"fatal/service-runner/unhandled","msg":"Cannot read property 'status' of undefined","time":"2019-06-11T20:06:01.721Z","v":0}
```

Mwoffliner is now stuck, since minutes, producing no output, the basic error being "Cannot read property 'status' of undefined".

What to do now?

Thank you very much!

**Comment by kelson42** [comment]
@ISNIT0 I confirm multiple errors within mwoffliner in my attempt to scrape halachipedia.com

**Comment by ISNIT0** [comment]
@kelson42 With what version? I think this is fixed in master (1.9.3 rcs)

**Comment by kelson42** [comment]
@ISNIT0 I have tested with the last rc and I can not create properly the ZIM.

**Comment by ISNIT0** [comment]
@kelson42 With this error? `Cannot read property 'status' of undefined `

**Comment by kelson42** [comment]
@ISNIT0 not that I was able to see.

**Comment by binyominzeev** [comment]
I just updated to 1.9.3-rc3 with the following:

```
npm install -g mwoffliner@1.9.3-rc3
```

And now I get the following error message:

```
bz@bz-HP-Laptop-15-bs1xx:~$ mwoffliner --mwUrl=http://www.halachipedia.com --adminEmail=szvb*******@gmail.com --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php
module.js:549
    throw err;
    ^

Error: Cannot find module 'src/stores'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bz/npm/lib/node_modules/mwoffliner/lib/util/rewriteUrls.js:24:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/bz/npm/lib/node_modules/mwoffliner/lib/util/saveArticles.js:33:23)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

**Comment by ISNIT0** [comment]
Okay, this is a known issue https://github.com/openzim/mwoffliner/issues/812

I think the 'status' of undefined issue is fixed in master though

**Comment by kelson42** [comment]
@ISNIT0 To me it seems here that the fundamental problem is the backend generates really quickly errors because it is overloaded (ant this is not HTTP  421). So MWoffliner does not scale down automatically quickly (and without HTTP 421 errors this is difficult to know why it should).

@binyominzeev We have released 1.9.3 yesterday, the error you have repored in the rc has been fixed. The overall problem stays here but it will be difficult to fix it quickly because the online version is really slow and does not really generate comprehensive errors.

**Comment by ISNIT0** [comment]
I'm seeing a lot of this kind of error: 
```
[warn] [2019-06-14T09:34:28.229Z] Failed to download mobile article [Aseret_Yimei_Teshuva], trying desktop article instead {
	"status": 503,
	"type": "internal_error",
	"detail": "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>503 Service Unavailable</title>\n</head><body>\n<h1>Service Unavailable</h1>\n<p>The server is temporarily unable to service your\nrequest due to maintenance downtime or capacity\nproblems. Please try again later.</p>\n</body></html>\n",
	"method": "GET",
	"uri": "/www.halachipedia.com/v1/page/mobile-sections/Aseret_Yimei_Teshuva"
}
```
@kelson42 I don't see any 421 errors, just 503s...

**Comment by binyominzeev** [comment]
Thank you very much!

Now I tried to export all pages and import to local MediaWiki instance.

```
bz@bz-HP-Laptop-15-bs1xx:~/websites/halachipedia$ mwoffliner --mwUrl=http://127.0.0.1/mediawiki/ --adminEmail=szvb*****@gmail.com --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php
```

It generated a lot of ECONNREFUSED errors like this:

```
{"name":"mcs","hostname":"bz-HP-Laptop-15-bs1xx","pid":16936,"level":50,"message":"Error: connect ECONNREFUSED 127.0.0.1:443","status":504,"type":"internal_http_error","detail":"Error: connect ECONNREFUSED 127.0.0.1:443","request_id":"2941ac12-8e94-11e9-b9b2-31af01dd2bed","request":{"url":"/127.0.0.1/v1/page/mobile-sections/Orach_Chaim","headers":{"user-agent":"axios/0.18.1","x-request-id":"2941ac12-8e94-11e9-b9b2-31af01dd2bed"},"method":"GET","params":{"0":"/127.0.0.1/v1/page/mobile-sections/Orach_Chaim"},"query":{},"remoteAddress":"127.0.0.1","remotePort":38214},"levelPath":"error/504","msg":"Error: connect ECONNREFUSED 127.0.0.1:443","time":"2019-06-14T11:04:20.999Z","v":0}
```

And at the end it generated a fatal error which tried to access mediawiki/w/load.php instead of mediawiki/load.php (although I was not pointing to directory "w", and api.php as well was accessed in its correct place):

```
Failed to run mwoffliner after [188s]: { Error: Request failed with status code 404
    at createError (/home/bz/npm/lib/node_modules/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/bz/npm/lib/node_modules/mwoffliner/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/bz/npm/lib/node_modules/mwoffliner/node_modules/axios/lib/adapters/http.js:202:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 60000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        accept: 'text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"',
        'cache-control': 'public, max-stale=2678400',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'MWOffliner/HEAD (szvbinjomin@gmail.com)',
        cookie: '' },
     method: 'get',
     url: 'http://127.0.0.1/mediawiki/w/load.php?debug=false&lang=en&modules=startup&only=scripts&skin=vector&version=&*',
     responseType: 'arraybuffer',
     data: undefined },
```

**Comment by binyominzeev** [comment]
OK, now I found the error and solution in issue #764, and it successfully produced the ZIM file.

Only the templates / images / modules are missing, any content which is not the text pages themselves -- I don't know if there is a way to export them seperately. Please let me know if anybody knows, or a way to scrape the original site. Thank you again!

**Comment by binyominzeev** [comment]
Now I did some improvements on the local site, added favicon.ico, and it seemingly crashed mwoffline:

```
bz@bz-HP-Laptop-15-bs1xx:~/websites/halachipedia$ mwoffliner --mwUrl=http://127.0.0.1/mediawiki/ --adminEmail=szvb*****@gmail.com --redis=redis://127.0.0.1:6379 --mwWikiPath=/ --mwApiPath=api.php --mwModulePath=/
[log] [2019-06-14T12:10:30.664Z] Using Tmp Directories: { outputDirectory: '/home/bz/websites/halachipedia/out/',
  cacheDirectory: '/home/bz/websites/halachipedia/cac/dumps-1560514230662/',
  dumpTmpDir: '/tmp/mwo-dump-1560514230664' }
[log] [2019-06-14T12:10:30.687Z] Getting text direction...
[log] [2019-06-14T12:10:30.688Z] Getting site info...
[log] [2019-06-14T12:10:30.689Z] Getting sub-title...
[log] [2019-06-14T12:10:31.610Z] Text direction is [ltr]
[log] [2019-06-14T12:10:31.891Z] Using a local MCS instance, couldn't find a remote one
[log] [2019-06-14T12:10:31.891Z] Starting Parsoid & MCS
{"name":"parsoid","hostname":"bz-HP-Laptop-15-bs1xx","pid":26457,"level":30,"levelPath":"info","msg":"loading ...","time":"2019-06-14T12:10:32.640Z","v":0}
{"name":"parsoid","hostname":"bz-HP-Laptop-15-bs1xx","pid":26457,"level":30,"levelPath":"info","msg":"ready on :8000","time":"2019-06-14T12:10:32.688Z","v":0}
{"name":"mcs","hostname":"bz-HP-Laptop-15-bs1xx","pid":26457,"level":30,"levelPath":"info","msg":"Worker 26457 listening on 0.0.0.0:6927","time":"2019-06-14T12:10:32.835Z","v":0}
[log] [2019-06-14T12:10:32.846Z] Worker [0] getting article range [0-50] of [1] [5000%]
[log] [2019-06-14T12:10:33.165Z] Got [500] articles from namespace [0]
[log] [2019-06-14T12:10:33.257Z] Got [257] articles from namespace [0]
[log] [2019-06-14T12:10:33.257Z] Doing dump
[log] [2019-06-14T12:10:33.258Z] Writing zim to [/home/bz/websites/halachipedia/out/127_hu_all_2019-06.zim]
[log] [2019-06-14T12:10:33.258Z] Flushing redis file store
Tmp directory already exists, deleting [/home/bz/websites/halachipedia/out/127_hu_all_2019-06.tmp]
[log] [2019-06-14T12:10:34.834Z] Found [2] stylesheets to download
[log] [2019-06-14T12:10:34.834Z] Downloading stylesheets and populating media queue
[log] [2019-06-14T12:10:34.865Z] Downloaded stylesheets
[log] [2019-06-14T12:10:34.866Z] Saving favicon.png...
Failed to run mwoffliner after [5s]: {
	"stack": "TypeError: Cannot read property 'includes' of undefined\n    at /home/bz/npm/lib/node_modules/mwoffliner/lib/Downloader.js:478:72\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/bz/npm/lib/node_modules/mwoffliner/lib/Downloader.js:4:58)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
	"message": "Cannot read property 'includes' of undefined"
}


**********

Cannot read property 'includes' of undefined

**********


[log] [2019-06-14T12:10:34.977Z] Exiting with code [2]
[log] [2019-06-14T12:10:34.977Z] Deleting tmp dump dir [/tmp/mwo-dump-1560514230664]
[log] [2019-06-14T12:10:34.977Z] Clearing Cache Directory

```

I don't understand why is it looking for favicon.png, when I have favicon.ico in its proper place, but I added that as well -- it did not help.

**Comment by binyominzeev** [comment]
Never mind, I figured out the issue, it was a $wgLogo with "webp" extension. I converted it to JPEG and now it runs.

**Comment by kelson42** [comment]
> Only the templates / images / modules are missing, any content which is not the text pages themselves -- I don't know if there is a way to export them seperately. Please let me know if anybody knows, or a way to scrape the original site. Thank you again!

I'm not sure it makes any sense to scrape template pages. You have to understand that we anyway scrape HTML, not the wiki code. For the images, there is no way so far to download pictures in highres. You can try to download the "image" namespace by adding its code/number with the option `--addNamespaces`... but not sure about the result. Regarding the "modules", I'm not sure what you mean.

**Comment by kelson42** [comment]
@binyominzeev If I understand properly this is now working fine. What is the exact command line you are using? Would you like us to generate it automatically each month?

**Comment by binyominzeev** [comment]
That would be wonderful, thank you! At the same time, unfortunately, it is not working now, rather it produces the same 503's as indicated in the comment above: https://github.com/openzim/mwoffliner/issues/810#issuecomment-502043452

Instead, I made a local copy (Mediawiki export, and then import), and scraped localhost. This worked, however, did not produce an ideal result.

So, it there could be achieved anything better than that, it would be much appreciated. Thank you!

**Comment by kelson42** [comment]
We have a recipe now for halachipedia.com in the Zimfarm. But we are impacted by the Parsoid timeout problem. Duplicate #660
