### ISSUE TITLE
WPEN movie selection can not be done with 1.9.3

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#832]
@Joe We can discuss this, but the problem for now, it that mwoffliner seems to crash, see https://farm.openzim.org/tasks/5d02afb98b9bc40020fc534e

Command

```
mwoffliner --adminEmail="contact@kiwix.org" --format="nopic" --format="novid" --mwUrl="https://en.wikipedia.org/" --customZimFavicon="https://upload.wikimedia.org/wikipedia/commons/8/84/Biofilm.png" --customZimTitle="Movies by Wikipedia" --customZimDescription="A selection of Wikipedia articles on movies" --articleList="http://download.kiwix.org/wp1/enwiki/customs/movies" --useCache --redis="redis://redis" --outputDirectory="/output"
```

Standard Error
```
[error] [2019-06-13T20:33:06.278Z] Error retrieving article: HTTP 404
[error] [2019-06-13T21:09:39.723Z] Error retrieving article: HTTP 404
[error] [2019-06-13T23:54:11.999Z] Error retrieving article: HTTP 404
[error] [2019-06-14T00:43:50.921Z] Error retrieving article: HTTP 404
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to redis:6379 failed - write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:788:14)
Emitted 'error' event at:
    at RedisClient.on_error (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mwoffliner/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:436:5)
    at onwrite (_stream_writable.js:461:5)
    at _destroy (internal/streams/destroy.js:49:7)
    at Socket._destroy (net.js:613:3)
    at Socket.destroy (internal/streams/destroy.js:37:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:790:10)
```

**Comment by kelson42** [comment]
Last trial has failed in the same manner https://farm.openzim.org/tasks/5d0bbd1c2d31fad1b7c5a68f

**Comment by ISNIT0** [comment]
The log has been fixed relatively recently (to include the failed articleId). 
I really don't think a 404 could cause a Redis issue though...

**Comment by ISNIT0** [comment]
Any news on this redis error?

**Comment by kelson42** [comment]
@ISNIT0 A [PR](https://github.com/openzim/zimfarm/pull/256) has been done to also upload the Redis log. It should be merged within two days in the zimfarm. We hope that way to get important information by next problem.

**Comment by kelson42** [comment]
A new run has been started, lets see what comes out https://farm.openzim.org/tasks/5d1ca32841340ade48d038cb

**Comment by ISNIT0** [comment]
I'm also doing this locally

**Comment by kelson42** [comment]
@ISNIT0 Not bad, even if I strongly suspect here a problem related to the zimfarm - not the mwoffliner.

**Comment by kelson42** [comment]
@ISNIT0 @rgaudin The built failed again, but this time we have a bit of redis log available:
```
1:C 03 Jul 2019 12:44:25.086 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 03 Jul 2019 12:44:25.086 # Redis version=5.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 03 Jul 2019 12:44:25.086 # Configuration loaded
1:M 03 Jul 2019 12:44:25.090 * Running mode=standalone, port=6379.
1:M 03 Jul 2019 12:44:25.090 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 03 Jul 2019 12:44:25.091 # Server initialized
1:M 03 Jul 2019 12:44:25.091 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 03 Jul 2019 12:44:25.091 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 03 Jul 2019 12:44:25.091 * Ready to accept connections
1:M 03 Jul 2019 12:44:25.091 * The server is now ready to accept connections at /tmp/sockets/redis_5d1ca32841340ade48d038cb.sock
```

@rgaudin I don't see anything obvious - no error happening :(
