### ISSUE TITLE
E2E tests do not pass

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#926]
```
   ✔ Created 5 outputs
    ✔ nopic has enough files
    ✔ nopic has enough redirects
    ✔ nopic has 10 articles

    ✖ Zimcheck passes
    ------------------
      operator: ok
      expected: true
      actual:   false
      at: Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
      stack: |-
  Error: Zimcheck passes
  at Test.assert [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Test.assert (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:344:10)
  at Test.bound [as ok] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
  at Generator.throw (<anonymous>)
  at rejected (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:5:65)
  at process._tickCallback (internal/process/next_tick.js:68:7)

    ✔ novid has enough files
    ✔ novid has enough redirects
    ✔ novid has 10 articles

    ✖ Zimcheck passes
    ------------------
      operator: ok
      expected: true
      actual:   false
      at: Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
      stack: |-
  Error: Zimcheck passes
  at Test.assert [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Test.assert (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:344:10)
  at Test.bound [as ok] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
  at Generator.throw (<anonymous>)
  at rejected (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:5:65)
  at process._tickCallback (internal/process/next_tick.js:68:7)

    ✔ nozim has enough files
    ✔ nozim has enough redirects
    ✔ nozim has 10 articles

    ✖ Zimcheck passes
    ------------------
      operator: ok
      expected: true
      actual:   false
      at: Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
      stack: |-
  Error: Zimcheck passes
  at Test.assert [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Test.assert (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:344:10)
  at Test.bound [as ok] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
  at Generator.throw (<anonymous>)
  at rejected (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:5:65)
  at process._tickCallback (internal/process/next_tick.js:68:7)

    ✔ nopdf has enough files
    ✔ nopdf has enough redirects
    ✔ nopdf has 10 articles

    ✖ Zimcheck passes
    ------------------
      operator: ok
      expected: true
      actual:   false
      at: Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
      stack: |-
  Error: Zimcheck passes
  at Test.assert [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Test.assert (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:344:10)
  at Test.bound [as ok] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
  at Generator.throw (<anonymous>)
  at rejected (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:5:65)
  at process._tickCallback (internal/process/next_tick.js:68:7)

    ✔ nodet has enough files
    ✔ nodet has enough redirects
    ✔ nodet has 10 articles

    ✖ Zimcheck passes
    ------------------
      operator: ok
      expected: true
      actual:   false
      at: Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
      stack: |-
  Error: Zimcheck passes
  at Test.assert [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:226:54)
  at Test.bound [as _assert] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Test.assert (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:344:10)
  at Test.bound [as ok] (/home/kelson/code/mwoffliner/node_modules/tape/lib/test.js:77:32)
  at Object.<anonymous> (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:61:19)
  at Generator.throw (<anonymous>)
  at rejected (/home/kelson/code/mwoffliner/test/e2e/en10.e2e.test.ts:5:65)
  at process._tickCallback (internal/process/next_tick.js:68:7)

    ✔ Scraped EN top 10
    ✔ Redis has been cleared



  Failed Tests: There were 5 failures

    Simple articleList

      ✖ Zimcheck passes
      ✖ Zimcheck passes
      ✖ Zimcheck passes
      ✖ Zimcheck passes
      ✖ Zimcheck passes


  total:     32
  passing:   27
  failing:   5
  duration:  1m 28.3s


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mwoffliner@1.9.5 test:e2e: `tape -r tsconfig-paths/register -r ts-node/register test/e2e/*.test.ts | tap-spec`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mwoffliner@1.9.5 test:e2e script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kelson/.npm/_logs/2019-08-03T18_10_29_683Z-debug.log
```

**Comment by ISNIT0** [comment]
Which version of zimtools is installed on your machine?

**Comment by kelson42** [comment]
```
$ which zimcheck 
/usr/local/bin/zimcheck
$ zimcheck --version
1.0.3
```

I start the test with specific ENV variable.

**Comment by ISNIT0** [comment]
It also fails on my local.
The only reason it works on Travis is because zimcheck isn't found by the tests, to the ZIM isn't checked.

Specifically:
> ZIMCHECK_PATH=`find .. --name=zimcheck`

Which is incorrect and does not resolve to an actual path: https://travis-ci.org/openzim/mwoffliner/jobs/567198811#L5622

**Comment by ISNIT0** [comment]
This is the reason it fails for our locals:
https://github.com/openzim/zim-tools/issues/61

**Comment by kelson42** [comment]
@ISNIT0 If $ZIMCHECK_PATH is empty or undefined, it should try to use one in the PATH. This is what has been coded I think. Why it does not?

**Comment by ISNIT0** [comment]
It does, but the above `ZIMCHECK_PATH=` sets the path to an invalid `"find .. --name=zimcheck"`, which is then not found, and the search is cancelled

**Comment by kelson42** [comment]
@ISNIT0 Might be, but this has nothing to do with my ticket or does it?

**Comment by kelson42** [comment]
@ISNIT0 I'm not sure to fully understand, so `zimcheck` is found but it fails? If "yes" can we have an output somehow helpful? For now:
* It looks like a code crash
* I don't have details about what is wrong (I suspect this is about the `zimwriterfs` exit code?). But in that case it should be written, the output of `zimcheck` too - with the zimcheck command line. So the user can know where to start.

**Comment by ISNIT0** [comment]
As discussed here: https://github.com/openzim/mwoffliner/issues/668
`zimcheck` is an optional test dependency.
The code does log when `zimcheck` is not found, and then doesn't run the test.

Locally, zimcheck is found and run - which fails due to https://github.com/openzim/zim-tools/issues/61

On Travis, because of the broken `find` command, zimcheck is not found (https://travis-ci.org/openzim/mwoffliner/jobs/567198811#L5622), and so not run (https://travis-ci.org/openzim/mwoffliner/jobs/567198811#L5856)

**Comment by kelson42** [comment]
@ISNIT0 I think your last comment should go to #929, this is not related to that ticket or my comment.

**Comment by kelson42** [comment]
@ISNIT0 I hardly can understand how `zimcheck` could work fine with openzim/zim-tools#61, even on MacOS. The bug has nothing to do with the OS. I have I think made a working patch https://github.com/openzim/zim-tools/pull/62. But I still have on zimchecks which fails (instead of 4 before) and I have no clue what is going wrong, see https://github.com/openzim/mwoffliner/issues/926#issuecomment-517985209.

**Comment by ISNIT0** [comment]
@kelson42 I'm not sure what your above comment means.
The e2e tests fail locally because `zimcheck` fails. It fails with this log:
```
> zimcheck out/wikipedia_en_articlelist_2019-08.zim.tmp  
[INFO] Checking zim file out/wikipedia_en_articlelist_2019-08.zim.tmp
[INFO] Verifying Internal Checksum.. 
  [INFO] Internal checksum found correct
[INFO] Searching for metadata entries..
[INFO] Searching for Favicon..
[INFO] Searching for main page..
[INFO] Verifying Articles' content.. 
[INFO] Searching for redundant articles..
  Verifying Similar Articles for redundancies..
[ERROR] Invalid internal links found :
  A//Manuel_A._Torres (./Manuel_A._Torres) was not found in article A/index
[INFO] Overall Test Status: Fail
[INFO] Total time taken by zimcheck: 2 seconds.
```

This is an invalid failure which I have reported.

**Comment by kelson42** [comment]
So it seems I have fixed it in zimcheck... but we need a release. In the mantime I would recommend to use a nightly build.

**Comment by ISNIT0** [comment]
Fixed with nightly, but we should release zim-tools asap
