### ISSUE TITLE
Unable to scrape http://processors.wiki.ti.com 

### ISSUE THREAD

**Issue by kelson42** [openzim/mwoffliner#983]
```
$ mwoffliner --mwUrl=http://processors.wiki.ti.com --mwWikiPath=index.php/ --mwApiPath="api.php" --adminEmail="kelson@kiwix.org" --verbose
[log] [2019-09-11T06:47:59.814Z] Getting text direction...
[log] [2019-09-11T06:47:59.815Z] Getting site info...
[log] [2019-09-11T06:47:59.816Z] Getting sub-title...
[info] [2019-09-11T06:47:59.817Z] Downloading [http://processors.wiki.ti.com/index.php/]
[info] [2019-09-11T06:47:59.817Z] Getting JSON from [http://processors.wiki.ti.com/api.php?action=query&meta=siteinfo&format=json&siprop=general|namespaces|statistics|variables|category|wikidesc]
[info] [2019-09-11T06:47:59.818Z] Downloading [http://processors.wiki.ti.com/index.php/]
[error] [2019-09-11T06:48:00.244Z] FATAL - Failed to get MediaWiki Metadata
Failed to run mwoffliner after [1s]: {
	"stack": "TypeError: Cannot read property 'general' of undefined\n    at MediaWiki.<anonymous> (/usr/lib/node_modules/mwoffliner/lib/MediaWiki.js:205:40)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/lib/node_modules/mwoffliner/lib/MediaWiki.js:4:58)\n    at process._tickCallback (internal/process/next_tick.js:68:7)",
	"message": "Cannot read property 'general' of undefined"
}


**********

Cannot read property 'general' of undefined

**********

```

Reported first at https://sourceforge.net/p/kiwix/bugs/818/

**Comment by kelson42** [comment]
New attempt within the Zimfarm https://farm.openzim.org/recipes/processors_wiki

**Comment by kelson42** [comment]
Works now https://download.kiwix.org/zim/other/processors_en_all_2020-03.zim

**Comment by kelson42** [comment]
The problem is that the wiki is so pulluted with SPAM that I had to remove the ZIM file and deactive the recipe in ZIM farm.
