### ISSUE TITLE
Failure in “Downloading module dependencies” on archwiki

### ISSUE THREAD

**Issue by rgaudin** [openzim/mwoffliner#988]
Trying to scrape [archlinux wiki](https://wiki.archlinux.org/) with `1.9.10`, it systematically fails at `Downloading module dependencies` stage reporting a `403` Error.

It was already failing the same way with [`1.8.6`](https://farm.openzim.org/tasks/5ccdad2091ae220020fc86b6)… but we had apparently successful runs in March and April 2019 (our latest ZIMs). We don't have logs of those in the zimfarm so no idea about the version nor flags.

```
Failed to run mwoffliner after [7388s]: { Error: Request failed with status code 403
    at createError (/tmp/mwoffliner/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/tmp/mwoffliner/node_modules/axios/lib/core/settle.js:18:12)
    at Unzip.handleStreamEnd (/tmp/mwoffliner/node_modules/axios/lib/adapters/http.js:202:11)
    at Unzip.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 60000,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        accept:
         'text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"',
        'cache-control': 'public, max-stale=86400',
        'accept-encoding': 'gzip, deflate',
        'user-agent': 'MWOffliner/HEAD (contact@kiwix.org)',
        cookie: '' },
     method: 'get',
     url:
      'https://wiki.archlinux.org/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*',
     responseType: 'arraybuffer',
     data: undefined },
  request:
   ClientRequest {
     _events:
      [Object: null prototype] {
        socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'wiki.archlinux.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'wiki.archlinux.org',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 6491353,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 378,
        [Symbol(kBytesWritten)]: 371,
        [Symbol(connect-options)]: [Object] },
     connection:
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: 'wiki.archlinux.org',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 7,
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'wiki.archlinux.org',
        _readableState: [ReadableState],
        readable: false,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: false,
        parser: null,
        _httpMessage: [Circular],
        write: [Function: writeAfterFIN],
        [Symbol(res)]: null,
        [Symbol(asyncId)]: 6491353,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 378,
        [Symbol(kBytesWritten)]: 371,
        [Symbol(connect-options)]: [Object] },
     _header:
      'GET /w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&* HTTP/1.1\r\naccept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\r\ncache-control: public, max-stale=86400\r\naccept-encoding: gzip, deflate\r\nuser-agent: MWOffliner/HEAD (contact@kiwix.org)\r\ncookie: \r\nHost: wiki.archlinux.org\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 443,
        protocol: 'https:',
        options: [Object],
        requests: {},
        sockets: {},
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        maxCachedSessions: 100,
        _sessionCache: [Object] },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path:
      '/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        socket: [TLSSocket],
        connection: [TLSSocket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 403,
        statusMessage: 'Forbidden',
        client: [TLSSocket],
        _consuming: false,
        _dumped: false,
        req: [Circular],
        responseUrl:
         'https://wiki.archlinux.org/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 0,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl:
         'https://wiki.archlinux.org/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      [Object: null prototype] {
        accept: [Array],
        'cache-control': [Array],
        'accept-encoding': [Array],
        'user-agent': [Array],
        cookie: [Array],
        host: [Array] } },
  response:
   { status: 403,
     statusText: 'Forbidden',
     headers:
      { server: 'nginx/1.16.1',
        date: 'Tue, 17 Sep 2019 12:12:38 GMT',
        'content-type': 'text/html',
        'transfer-encoding': 'chunked',
        connection: 'close',
        'strict-transport-security': 'max-age=31536000; includeSubdomains; preload' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 60000,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'get',
        url:
         'https://wiki.archlinux.org/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*',
        responseType: 'arraybuffer',
        data: undefined },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [TLSSocket],
        connection: [TLSSocket],
        _header:
         'GET /w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&* HTTP/1.1\r\naccept: text/html; charset=utf-8; profile="https://www.mediawiki.org/wiki/Specs/HTML/1.8.0"\r\ncache-control: public, max-stale=86400\r\naccept-encoding: gzip, deflate\r\nuser-agent: MWOffliner/HEAD (contact@kiwix.org)\r\ncookie: \r\nHost: wiki.archlinux.org\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path:
         '/w/load.php?debug=false&lang=en&modules=mediawiki&only=scripts&skin=vector&version=&*',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      <Buffer 3c 68 74 6d 6c 3e 0d 0a 3c 68 65 61 64 3e 3c 74 69 74 6c 65 3e 34 30 33 20 46 6f 72 62 69 64 64 65 6e 3c 2f 74 69 74 6c 65 3e 3c 2f 68 65 61 64 3e 0d ... > } }


**********

Request failed with status code 403

**********
```

https://farm.openzim.org/tasks/5d808aea1d1619754c6a5947
https://farm.openzim.org/tasks/5d80b0bd1d1619754c6a596f

**Comment by kelson42** [comment]
The config of MWoffliner was wrong/outdated. See the correct/new one https://farm.openzim.org/schedules/archlinux_wiki

**Comment by rgaudin** [comment]
yes, sorry forgot to close the issue :/
